### ISSUE TITLE
Add refresh/reload option for Zim files

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1072]
**Is your feature request related to a problem? Please describe.**
Many times, the Zim files do not load properly( pics are broken) and the page or file has to be reopened from the beginning (if not bookmarked or if it is not main page), which is not good user experience.

**Describe the solution you'd like**
Add a refresh/reload option in the overflow menu. 

**Describe alternatives you've considered**
Already the menu list is already so long, so adding one more option may not be advisable. So, I want to revamp the overflow menu to what google chrome has. I mean, use symbols instead of texts for  bookmarks, refresh, and others. This suggestion was also given by @abdulwd  in issue #973. But I will open a separate ticket for revamping. So, I request you to let me add it and after this, I will revamp it.

**Additional context**
![refresh_menu](https://user-images.githubusercontent.com/34706326/54074852-c1409c80-42bd-11e9-99c7-8d5972f2c9d9.gif)

**Comment by kelson42** [comment]
@macgills @sonusourav I don't understand what is the problem here. If pics are broken, there is a problem the libzim/jni/render OR the ZIM is broken itself. In both case we need a concrete repro case and this has nothing to do with any menu. So for me here (1) the problem is not clear (2) the solution is not related. Therefore I propose to close that ticket.
