### ISSUE TITLE
Overflow menu shows blank menu item in webview actionbar

### ISSUE THREAD

**Issue by sidkathuria14** [kiwix/kiwix-android#1098]
**Describe the bug**
In webview, the Contextual Action Bar appears on the text selection(long click on text). In the Contextual Action Bar, the overflow menu button shows no menu item or maybe shows an item with empty string title.

**Expected behavior**
The overflow menu should show Read Aloud button.

**Screenshots**
![Screenshot_20190320_184113](https://user-images.githubusercontent.com/29261743/54686848-39ba1f80-4b40-11e9-8533-333b219dc14e.jpg)

**Environment**
- Version of Kiwix Android :  The lastest version available on playstore
- Device : Vivo V3
- OS version : API level 21

**Comment by sonusourav** [comment]
@sidkathuria14  Don't use play store version, install the app from GitHub repo( with KiwixDebug Build variant). Play store version is not used for development purpose, and it does not have all the updates.
Adding to your issue, it is not present in the GitHub version.

**Comment by angmas1** [comment]
I want to contribute to this app and am trying to build it but I am unable to import this in Android Studio. I have been trying to ask for help on freenode since last 2 days.
After importing, I get error sdk missing, so I made a file local.properties with correct sdk path. Then I get androidmanifest missing with a popup saying Android structure found with a manifest so I clicked ok. Then on running gradlew build. I get app:lint failed with this error.
The first 3 errors (out of 5) were:   C:\Users\Anunay\Desktop\repos\kiwix-android\app\src\main\java\org\kiwix\kiwixmobile\downloader\DownloadService.java:281: Error: Builder.mActions can only be accessed from within the same library group (gr oupId=androidx.core) [RestrictedApi]       notification.get(notificationID).mActions.get(0).title = getString(R.string.download_resume);
On continuing, I fail 2 tests. Then on running gradlew build -x test, build passes but I am still unable to run app. Please help!

**Comment by abdulwd** [comment]
@angmas1 Can you try this https://github.com/kiwix/kiwix-android/pull/974#issuecomment-463157239 and select kiwixDebug as build variant and try to install the app.

**Comment by angmas1** [comment]
@abdulwd Thank you very much. Finally resolved it.
