### ISSUE TITLE
Explain branching/merging strategy in CONTRIBUTING.md

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1200]
Add a new paragraph "Branching" in `CONTRIBUTING.md`

Following questions should be answered
* What are the "develop", "release" and "master" branches or any other branches?
* How to merge a PR?
* When to do rebase?
* How releases are made? How to deal with many releases in parallel?

**Comment by macgills** [comment]
I think I will make a PR onto master because the next time master is getting updated is for 3.0.
Brief template of my answers so we can discuss them here:
Develop is what we branch off of while working on new features, develop is the actively worked on next release of the app.
Release should be ignored, it is a temporary measure that will go away shortly (will not include this in the contrib section).
Master is a history of releases, once committed to from develop and tagged we create a release on the play store & GitHub releases.
All work should be done on feature branches either `feature/*` or `<username>/feature/*`.
If we need to release a fix or update to an existing version we create a `hotfix/*` branch off of master, commit back to master, tag and release, merge master to develop.
All PRs will be merge committed after they have passed all checks and have at least 1 reviewer approving.
Rebasing should essentially never happening, each branch should have distinct history so it should be avoided.
