### ISSUE TITLE
Improve "unknown content" handling 

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#121]
If a content (mime-type) is unknown or if there is not associated app, then it's impossible to access the content (link target). In such cases, the Kiwix app should propose to download/save the content (or maybe give a choice of apps to open it)?.

Reported first at https://sourceforge.net/p/kiwix/feature-requests/926/

**Comment by mhutti1** [comment]
@kelson42 I am not entirely sure what this means. Do you mean we should give the option to download corrupted ZIM files?

**Comment by kelson42** [comment]
No, if you have for example an EPUB file in a ZIM file, by clicking on the link Kiwix should provide a list of app to open the EPUB file (as Kiwix itself is not able to deal with it). Or at least shoudl propose to save it somewhere.

**Comment by Aditya-Sood** [comment]
@kelson42 @mhutti1 
Based on what I know, one can find out the type of file being referred to by the link; and then use an _intent_ to open it (which will automatically give the user a list of apps which can open that particular type of file).

If this is how you want it done, can I work on this issue?

**Comment by mhutti1** [comment]
If you are able to reproduce and then fix it then sure.

**Comment by Aditya-Sood** [comment]
Thanks
I'll get started

**Comment by Aditya-Sood** [comment]
@kelson42 
Could you give me some context as to where this issue occurs?
I downloaded and browsed a bunch of collections, but didn't come across one facing the above issue.

Videos are taken care of by the video player embedded in the browser, while hyperlinks to sites work just fine by requesting the user to select any one of the installed browsers to complete the task.

The only collection where the issue seemed apparent was the Project Gutenberg Library collection, but it was too large (39.8 GB) to download. Is it possible to download only a chunk of the whole zim file @mhutti1 , so that I can try some fixes for the issue on it?

**Comment by Aditya-Sood** [comment]
@mhutti1 @kelson42 
Could you help me out with reference to the above comment?

If not, then I would like to proceed to a bug that I came across while using the app ( #592 )
And please do inform about your decision, so that I start focussing on the new issue.

**Comment by mhutti1** [comment]
@Aditya-Sood I am not too sure. You could try using your own HTML by temporarily modifiying around line 481 of ZimContentProvider to serve your own HTML.

**Comment by Aditya-Sood** [comment]
I've resolved the bug (pull request #626 )
Will try and figure this out while I work on my proposal

**Comment by kelson42** [comment]
Sorry, for the late answer, but this is typically with the Gutenberg ZIM file at the time you clikc on an EPUB file. Then IMO the app should provide a list of app supporting that file format (epub).
