### ISSUE TITLE
Night mode does not work properly in library (with 3.0)

### ISSUE THREAD

**Issue by Aditya-Sood** [kiwix/kiwix-android#1301]
**Describe the bug**
Night mode inverts book icon colour in 'Get Content' library

**Steps to reproduce the behavior:**
Navigate to 'Get Content' library with in-app night mode enabled

**Screenshots**
<p align="center">
  <img src="https://user-images.githubusercontent.com/15438998/61582639-d6bab280-ab4a-11e9-93d7-8768ba57d6d2.png" width="350" title="bleh">
</p>

**Environment**
- Version of Kiwix Android : Tested until [this](https://github.com/kiwix/kiwix-android/commit/9c1d36657a7a476a1625d9f0a49a573a16eba322) commit on `develop`
- Device : Moto G5+
- OS version : 8.1.0

**Comment by Aditya-Sood** [comment]
@macgills might be similar to #905 
The double inversion to support night-mode might be required [here](https://github.com/kiwix/kiwix-android/blob/develop/app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/adapter/LibraryViewHolder.kt#L44) in LibraryViewHolder.kt

**Comment by kelson42** [comment]
What I see is that the text is not inverted ether. To me the Night mode is broken within the library.

**Comment by macgills** [comment]
Our nightmode implementation is strange, it is not theme driven.
Can anyone supply a justification for the current approach? @mhutti1

**Comment by mhutti1** [comment]
A theme approach might work better. I implemented most of this so long ago I can't really remember the full details, android has changed a lot too since then.

**Comment by macgills** [comment]
Undoubtedly, it is a shifting sea of sand.
So this ticket becomes "rework night mode completely", not a small amount of work

**Comment by Aditya-Sood** [comment]
@macgills when you say theme driven, is it different from specifying themes in styles.xml and using them?

**Comment by macgills** [comment]
It is a bit different and more powerful to use themes well as they are applied once in the Manifest and this affects every activity. Essentially we need to reparent our baseTheme to a material `DayNight` theme and then use android's inbuilt day night system to inform the system what mode we are currently in. It will also take some attribute chicanery and potentially supplying different resources for night mode. Basically it should allow us to stop querying `isNightMode` everywhere and just have all our widgets respect our theme innately.
I also habitually create a different xml file for themes because themes and styles while sharing a lot of similarities should not be used interchangeably.

**Comment by macgills** [comment]
[Chris Banes](https://medium.com/androiddevelopers/appcompat-v23-2-daynight-d10f90c83e94) goes into better detail than myself

**Comment by kelson42** [comment]
@macgills I assign you the ticket to avoid any ambiguity about who should fix night mode problems
