### ISSUE TITLE
Download always in pending status

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1318]
A user reported the following scenario:
- tried to download a zim file;
- Download window indicates "pending";
- Nothing more happens.

Kiwix Version 2.5.1  Build 220501
Sony Xperia XA   F3113
Android version 7.0 Build number 33.3.A.1.126

First reported at  #1304

**Comment by kelson42** [comment]
@Popolechien Would you be able to ask the user if he uses a blocker similar like Blokada (would be then a duplicate of #1304.
@macgills Any chance to detect this and avoid a download to be pending for years?

**Comment by macgills** [comment]
Is it possible to do so? Absolutely.
Do I think it will be useful to a user? Probably not, if the download is failing they have a problem and me just retrying is probably not going to help at all.

**Comment by kelson42** [comment]
@macgills If the download is failing, I don't like to have it reported as "pending". This is the problem. If there is a winning strategy to try to avoid that or recover from that, is another one.

**Comment by macgills** [comment]
The thing is if the DownloadManager tells me it is Pending then it _is_ pending, it is just waiting for some issue to resolve itself. Pending is a very valid state and can be a state for a very long time because of the nature of data connections.
We can fake `has been pending a while` but I think the best way is to warn users about adblockers and the like, we can display it beneath the "No Downloads" text when downloads are empty? There are many options but allowing the user to reason about their scenario and the component they are interacting with is better when we actually show the truth of the scenario.
The more indirection we add on top of the real state of a system component I think the worse an experience we create.

**Comment by kelson42** [comment]
@macgills Thx, this is the kind of response I was aiming to. What I don't want is anything where we warn the users about this kind of scenario, even if they have no problem (which is the most probable scenario). But in that case we have somehow to detect this `has been pending a while`... and I understand your concern about that.

I don't really understand your proposal about "No downloads"... probably because I don't know well enough the app. I thought that if we have a pending download, then we have at least one item in the "Downloading" tab?!

**Comment by macgills** [comment]
When you have no downloads then the list is empty in the downloads tab and we show some text `No Downloads` or the like. We could add `Note: you may need to disable your adblocker to download zims` just below this when the list is empty. This means the message is always there in the app and they are likely to see it...… hmmm actually we are planning on removing the downloading section entirely so that is not a good spot for it.
A help section might be the best even though I hate help sections.

**Comment by Popolechien** [comment]
> @Popolechien Would you be able to ask the user if he uses a blocker similar like Blokada (would be then a duplicate of #1304.

I've asked and no, no blocker of any type.

**Comment by kelson42** [comment]
We use a totally different download library in 3.0 (than in 2.5). This bug might or might not appear anymore... but in both case the situation is totally different. A new ticket should then be open if necessary.
