### ISSUE TITLE
Kiwix 2.5.3 / 3.0 does not consistently look for files from previous installs.

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1397]
I noticed this while testing/comparing both nightly and 2.5.3 (android 9)

- I downloaded a zim file from the nightly (3005 from 19.08) and it was stored on my internal download folder. Yet, it could not find the zim file that had been stored on my external storage (at least not within a few minutes; at some point I just gave up waiting).
- I then uninstalled the nightly and re-installed 2.5.3: this one could find the zim on the external storage no problem, but couldn't find the one previously downloaded into the Download folder.

**Comment by macgills** [comment]
#1385 so first of all how did you get a file onto external storage on 9.0? Did you manually add it there? It should be completely impossible to download to an external sd card on 9.0.
I fixed the indefinite scanning bug yesterday in https://github.com/kiwix/kiwix-android/pull/1394, no files were being scanned in 9.0 because some code was throwing an exception.

I don't think we support downgrading your app though the observation is curious

**Comment by Popolechien** [comment]
@macgills The file was there from a previous install (pre 9.0).
Are you basically saying that from 9.0 onwards people won't be able to store content externally? (not just Kiwix users but everyone out there?)

**Comment by macgills** [comment]
The ticket I linked has all the details, I talked with @kelson42 for 1hr+ about it yesterday. I am working on a solution.
TL:DR apps can't write to public places on an SD card in 9.0

**Comment by Popolechien** [comment]
Ok. Closing this then?
