### ISSUE TITLE
Hotspot mode should be configurable

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1483]
* Default SSID should be KIWIX
* Default should be without password
* Automatically generated password should be shorter (6 charaters are enough IMO)
* SSID/password should be configurable

**Comment by kelson42** [comment]
@iadeelzafar Any way to configure that from Kiwix itself?

**Comment by iadeelzafar** [comment]
Short answer is 'no'.
This would be possible for <Oreo. But even for that, it will be possible via Reflection. 
So far, Android doesn't provides any official SDK to play with default hotspot.

**Comment by kelson42** [comment]
@iadeelzafar You mean >=Oreo?

**Comment by iadeelzafar** [comment]
No. <Oreo. Like how we were using reflection before to turn on hotspot on those devices. I even made the hotspot configurable for those devices using the same specs you've proposed here.
* No password by default.
* SSID should be 'Kiwix'
But since it was using reflection, we had to fall back to manual.

---------
On the other hand, SDK for >=Oreo doesn't allows us to play with the default hotspot. It was not toggling the default hotspot. If you noticed it's working, it starts a local hotspot with no internet. And there's no way so far, we could play with the local hotspot's SSID or key.

**Comment by kelson42** [comment]
You have confirmed implicitly in #1558 that with >=Oero, it is possible to start the Hotspot via the SDK.

**Comment by iadeelzafar** [comment]
@kelson42 toggling the hotspot(local Hotspot) is indeed possible for >=Oreo. And I even implemented that. But #1432 is a blocker currently for that.

**Comment by macgills** [comment]
Yes we encountered the issue of the hotspot randomly turning off and there was no easy solution nor even a hard one, we decided to fallback to this functionality so we had a stable feature.

**Comment by kelson42** [comment]
@macgills OK, I understand that, but this is not the point here. The point is: there is a SDK and I would like to get confirmation that there no method (even readonly) to read or/andwrite Hotspot SSID and password? With other words: please confirm the user has to go manually through settings to change/read the Hotspot SSID/password (which is extremely annoying).

**Comment by macgills** [comment]
There was a way but it stopped working in 5.0 from what I can gather and you had to use reflection. Perhaps creating a hotspot can still work as detailed [here](https://stackoverflow.com/questions/44175056/how-to-create-custom-wpa-hotspot-with-ssid-and-password-in-android) but turning it on should definitely not work. Should be mentioned how unreliable reflection is in android due to vendor specific android flavors not to mention how that is multiplicative with regards to android versions.

As Adeel said:
>Short answer is 'no'.
This would be possible for <Oreo. But even for that, it will be possible via Reflection.
So far, Android doesn't provides any official SDK to play with default hotspot.

The current vision of android seems to be that the developer cannot create hotspot configurations, they are the purview of the user and to be configured however they like. Mostly I think because there can only be one hotspot on a device and if multiple apps use it then it must be shared between them

**Comment by iadeelzafar** [comment]
The SDK we're using. Acc to the documentation it only provides 3 callback methods, onStart(), onStop(), onFailed. We can't do much other than that.
[StartLocalOnlyHotspot](https://developer.android.com/reference/android/net/wifi/WifiManager#startLocalOnlyHotspot(android.net.wifi.WifiManager.LocalOnlyHotspotCallback,%20android.os.Handler))


Some references:
https://stackoverflow.com/questions/47700717/change-wifi-hotspots-ssid-and-password-in-android-oreo-8-x
https://stackoverflow.com/questions/51248828/oreo-startlocalonlyhotspot-customize-ssid-and-password-api-26?rq=1

**Comment by kelson42** [comment]
@MohitMaliFtechiz Would this four points be feasible?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Would this four points be feasible?

unfortunately not. @macgills , @iadeelzafar  is correct.

* I have tried every posible way to change ssid in (Huawei LND-AL30 , Samsung tablet , emulator) and it's not allowing to change the ssid. it's every time returing the unknown ssid message after changing the ssid via code. because the issue is caused by a limitation in the device's firmware or software.
   
* It's only allowing this feature to system apps. In general, it is not possible to change the SSID of a WiFi network programmatically on Android without root access or system-level permissions. Changing the SSID of a network requires access to protected system settings and services, which are not available to regular apps.

Without root access or system-level permissions, the only way to change the SSID do it manually through the device's settings.

If you do have root access or system-level permissions, it may be possible to change the SSID programmatically using the code which i have tried. However, this should be done with caution, as it can have security implications and may cause compatibility issues with future updates or modifications to the device.

**Comment by kelson42** [comment]
You seem to answer only to part of the request. What about the password?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 , it uses the same API for password too and i have tried to change the password, but it always returning null whenever i changed the password via code.

**Comment by kelson42** [comment]
OK, so feature can not be implemented because platfoem limitation.
