### ISSUE TITLE
Sign CI build properly (Unable to install unsigned ARM nightly builds)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#151]
They can not be installed on my ARM based Android devices. Also tested by @mhutti1. Looks like the architecture is simply wrong.

Nightlies are available at https://download.kiwix.org/nightly/

**Comment by mgautierfr** [comment]
The PR https://github.com/kiwix/kiwix-lib/pull/55 should fix this.

The directories for native libs will be :
- arm
- aarch64 (instead of arm64 now)
- mipsel
- mips64el
- i686
- x86_64

@mhutti1, @kelson42, please let me know if the dir names are wrong.

**Comment by mhutti1** [comment]
I am not entirely sure if the directory name matters. The current architecture directory names are:

- arm64-v8a
- armeabi
- mips
- x86

**Comment by kelson42** [comment]
@mgautierfr I have no clue, but I would do it like it was before. I can also confirm that the x86(_64) can also not be installed. So this is a "generic" problem.

**Comment by mgautierfr** [comment]
The used directory will be (in correspondence to https://developer.android.com/ndk/guides/abis.html#sa):
- armeabi (instead of 'arm'),
- arm64-v8a (instead of 'arm64'),
- mips,
- mips64,
- x86,
 -x86_64.

It should fix install on `arm*` device (I can install the apk on my arm (32) device).
However, as the `x86*` directory is good, I don't know what is the problem here.

I don't have a intel device so I cannot test. I will try on a emulated device but I've some issue with kiwix on them (even the released version). I have more to investigate on this point.

The kiwix-lib PR need new dependencies archive generated daily to be merged. So fixed daily apks will come in two days at least.

**Comment by kelson42** [comment]
I still have the problem, the device still tels me "App not installed". @mhutti1 Does it still fails for you too?

**Comment by mhutti1** [comment]
@kelson42 It works for me. Are you using the right architecture?

**Comment by kelson42** [comment]
@mhutti1 That is a good news, I'll try again.

**Comment by kelson42** [comment]
@mgautierfr after verification it seems that @mhutti1 and myself confirm that (tested for ARM and x86):
* the debug builds work now fine 
* the release-unsigned fails.

**Comment by mgautierfr** [comment]
What is the error when trying to install the release-unsigned apk ?
`debug` and `release-unsigned` apks are build at the same time by gradle so I doubt that the architecture of the release-unsigned is wrong while the debug one is good.
Maybe it is because the release apk should be signed and you cannot install a unsigned one.

**Comment by kelson42** [comment]
@mgautierfr It simply says "App not installed"

**Comment by kelson42** [comment]
This is the log

```
I/PackageManager(  493): onServiceConnected
I/SurfaceFlinger(  473): id=291 Removed QackageInst (3/7)
I/SurfaceFlinger(  473): id=291 Removed QackageInst (-2/7)
I/power   (  493): *** release_dvfs_lock : lockType : 1 
D/CustomFrequencyManagerService(  493): releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1008000  uid : 1000  pid : 493  tag : ACTIVITY_RESUME_BOOSTER@6
W/ActivityManager(  493): mDVFSHelper.release()
D/STATUSBAR-NetworkController(  681): refreshSignalCluster: data=-1 bt=false
D/SensorService(  493):   -0.1 -0.1 9.9
I/PackageManager(  493): Copying native libraries to /data/app-lib/vmdl1979232574
D/STATUSBAR-NetworkController(  681): refreshSignalCluster: data=-1 bt=false
E/PackageParser(  493): Package org.kiwix.kiwixmobile has no certificates at entry AndroidManifest.xml; ignoring!
D/STATUSBAR-NetworkController(  681): refreshSignalCluster: data=-1 bt=false
D/STATUSBAR-NetworkController(  681): refreshSignalCluster: data=-1 bt=false
E/Watchdog(  493): !@Sync 67101
I/Monitor (  493): SIOP:: Current AP = 0, CP = 0
D/SensorService(  493):   -0.1 -0.1 9.8
D/dalvikvm(  493): GC_EXPLICIT freed 2195K, 26% free 33822K/45568K, paused 14ms+25ms, total 314ms
D/InstallAppProgress(11776): Installation error code: -103
D/STATUSBAR-NetworkController(  681): refreshSignalCluster: data=-1 bt=false
D/SensorService(  493):   -0.1 -0.1 9.9

```

**Comment by kelson42** [comment]
@mgautierfr After searching a bit it seems that is related to the signature. Could you please sign it and release kiwix-android_arm-release.apk instead?

**Comment by kelson42** [comment]
Here is the install via adb:
```
$ adb install kiwix-android_arm-release-unsigned.apk
7566 KB/s (13947683 bytes in 1.800s)
	pkg: /data/local/tmp/kiwix-android_arm-release-unsigned.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
```

**Comment by mhutti1** [comment]
@kelson42 As I told you it works for me. 

Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES] is probably because the apk is unsigned. Can you try the debug apk?

**Comment by kelson42** [comment]
@mhutti1 The debug works fine. We should not provide APK which can not be installed.

**Comment by mhutti1** [comment]
@kelson42 Well this is kind of the point of the unsigned one... I think you can enable a setting in Android to allow it if you want. The alterative would be we sign nightly builds, I don't think this is practical or a good idea from a security standpoint.

**Comment by kelson42** [comment]
@mhutti1 the option security > unknown source is already checked. So it should work. Does that work for you? Why providing an unsigned version is better than providing a signed version (what is the security problem you are talking about?)?

**Comment by mhutti1** [comment]
@kelson42 Well imo we should only sign releases so if someone installes a signed apk they know it was intended to be used and is unlikely to have bugs in it. I guess we could sign these with a separate key. I guess there are advantages to signing them with the main key in that they can easily be tested but we have beta tests for that imo and if you want to install this apk just self sign it or use the debug version.

**Comment by kelson42** [comment]
@mhutti1 Signing an APK does not mean this is an official release. It just mean that we have compiled it - and not someone else - and we can prove it. I also do not think this would really be misunderstood, in particular if this is available in the "nightly" directory.

So, I see three potential solutions to that problem:
* We understand how to get things done so all people can install these APKs (but I quite probable this is impossible at all)
* We sign with a self-signed certificate (with the option activated in security > unknown source, it should work http://www.androiddevelopment.org/tag/apk/)
* We stop producing these APKs in the nightlies (what is the added value to the debug version? I do not understand it)
* We sign it properly (would that be easy to do)?

**Comment by kelson42** [comment]
Here is the command to sign:
```
/BUILD_neutral/TOOLCHAINS/android-sdk-r25.2.3/build-tools/27.0.3/apksigner sign -ks \"${keystore}\" --ks-pass env:KIWIX_KEY --out signed_apks/app-$ENV{ORG_GRADLE_PROJECT_version_code}-release-signed.apk BUILD_android/kiwix-android/app/build/outputs/apk/kiwix/release/app-kiwix-release-unsigned.apk
```

**Comment by kelson42** [comment]
@macgills Reassigning to you as you work on the solution.

**Comment by macgills** [comment]
I will aim to create a deploy step on travis that will run only on cron job types with branch == develop.
Can I be pointed towards the code that uploads to https://download.kiwix.org/nightly/ and also any credentials that are required?

Nightly builds pose a strange question for our version codes, let me post the "javadoc" of our version codes
```
/*
* max version code: 210-0-00-00-00
* our template    : UUU-A-ZZ-YY-XX
* where:
* X = patch version
* Y = minor version
* Z = major version (+ 20 to distinguish from previous, non semantic, versions of the app)
* A = number representing ABI split
* U = unused
*/
```
seeing as how the leftmost digit can logistically only ever be 1 or 0 so I propose using that as a "snapshot flag".
Version codes are what determines if an application can install over another, we need to have a higher version code otherwise an uninstall will be necessary. It may help if I understood the usecase of nightlies more, who is consuming them and what do we expect to happen if they have a production app installed?
Should a nightly install over the nightly of the previous day?

**Comment by kelson42** [comment]
@mgautierfr This is why the compilation shoudl run properly from kiwix-buid. Kiwix-build Travis configuration does all of this already properly. I'm not sure this is the correct solution to rebuilt all of this somewhere else. Here again, please sort out the problem with @mgautierfr next week.

**Comment by macgills** [comment]
https://download.kiwix.org/nightly/2019-07-12/ nightly published here, closing
