### ISSUE TITLE
Refactor LocalFileTransfer: UI changes

### ISSUE THREAD

**Issue by Aditya-Sood** [kiwix/kiwix-android#1532]
As linked [here](https://github.com/kiwix/kiwix-android/pull/1276?_pjax=%23js-repo-pjax-container#pullrequestreview-274146177) and [here](https://github.com/kiwix/kiwix-android/pull/1276?_pjax=%23js-repo-pjax-container#issuecomment-521173777), the zim transfer module is to be tweaked with an entry point in the contextual action bar itself

- @mhutti1 @macgills are there any other UI changes that you'd like?
- On the issue of educating users about the feature, I think displaying a dialog (on a fresh install, with option to not show again) with a link to the [wiki page](https://github.com/kiwix/kiwix-android/wiki/Sending-ZIM-files-to-another-device) describing how to use it will be the best way to go.
Additionally, I can add a help icon within the LFT activity which links to the same webpage or displays an offline copy of the same

**Comment by macgills** [comment]
When you launch the sender/receiver it doesn't automatically ask for permission or start scanning on successfully getting permission, ideally user should never have to press the search icon and the search icon should probably be a refresh icon. Steal as much as possible from bluetooth ui in the phones system, this will be most analgous to the user.
There should ideally be 2 separate UIs for these separate contexts as reusing the ui is confusing to a user eg Nearby Devices having clickable list items doesn't make much sense for Receiver(not sure they should even have this just a "Broadcasting/Visible as [device name]"), Files For Transfer should not be visible for the Receiver until files actually start getting transferred to the receiver.
The blue lines make the device name look like an EditText, we probably don't even need the lines just some appropriate spacing

I do not like the wiki page option, it may be easisest but good ui/ux is intuitive. Many apps to highlight new features use a [showcase/highlight view](https://github.com/deano2390/MaterialShowcaseView), I generally find that to be an admittance that your ui is too poor to just be used correctly but the paradigm is well understood.

**Comment by kelson42** [comment]
@Aditya-Sood As we are now in the middle of the 3.2 milestone, is that a ticket you would like to work on?

**Comment by Aditya-Sood** [comment]
@kelson42 yes I definitely want to finish this ticket
I didn't understand the milestone part - do I have to ensure that this is done before the milestone items are complete?

**Comment by kelson42** [comment]
@Aditya-Sood I made an error, this is not part of the 3.2 milestone. But happy to read this is on your radar.

**Comment by kelson42** [comment]
@MohitMaliFtechiz This ticket is very old, can you please update it? Is that still valid? How much work would be needed to be fixed?

**Comment by MohitMaliFtechiz** [comment]
> When you launch the sender/receiver it doesn't automatically ask for permission or start scanning on successfully getting permission.

@kelson42, Yes it does not automatically ask permission, the application asks permission when the user clicks on the search icon which is good we should ask permission when the specific feature is used, but yes I agree with @macgills it should automatically search for the nearby devices when user grant the permission. In the current scenario, it takes permission on the first click, and after that, it requires the second click from the user to initiate the nearby search.

> ideally user should never have to press the search icon and the search icon should probably be a refresh icon. Steal as much as possible from bluetooth ui in the phones system, this will be most analgous to the user.

But for the icon, I think the search icon is good because here is the functionality for searching nearby devices so this icon is a good match for this functionality.

> Files For Transfer should not be visible for the Receiver until files actually start getting transferred to the receiver.

We are showing files to the receiver when the file sharing starts.

> The blue lines make the device name look like an EditText, we probably don't even need the lines just some appropriate spacing

Here I agree with @macgills device name looks like an `edit text` we should use the appropriate spacing or if we decrease this line height just like the below one then it will look good.

![1696337691584](https://github.com/kiwix/kiwix-android/assets/34593983/dd0b46e4-9fd7-4028-ae41-97789c394fcb)

> I do not like the wiki page option, it may be easisest but good ui/ux is intuitive. Many apps to highlight new features use a [showcase/highlight view](https://github.com/deano2390/MaterialShowcaseView), I generally find that to be an admittance that your ui is too poor to just be used correctly but the paradigm is well understood.

That would be great if we educate users like this it will enhance our UI. Most of the modern apps do the same to introduce how to use new features to the user.
