### ISSUE TITLE
Document translatable messages in translatewiki

### ISSUE THREAD

**Issue by amire80** [kiwix/kiwix-android#1605]
**Describe the bug**

Kiwix is localized in translatewiki. About 250 translatable message are currently not documented, and this makes localization more difficult. Every message, short and long, must be documented.

**Expected behavior**

The list of "untranslated" message documentation items must be empty. The list is available here:
https://translatewiki.net/wiki/Special:Translate?filter=%21translated&action=translate&language=qqq&group=kiwix

**Steps to reproduce the behavior:**
Click https://translatewiki.net/wiki/Special:Translate?filter=%21translated&action=translate&language=qqq&group=kiwix . The list has about 250 items.

Somebody who is familiar with how the software works must have a translatewiki account, click each row in this list and add a short explanation in English about each message—where does it appear, and what is its function.

**Screenshots**

**Environment**
(Not relevant. It's a problem in the source code and in the localization workflow.)

**Logs**

**Comment by kelson42** [comment]
@amire80 Thank you for your report. The problem here is that we are really short on resources and that most of the time the translation is OK (at least in the languages I know) without documentation... so it always felt with low priority (the problem is not new and does not only concern Kiwix for Android). The only way I think to solve this would be to have the developer creating this contextual information within the code at the time the string is created. This would be then automatically put upstream. I don't believe to be able to do that work properly in a second step... at least as long as we don't have paid people to handle that specifically. But maybe you have other ideas?

**Comment by kelson42** [comment]
@amire80 I think the way to follow is described in #1759. Wouldnthat be good to you. Then this ticket would be about getting the job done for all existing strings.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please document briefly each string to translate, so the translators get a bit of context.
