### ISSUE TITLE
A Problem with the Night Mode 

### ISSUE THREAD

**Issue by Scramjet911** [kiwix/kiwix-android#1707]
**Describe the bug**
The Night Mode of the app is not working correctly. When we change the night mode during functioning, the color of the text inside the drop-down menu does not change, while its background changes. This is fixed on a restart, where the night mode works correctly. The same is happening while switching off the night mode.
Along with this the theme of the homepage is also not changing along with the change in nightmode.
I have attached a gif exhibiting the behavior.

**Expected behavior**
The app can change from night mode off to on and vice versa and the text in the menu is readable in both modes and the homepage is also changing according to the mode selected.

**Steps to reproduce the behavior:**
1. Open the kiwix app
2. Select "Settings" from the menu
3. Switch the nightmode "ON" if currently "OFF" or vice versa
4. Exit the settings menu and select the dropdown menu (The three dots on the top corner)
5. Try to read the words.
6. Look at the homepage.

**Screenshots**
![kiwix(1)](https://user-images.githubusercontent.com/36035352/72902255-26c03f00-3d51-11ea-8b48-1fb3c2c67628.gif)

**Environment**
- Version of Kiwix Android : 3.1.3
- Device : Lenovo K8 Note
- OS version : Android 7.1.1

**Comment by macgills** [comment]
@Scramjet911 could you upload pictures? The compression in the video is quite severe and a clearer image may help with diagnosis.
I am testing this out on a 7.1.1 emulator to see if that is the root cause, working perfectly on my Nexus 8.1.0

**Comment by Scramjet911** [comment]
Right, I just noticed that. Sorry, here are the pictures
![1](https://user-images.githubusercontent.com/36035352/72905342-6ccbd180-3d56-11ea-95c6-66353bafa6ef.png)
![2](https://user-images.githubusercontent.com/36035352/72905344-6d646800-3d56-11ea-9a53-768602f51c57.png)
![3](https://user-images.githubusercontent.com/36035352/72905347-6dfcfe80-3d56-11ea-8147-5a5ab953cd1c.png)
![4](https://user-images.githubusercontent.com/36035352/72905348-6dfcfe80-3d56-11ea-92e8-667dc7f3ec83.png)

**Comment by Scramjet911** [comment]
Also, I noticed this bug on other devices of Android version 7.0.

**Comment by macgills** [comment]
My results on the emulator are different but similar:
![image](https://user-images.githubusercontent.com/3358282/72907334-9ae7ec00-3d2b-11ea-96d7-25fc2eedad31.png)

Is the 7.0 device also a lenovo?

**Comment by Scramjet911** [comment]
Not Lenovo but I they use the same Moto UI

**Comment by macgills** [comment]
This seems like a bug in Appcompat specifically [this method](https://developer.android.com/reference/androidx/appcompat/app/AppCompatDelegate#setDefaultNightMode(int)). Our activity does not get recreated like on other api levels because on the start of MainActivity the activity reports that it has the night mode active.

We can pass back a value when night mode changes that tells the activity to recreate itself or open a bug [here](https://issuetracker.google.com/issues?q=componentid:192731%20status:open) and hope it gets resolved in the next release.

**Comment by Scramjet911** [comment]
So, what should we do? 
Can I try to fix the issue? And is it possible to be fixed by a beginner?

**Comment by macgills** [comment]
It could be, the methodology is pretty simple, startActivityForResult the SettingsActivity, if night mode gets changed return a result to MainActivity so it calls `recreate`. If that sentence made sense to you then you can do it if you wish (and are very welcome to), otherwise I will get to it at some point because it is in our current milestone

**Comment by Scramjet911** [comment]
I tried implementing another condition for Nightmode - auto, but it was crashing. I will try something else for implementing that.

**Comment by kelson42** [comment]
@macgills @Scramjet911 well done!
