### ISSUE TITLE
Re-enable tests for ZimManageActivity

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1755]
**Type of Test**

* [ ] Unit Test
* [x] UI Test

**Current Status of the tests**
On CI this test would sometimes fail.
Clicking on the book would not start the download and not show the `stop_download` button.
Operating theory is that a system dialog was interfering at times, preventing view interaction

**Comment by kelson42** [comment]
@gouri-panda What is the status of this bug? This actual? If "yes", could we reactivate the test?

**Comment by kelson42** [comment]
We will postpone this ticket to 3.8.0 because it implies a larger rewriting of onlinelibraryfragment…. And this part will probably be significantly revamped in 3.8.0 because of OPDS support.

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda , @kelson42  

* Since this ticket is very old and now the ```ZimManageActivity``` is not there in our project. Can you please tell me, what is this activity do in the past.
* According to [this PR](https://github.com/kiwix/kiwix-android/pull/2949/files) i think this activity is doing the downloading ZIM files and language related part (Tell me if i had understand this wrong).
* if i'm correct , then we have already written test cases for ```DownloadTest``` , ```LanguageTest``` , ```InitialDownloadTest```  these test making sure the online content is loaded or not which i think we are testing in ```ZimManageActivityTest```.

**Comment by kelson42** [comment]
@gouri-panda This is a question for you.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Sorry for the late reply! Yes! you are correct. We refactored this class from `ZimManageActivity` to `OnlineLibraryFragment` long back. If you can see `ZimManageActivityTest` we deleted/commented on the whole class. I think that's why we created this ticket to secure these tests.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can you handle it?

**Comment by MohitMaliFtechiz** [comment]
> On CI this test would sometimes fail.
Clicking on the book would not start the download and not show the stop_download button.
Operating theory is that a system dialog was interfering at times, preventing view interaction

@kelson42 , The purpose of this test is to start and stop the download of ZIm files , which we are already doing in ```DownloadTest``` , ```InitialDownloadTest``` , so we can close this ticket. 

Since now ```ZimManageActivityTest``` and ```ZimManageRobot``` classes are unused we should remove these classes.
