### ISSUE TITLE
Document adding detail to values-qq when adding a new string

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1759]
**Is your feature request related to a problem? Please describe.**
When a new translation is added in english it sometimes has an ambiguous context that would need extra explanation.

**Describe the solution you'd like**
When a translation is added in english there should be a corresponding update in `values-qq` and we should document this process, possibly in Contributing.

**Additional context**
https://translatewiki.net/wiki/Translating:Localisation_for_developers#Message_documentation

**Comment by kelson42** [comment]
@macgills OK but:
* How to secure that happen?
* At the time the new string is created, nothing is on translatewiki.net.

I think this could only work, if we would be able somehow to put a comment in the original Android `strings.xml` in English and then that would be automatically uploaded to translatewiki.net. Then we could enforce it at the review time.

**Comment by macgills** [comment]
@kelson42 the `values-qq/strings.xml` is already there, excerpt:
```
<string name="menu_zim_manager">Displayed in application menu</string>
  <string name="menu_help">{{Identical|Help}}</string>
  <string name="menu_home">{{Identical|Home}}</string>
  <string name="menu_settings">{{Identical|Settings}}</string>
  <string name="menu_bookmarks">{{Identical|Bookmark}}</string>
  <string name="menu_random_article">{{Identical|Random article}}</string>
  <string name="menu_full_screen">{{Identical|Full screen}}</string>
  <string name="search_label">{{Identical|Search}}</string>
  <string name="stop_hotspot_button">Clicking on the “Stop” button shuts down the Kiwix server. This server allows to stop sharing the Kiwix local library on the LAN with the HTTP protocol.\n\n&lt;gallery&gt;\nFile:Kiwix-ui.server.start-0.png\nFile:Kiwix-ui.server.start-1.png\n&lt;/gallery&gt;\n{{Identical|Stop}}</string>
```

We should enforce adding explanations to `qq` at review time but also we should document this as officially part of our process

**Comment by kelson42** [comment]
@macgills OK, two questions:
* qq should not be integrated to the android app. How do we secure this?
* How do we secure that, like values-en, values-qq will be uploaded?

**Comment by macgills** [comment]
Having the qq file in source is one of the best ways to secure it gets updated, it is probably worth the 4KB.
I am not sure what you mean by "uploaded", I think this will be managed by translatewiki as part of their upload.
You can view the [discussion](https://github.com/kiwix/kiwix-android/pull/1751#discussion_r374649627) on the PR.

**Comment by macgills** [comment]
@Abijeet can you confirm for me the workflow?
A developer adds a string to `values/strings.xml' file.
A developer adds the context string to `values-qq/strings.xml` file.
When TW syncs with the latest files it imports these 2 files.

**Comment by Abijeet** [comment]
Yes,  this will be imported into Translatewiki and then be displayed to translators when they are translating messages into other languages.

![image](https://user-images.githubusercontent.com/1685517/74134968-7045d080-4c11-11ea-9d9a-486737068bdc.png)

That documentation comes from https://github.com/kiwix/kiwix-android/blob/develop/core/src/main/res/values-qq/strings.xml#L13

Just to add some more background information,

You add a new string name: `abc` to `values/strings.xml`. You will have to similarly add a string with name: `abc` to `values-qq/strings.xml` but the content should be the context (in English) of where and how the original message in `values/strings.xml` is being used. You can also add any other information that you think the translator might need to know in order to translate the string properly. For eg: the word **access** can be used both as a noun or a verb, but other languages might need to use different strings for either of the usage.

**Comment by kelson42** [comment]
@macgills So IMO we need to close that ticket:
* Add a small paragraph about translation in the CONTRIBUTING.md
* Secure that `values-qq` is not part of the app

**Comment by kelson42** [comment]
@MohitMaliDeveloper Please update the `README.md` with a small documentation explaining what is necessary to know for a developer regarding localisation of the software. Proper English and clear English explanation are a must.
