### ISSUE TITLE
Overlap between logo and title on WikiMed AR

### ISSUE THREAD

**Issue by alanajjar** [kiwix/kiwix-android#1760]
Hello, 

On WikiMed AR app the title is too close to the logo (compared with WikiMed EN), so it look like there's an overlap between the logo and the title.

So please if you can make more space between them?

Also, Why there's frame around the logo? can you please hide it? 

![1 (1)](https://user-images.githubusercontent.com/20701355/73971456-96c0ee80-4927-11ea-804d-daaf80f49ab2.png)
![1 (2)](https://user-images.githubusercontent.com/20701355/73971459-988ab200-4927-11ea-99c5-271e20e6f6f4.png)

**Comment by kelson42** [comment]
@alanajjar Thank you for your report. The problem your report concerns the content, not the software itself. The problem is in the ZIM file itself. The wikimed ar zim file is prepared following this recipe: https://farm.openzim.org/recipes/wikipedia_ar_medicine. Like you can see, the homepage specified in this recipe is https://ar.wikipedia.org/wiki/%D9%88%D9%8A%D9%83%D9%8A%D8%A8%D9%8A%D8%AF%D9%8A%D8%A7:%D9%85%D8%B4%D8%B1%D9%88%D8%B9_%D9%88%D9%8A%D9%83%D9%8A_%D8%B7%D8%A8/%D9%85%D8%B1%D8%AC%D8%B9_%D8%A8%D8%AF%D8%A7%D9%8A%D8%A9_%D8%A7%D9%84%D8%AA%D8%B7%D8%A8%D9%8A%D9%82_%D8%A7%D9%84%D8%B7%D8%A8%D9%8A2 on Wikipedia. If you fix that page on Wikipedia, next app update will automatically benefit of your fix.

**Comment by alanajjar** [comment]
Hello @kelson42 I fixed it on Arabic Wikipedia now. But I think we can let it until I'll make other edits to (update) the homepage and other indexes. 

Best

**Comment by kelson42** [comment]
@alanajjar Thank you. We do a new ZIM file of Wikimed AR one time a month... and release new Wikimed AR Android app more rarely. We will just have to wait a few months to make a new full release.
