### ISSUE TITLE
Undo in tab switcher not working 

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1873]
**Describe the bug**
The UNDO option is not clickable when you are in tab switcher mode.

**Expected behavior**
The UNDO option should work as expected.

**Steps to reproduce the behavior:**
1.  Go to tab switcher mode.
2. Close a tab.
3. Try to undo by clicking the UNDO option in snackbar. It is not clickable.

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : Redmi 4
- OS version : Nougat

**Comment by 4shutosh** [comment]
Hey! @sonusourav 
You correctly pointed out the issue.
But I think It won't work as of now as we are using FrameLayouts for the tab switcher and content frame and the snackBar is in the parent View.

**Comment by 4shutosh** [comment]
Hey! @sonusourav 
You've correctly pointed out the issue.

But I think this won't work as of now, because we are using FrameLayouts for content frame,
Also the tabswitcher (`activity_main_tab_switcher`) is a child layout of the `main_activity_content` which in turn is child layout of `activity_main`
And the Snackbar is in parent activity.

To make the Snackbar functional the tabswitcher should be closed at the very moment we close any tab which is not suggested.

So this is a won't fix issue. What are your suggestions @abdulwd @mhutti1 ?

**Comment by abdulwd** [comment]
Not a won't fix. This used to work we just need some workaround to get this working.

**Comment by 4shutosh** [comment]
Yes @abdulwd 
I found the solution 
In `CoreMainActivity.closeTab` wrong View was passed to the `Snackbar.make()`
We need to pass `tabSwitcherRoot` instead of `snackbarRoot`.

**Comment by abdulwd** [comment]
@sonusourav has this been fixed?

**Comment by sonusourav** [comment]
Yeah by #1879
