### ISSUE TITLE
Revamping the UI of recycler view items

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1874]
**Describe the bug**
The design of recycler view items is not according to Material Guidelines. The items do not look uniform due to different length of the text and in some cases, the alignment of the details are also not correct.

**Expected behavior**
The items should be in accordance with Material Guidelines. Also, using a card view would make it look better.

**Screenshots**

![InkedUI-1_LI](https://user-images.githubusercontent.com/34706326/76210379-07f70880-622a-11ea-8b89-598537d6a0b6.jpg)

![UI-2](https://user-images.githubusercontent.com/34706326/76210382-09283580-622a-11ea-9789-e5341352eda0.jpeg)

**Comment by mhutti1** [comment]
We looked at using a cardview but the amount of data we wan't to display means with cards you would only really get 2 times per screen which isn't great. The pictures you point out do seem like issues though.

**Comment by macgills** [comment]
Cards can be any size they just have an elevation really, I amn't too fussed on this point

The WikEm weird layout is due to a missing field in the data so a text field is hidden and constraints jump about.

TEDMED has a stupid long description, we should probably elipsise that after 3 lines, which I think is generous enough.

These 2 should be worked on
