### ISSUE TITLE
Bug in Bookmarks and History list selection

### ISSUE THREAD

**Issue by yash1ts** [kiwix/kiwix-android#1907]
**Describe the bug**
In history and bookmarks screen one can select items for deletion, but there is a button which allows user to view bookmark or history from all books. Even after selecting the items one can switch the view. Which results in confusing list(shown in screen shot).

**Expected behavior**
The view book marks from all books switch should be gone after selecting items, so that user cannot change the list. Another way is that number of selected item should change according to the list items.

**Steps to reproduce the behavior:**
1. Open pages from different books.
2. Open history from the menu items.
3. Select multiple items from different books.
4. Click the switch "View history from all books".
5. See the wrong number of selections.

**Screenshots**
![Screenshot_2020-03-17-14-46-36-539_org kiwix kiwixmobile](https://user-images.githubusercontent.com/45488341/76843113-54ad9580-6861-11ea-8da7-9a77f38e67c1.jpg)
![Screenshot_2020-03-17-14-55-48-004_org kiwix kiwixmobile](https://user-images.githubusercontent.com/45488341/76843132-5aa37680-6861-11ea-9335-ef5bd528b430.jpg)

**Comment by Frans-Lukas** [comment]
I think the button does what it says it does. My opinion is that a button should only do what it says it should do, this button says that it will toggle between _showing_ the history of the opened book and all books. It does not say it will _deselect_ items from the list. 

Because other multi-selection views shown in for example Material Design [1] hide list-altering actions on entering a selection view, I agree with your point that the toggle should not be visible in the selection mode. Are you working on this? Otherwise, do you mind if I work on it? (If we could get a review on this from ex. @macgills @mhutti1 )


[1] [Material Design multi selection](https://material.io/design/interaction/selection.html#item-selection)

**Comment by yash1ts** [comment]
Yes I want to work on it.

**Comment by macgills** [comment]
Yes, most definitely a bug. Please hide the toggle on action mode start.
