### ISSUE TITLE
Block access to external links from within the app

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2023]
Kiwix (and Kiwix-custom) should have an option that disables entirely the possibility to open an external link from within the app (for instance in a Wikipedia infobox).

We implemented something similar on Kiwix-serve that gives users a warning (e.g. "are you sure you want to do this?"), but I would like the option to open external links entirely removed.

**Comment by kelson42** [comment]
@macgills I think this shoudl be a (build-time) option for kiwix-custom-apps. For now no reason to have it in Kiwix itself.

**Comment by macgills** [comment]
Should be pretty easily achievable as we already detect external links, just have to wrap things in a if.

Adding this for custom apps raises some questions, do we want to update the json of all custom apps or do we want this to be an optional field on the json? Is the default behaviour in that case "allow" or "disallow" external links?

**Comment by kelson42** [comment]
@macgills Default is allow. Could we just activate this option is asked in the json? So a default value if not at all in the json?

**Comment by macgills** [comment]
Yeah, if the option is not declared in the json we can simply interpret that as "allow external links"

**Comment by kelson42** [comment]
@Popolechien Looks again to this ticket because of the PR of @ManasviPatidar. The current behaviour for both Kiwix Android and Kiwix Android Custom Apps is:
* Per default external links are not allowed
* If someone click on an external link he gets a confirm dialog asking if he really wants to open the external link.
* There is an option to avoid to get this confirm dialog displayed (so then just open straight).
* This option (confirm dialog of not for external links) can be changed in the settings

@Popolechien I wonder a bit in which use case, this current feature is not satisfying?

**Comment by Popolechien** [comment]
@kelson42 This seems pretty good. I can not think of an issue where this is not satisfying.
