### ISSUE TITLE
Automatic split for downloader

### ISSUE THREAD

**Issue by mifritscher** [kiwix/kiwix-android#2085]
As kiwix can cope with split zim files, it would be very nice to add the functionality to split zim files automatically while downloading. I've a smartphone (android 9) which accepts only a FAT32 filesystem on the sd-card, and so I can't use a offline wikipedia for instance.

**Comment by kelson42** [comment]
Recent versions of Kiwix can not deal with randomly splitted ZIM files anymore. Maybe at some point we will reintroduce a smart splitting, but for now please don't split your ZIM files anymore. See https://github.com/kiwix/kiwix-tools/issues/287

**Comment by ITCMD** [comment]
Bumping this, sadly Kiwix is incompatible with most android devices since it doesn't support split ZIM files anymore and 4GB is the file size limit for SD cards with android (as they do not support ext3,4, exfat, or ntfs)

**Comment by kelson42** [comment]
Most of the the latest smartphones and tablets support exFAT file system.
Source: https://frameboxxindore.com/android/best-answer-do-android-phones-support-exfat.html

**Comment by ITCMD** [comment]
This is true, but my point still stands that most do not, especially since I wouldnt want to spend money on a flagship device for a wikipedia box.

I get it though, gotta pick and choose where volunteer time goes. The alternative I've discovered is hosting it on a pi-zero-w and accessing that via an old tablet.

**Comment by ge0rg** [comment]
Another case is people using (old) eBook readers like devices from Kobo which only support FAT32. I'm currently in a weird situation without a solution:
- I can't reformat the internal microSD to exFAT to support non-split archives
- I can't use any recent version of `kiwix-tools` due to removed split file support
- I can't use recent ZIM files because old versions of kiwix-tools don't understand the current compression format:

version 1.0 reports:
```
Invalid /mnt/onboard/Wikipedia-DE-Medizin/wikipedia_de_medicine_maxi_2022-09.zim : Invalid compression flag
```

version 2.1.0 crashes:
```
terminate called after throwing an instance of 'zim::ZimFileFormatError'
  what():  Invalid compression flag
Aborted
```
(I double-checked that the file has been downloaded correctly)
