### ISSUE TITLE
Speed up Automated Tests by sharing apks 

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2096]
**Is your feature request related to a problem? Please describe.**
Currently each automated test has to build the apk, we could see a significant speed boost if we uploaded the apk in a first step and only had to download it in all the others

**Describe the solution you'd like**
Use Upload Artifact and Download Artifact Actions to share apks across our build

**Comment by kelson42** [comment]
@gouri-panda Still a valid proposal to your opinion?

**Comment by gouri-panda** [comment]
@kelson42 Yes, absolutely!

**Comment by kelson42** [comment]
@gouri-panda how many times is ot build for one full CI build? How many would we get if we implent this ticket?

**Comment by gouri-panda** [comment]
>@gouri-panda how many times is ot build for one full CI build?

@kelson42 Our current system builds one APK per automated test.  How many tests are there or will it builds that many.
> How many would we get if we implent this ticket?

We will first build one and later use it in others.

**Comment by gouri-panda** [comment]
I don't know the exact numbers but maybe 40 or 50+.

**Comment by kelson42** [comment]
@MohitMaliFtechiz I think it is really time to work on this!

**Comment by MohitMaliFtechiz** [comment]
@kelson42, @gouri-panda I have researched about it and we can do it via passing apk path in `testInstrumentationRunnerArguments`. But Along with this approach, we can speed up our test cases by making some test changes.

e.g.

1. We are using this code in all of our test cases, which is 1 second here, but in a few test cases we are waiting for 10 seconds before performing any further action to ensure that the view will show before checking it. If anything is rendering on the screen, `uiObject` will not be able to find the object during the rendering process and It will always wait for the given time even if the view is visible. We can use the `uiDevice.waitForIdle()` method which ensures that if the view is visible on the screen then it will perform the further action otherwise it will wait for any animation to finish.

https://github.com/kiwix/kiwix-android/blob/08face55e144dfba8255e49ac4756996b18933a7/app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteRobot.kt#L111

2. We are always deleting the ZIM files in our `DownloadTest` and `InitialDownloadTest` even when there is already `No files here` text showing which takes a few seconds. So we can improve these test cases to speed up the Automated test.

@kelson42, @gouri-panda What do you think?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have implemented the sharing APK functionality in https://github.com/kiwix/kiwix-android/pull/3758 via `testInstrumentationRunnerArguments.apk` but it makes the test cases even more unstable e.g. sometimes it does not receive any test on the first run, and sometimes it does not receive in the second run(if the first test case is failed) [see workflow](https://github.com/kiwix/kiwix-android/actions/runs/8264283838/job/22607565607?pr=3747#step:6:27370 ) for more details. However, I have analyzed the behavior of test cases locally and on the CI also, we are using `jacocoInstrumentationTestReport` for running test cases and generating the report which depends on the `createDebugCoverageReport`, and it internally uses the same APK for running all the test cases since between running the test cases there is no lack of time (one test finished and the second one starts, which indicates the test are running on the same APK. Because generating APK takes time.). However, if we run test cases one by one on the local machine it every time builds the APK for running that test case because it takes the latest changes from the code and then runs the test cases. However in the ` createDebugCoverageReport` we run all test cases together so it only generates the APK for the first test case to take the latest changes of the code and use it for all the test cases.

Might be that's why this argument is not listed on the [official documentation](https://developer.android.com/topic/performance/benchmarking/macrobenchmark-instrumentation-args.) 


However, we have stabilized the CI in https://github.com/kiwix/kiwix-android/pull/3758 by improving our test cases and CI which makes the CI faster. By doing changes in https://github.com/kiwix/kiwix-android/pull/3758 now our instrumentation test cases are very stable on API levels 24 and 30 since these APIs use the `default system` image only sometimes we might face failure on 33 since it uses the `google_apis` system image which is heavy due to including the google services which makes sometimes cause the emulator lag.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thx for the explanation. Closing then.
