### ISSUE TITLE
Revisit "writeLogToFile()" functionality

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2143]
**Is your feature request related to a problem? Please describe.**
Currently CoreApp has code for writing a log file and I have found the usefulness of this to be low.

**Describe the solution you'd like**
a) Extract the functionality to a separate class
b) Rethinking what commands we run and when we run them

**Describe alternatives you've considered**
Removing the functionality

**Comment by s-ayush2903** [comment]
I would like to work on this issue

**Comment by s-ayush2903** [comment]
I think instead of using java's `Runtime.getRuntime().exec("....")` calls we should make use of _BufferedWriter_ for better performance.

* One more thing, since we've been extensively using the logging throughout the codebase, then it can be better if we make use of some logging library like _Timber_.

**Comment by s-ayush2903** [comment]
I've planned of extracting out the current `writeLogFile()` function to the FileUtils.kt and modifying the logic of the same following the approach mentioned above.

@macgills 
Please put forward any views and suggestions for further improvement in the approach/functionality described above

**Comment by macgills** [comment]
@s-ayush2903 excellent! You are assigned.
