### ISSUE TITLE
Library slow to load zim files

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2170]
The commenter gave a disposable address, so if the report can not be actioned feel free to close:

"Hi. I am reporting a problem here because I do not want to give my email address to Microsoft (owner of Github).
I downloaded some zim files that were made in the May and June of 2020. Examples are wiktionary_en_all_maxi_2020-06.zim and wikipedia_en_physics_maxi_2020-05.zim.
These files were very very slow to be detected in the Kiwix app library and to be loaded by the Kiwix Android app.
These same zim files from 1 to 5 month earlier did not have this problem.
The problem occurs with Kiwix v3.3.1, v3.2.1, v3.1.3 and v2.5.3.
It occurs on my Asus phone with Android 8.1 and on my Samsing 2018 tablet with Android 9.
It also occurs on my Windows 7 desktop when using the Kiwix v2.7 extension with the Chromium v83.0.4103.116 browser.
But there is no problem with Firefox v77.01 with the Kiwix v2.7 extension. The zim files load fast with Firefox.
Because my phone and tablet use Chrome v83.04103.106 as the Android System Webview and Desktop Chromium v83.0.4103.116 has the same problem, I think that Chrome is the problem, in combination with some change in the zim file format starting in May 2020.
I hope this info is helpful to you."

**Comment by Popolechien** [comment]
Could it be related to what @Jaifroid described in [#628](../../kiwix-js/issues/628#issuecomment-650593866)?

**Comment by Jaifroid** [comment]
To summarize the issue I identified: the [libZim code here](https://github.com/openzim/libzim/blob/master/src/fileimpl.cpp#L130) assumes that the URL Pointer List comes one byte after the MIME type table. But recent ZIM files in May and June appear to have relocated the URL Pointer List, in one case at least to the end of the file. This means that the linked function in libZim tries to read a huge slice to get the MIME type table, caused by the line `size = zsize_t(header.getUrlPtrPos() - header.getMimeListPos());`. It may fail on some readers, depending on the amount of memory and size of ZIM, or just may take a very long time to load the archive.

A simple patch is to limit `size` to 512 or 1024 bytes if it is greater than this. There is no MIME type table I have found that is greater than 141 bytes. It is of course a bit inelegant to hard-code a value...

**Comment by macgills** [comment]
So I am not sure if this person is saying:
1) v3.3.1 has problems loading 2020 files but loads 2019* files just fine
or
2) The version of kiwix I was on prior to getting these 2020 files was fine.

There is also the size of these files that complicates matters because this is undoubtedly on an sd card which goes unmentioned, if this user can send a diagnostic report identifying themselves in some way I can try and figure out why this is not working for them. If they are unwilling to do that then I would see if they can double check their sd card is exfat formatted

**Comment by Popolechien** [comment]
@macgills My understanding is (1) - problem loading 2020 files.

As I mentioned they gave an address we can't reply to so feel free to close the ticket.

**Comment by Jaifroid** [comment]
@macgills OP is saying that May and June 2020 ZIMs are slow to load, and previous ZIMs were working fine, on all the versions of Kiwix Android that they tested.

**Comment by macgills** [comment]
Well my thoughts are we close this ticket as there is already a ticket open to improve the performance of kiwixlib and right as I see it there is nothing to change android side maybe?

**Comment by Popolechien** [comment]
Sounds good to me.
