### ISSUE TITLE
Problem with finding external SD card with Huawei P8 Lit

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#222]
User report external SD card is not visible. Mount point is /storage/4689-07F1
Have tested with Bitbar, but unable to reproduce the problem.

More details here https://play.google.com/apps/publish/?account=9116215767541857492#ReviewDetailsPlace:p=org.kiwix.kiwixmobile&reviewid=gp:AOqpTOEw-rPXWEThCIoWjnrS6S9o0heRNXaR2Yqf3_jTaQ61HVIODewMQmzO05KI_ayc_SrBqMePI5aU4eDabgM

**Comment by mhutti1** [comment]
This appears to be randomly generated. As you are unable to reproduce there's not much point looking into this. 2.3 will allow user defined sd paths that should resolve this users issue.

**Comment by kelson42** [comment]
@mhutti1 

OK, but the pattern 4numbers-4numbers is stable and pretty common as far as I believe. At least it is not the first time I see this kind of pattern. Would that be possible to put a path pattern recognition in the soft?

I'm no convinced at all with the ability given to the users to put theire own path... This is far too complicated for 95% of users. Things should work out of the box. We can give a try with 2.3, but pretty sure this is against "all guidelines of usability".

**Comment by mhutti1** [comment]
It might be possible to do that but would not be easy due to the way android mounts stuff. And would likely result in duplicate storage devices of others. One manufacturer might decide /storage should be the storage directory others that subdirectories of storage should be. How do we distinguish? A pattern is not a great solution

**Comment by kelson42** [comment]
@mhutti1 We need to discuss this again. The work you have done so fat works pretty well. We need to complete it to achieve near 100% device overage.

**Comment by mhutti1** [comment]
Well with no way to reproduce there's nothing I can do at the moment.

On 5 Aug 2017 6:45 am, "Kelson" <notifications@github.com> wrote:

@mhutti1 <https://github.com/mhutti1> We need to discuss this again. The
work you have done so fat works pretty well. We need to complete it to
achieve near 100% device overage.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kiwix/kiwix-android/issues/222#issuecomment-320414448>,
or mute the thread

**Comment by kelson42** [comment]
We can now add a custom path... and like @mhutti1 said, there is nothing more we can do. I close the ticket.
