### ISSUE TITLE
bug: Crashes when clicked for sending Diagnostic Report 

### ISSUE THREAD

**Issue by s-ayush2903** [kiwix/kiwix-android#2412]
**Describe the bug**
When present on the help screen and click for _Send Diagnostic Report_, the app crashes (yes this is a regression)

**Expected behavior**
It should not crash and the report should be sent successfully

**Steps to reproduce the behavior:**
*  Navigate to Help Screen (using navDrawer)
* Now click on _Send Diagnostic Report_
*  (Witness the crash)

**Screenshots**
NA

**Environment**
- Version of Kiwix Android : `kiwix/develop`
- Device : Samsung Galaxy M31
- OS version : 10

**Logs**
Not needed

One thing to add, this is not introduced as a result of latest nav. merge in the develop, it was present on develop earlier, I'm not sure where this regression crept in, last time when I added the in-file logging feature, it was working well

**Comment by macgills** [comment]
This is not an issue with the app, the issue was that you had build files for a an older version of the app that complained when you tried to build the latest version. If you posted the logs they probably would have been something about butterknife. A clean build resolves this

**Comment by s-ayush2903** [comment]
Okay, fine then. But how should I know when to run a clean build?

**Comment by macgills** [comment]
After reading the crash method it should have become clear that this was the issue. Granted you need to know a bit about butterknife but the problem was butterknife couldn't bind a view in Diagnostic/ErrorActivity and butterknife isn't used in either of those activities, bit of a dilemma.

We are closer and closer to getting rid of Butterknife and it is the largest contributor of these problems. In general run `clean` a lot. whenever I switch branches or checkout a fork I'll start off with a `gradlew clean uA` before installing to make sure I am not conflicting in any way
