### ISSUE TITLE
Convert CoreReaderFragment to Kotlin

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#2458]
**Is your feature request related to a problem? Please describe.**
Convert CoreReaderFragment to Kotlin.
Splits from #1826 

**Describe the solution you'd like**

This will also help us to get rid of ButterKnife

**Describe alternatives you've considered**

**Additional context**

**Comment by harshsbais** [comment]
@abdulwd I want to work on this.
Can you please assign this to me?

**Comment by yyprince334** [comment]
Hi, I want to contribute  on it .

**Comment by gouri-panda** [comment]
Hi @yyprince334! Thank you for your interest but  I'm afraid it's not possible since this is our core file at kiwix-android, it's best if someone already familiar with the codebase should do the job. You can start contributing by going through [here](https://github.com/kiwix/kiwix-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) . Thank you for understanding!

**Comment by Rishavgupta12345** [comment]
hi can i work on this issue

**Comment by kelson42** [comment]
@Rishavgupta12345 nice, please make a PR when you are so far.

**Comment by kelson42** [comment]
@gouri-panda @MohitMaliFtechiz What is the status on this? Already done?

**Comment by gouri-panda** [comment]
Yes @kelson42
