### ISSUE TITLE
can't download or open wikipedia

### ISSUE THREAD

**Issue by ilyapashuk** [kiwix/kiwix-android#2480]
**Describe the bug**
if I try download full wikipedia, I'm getting unabletodownload mark, but I have enough space. If I try to download it from pc and open in FileManager, app hangs.

android 9, samsung galaxy a 30, last kiwix from android, last wikipedia.
with text only version all works fine.

**Comment by s-ayush2903** [comment]
@ilyapashuk Thanks for reporting. If you give us the recording in which you can depict the problem being encountered by you, it'll help us diagnose it smoothly and then propose a valid fix.

**Comment by s-ayush2903** [comment]
@ilyapashuk Thanks for reporting. If you give us the video recording in which you can depict the problem being encountered by you, it'll help us diagnose it smoothly and then propose a valid fix.

**Comment by macgills** [comment]
@ilyapashuk 
> I'm getting unabletodownload mark

Is the list item greyed out? You can long click these cells and then a message will show telling you why it is greyed out. Potentially this is just because we are trying to figure out the filesystem and this unfortunately can take some time

>If I try to download it from pc and open in FileManager

If you have transferred the file from your pc via sdcard I would recommend you launch Kiwix and then the scanning feature of the app should find a file anywhere on disk. Unless IO is being blocked by our filesystem detection.

It may also be beneficial to send a diagnostic report from the help section of the app. This may allow us to give more detailed help. Please include some identifying information so I can link the report back to this issue

**Comment by ilyapashuk** [comment]
I know that my fs can create such files, so how I can forceably make it to work out from this fact.

**Comment by macgills** [comment]
If you leave the app open on the download section for several minutes it should figure this out (if you have your preferred storage set to external) and once it figures it out once it will then cache the result in a file on your external drive to avoid repeating this lengthy check. It would also be possible to trick the detection system by manually adding this file but it is not a path I would recommend

**Comment by ilyapashuk** [comment]
now I downloaded one small package from the app and than reset data of the app in the settings.
and app found nothing, but content file was not deleted, so your scanning system is not working.
if I try to open zim in filemanager, I get error about that the app for such file type not found, or app hangs forever.

please add menu item to open the saf window and find file from it in app directly.

**Comment by macgills** [comment]
Have you tried uninstalling the app and on a fresh install trying to download a relatively small file to your internal storage through the app? I would like to try and verify the basic functionality is operational in your environment.

I would avoid trying to open a zim through the file explorer for the time being.
What I alluded to previously was if your sd card is preoccupied with us trying to figure out if it is capable of handling 4GB files then it can't also be traversed to find zim files. If you send a diagnostic report with appropriate text identifying yourself I can help diagnose further but I imagine that your OS is reporting that it is `vfat` or `sdfat` instead of the correct `exfat/ext4` so it could be that a reformat could solve your issues if that is an option.

Supporting SAF is unfortunately quite some time away but will hopefully be enabled by current projects underway

**Comment by ilyapashuk** [comment]
uninstalling, using internal storage, opening small zim's in explorer, I tried all, and your scanner is not working in all cases, app detects only zim's which downloaded, but ignores them after reset.

4gb detection works fine.

**Comment by macgills** [comment]
`reset` could be deleting our files as they are stored internal to the app? Definitely wiping the database that backs the library list, when downloading from our app a successful download inserts into that database. I wonder if the file scanner is throwing an exception? Have you tried downloading zim files(via browser, torrent, etc) to your internal storage, without an sd card inserted? It would be very surprising if File Search failed in this scenario.

We have a similar issue here #2405 which is similar to the feature you request.

If you send me a diagnostic report it would also have logs and I may be able to say something definitive.

**Comment by ilyapashuk** [comment]
reset don't delete zim files
without sd it detects files on internal storage, but with sd inserted it detects nothing but opens already detected files.
sd is formatted by system's tools and contains nothin but this wikipedia.

I think it may be because android_secure file or folder exists, may be app tries to access it.
please rewrite scanning service so that it will ignore uncritical errors like inability to access some dirs.
and please add feature to add zim's to db manually.

**Comment by macgills** [comment]
Have you sent me a diagnostic report? Until I get logs then this is mostly speculation and I would like to arrive at concrete solutions from reliable data

**Comment by ilyapashuk** [comment]
How I can get such data? How I can make this app to generate logs?

**Comment by macgills** [comment]
>It may also be beneficial to send a diagnostic report from the help section of the app. This may allow us to give more detailed help. Please include some identifying information so I can link the report back to this issue

On Library/Reader/Download click on the drawer icon in the top left to open the nav drawer, help is in there

![image](https://user-images.githubusercontent.com/3358282/99509647-f0a61880-297d-11eb-90e1-75006653d060.png)

and inside Help is "Send Diagnostic report"

**Comment by ilyapashuk** [comment]
[Hi.txt](https://github.com/kiwix/kiwix-android/files/5560080/Hi.txt)

**Comment by ilyapashuk** [comment]
When i'm opening something from internal storage without sdcard, all works fyne, but when I mount sdcard, nothing works.
formatting don't help.

**Comment by macgills** [comment]
You are not using our most recent version, could you upgrade to 3.4.1 and confirm the issue still persists?
```
MountInfo(device=/dev/block/vold/public:179,33, mountPoint=/mnt/media_rw/5266-EB4C, fileSystem=sdfat)
```
your secondary storage is reporting as `sdfat`. Judging by the `magisk` mount points you are running a rooted device? What OS are you running?

**Comment by ilyapashuk** [comment]
3.3.1 is the last version that is available on your fdroid.

I'm sorry, but I don't using gapps.

**Comment by macgills** [comment]
https://github.com/kiwix/kiwix-android/releases you can get the latest version directly off github, I'd try the arm64-v8a version first. I'll work on updating fdroid

**Comment by ilyapashuk** [comment]
after update it started work instantly.

I think it is more simple to track releases on both markets then work with such issues.
