### ISSUE TITLE
Download won't start in search mode

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2544]
Happened on both Samsung and Huawei phones with Android 9. Looked for "Core" content in the library, found them, but when clicking no download starts. I've tried with several other files and it looks like TED videos are a little faster to get started,  but in some cases download starts after 20-30 seconds or simply do not start at all.

**Comment by Popolechien** [comment]
Kiwix 3.4.2 build 6230402

**Comment by kelson42** [comment]
I strongly suspect a platform problem as download.kiwix.org seems unstable these last days.

**Comment by kelson42** [comment]
This morning it works, I believe this is a side effect of https://github.com/kiwix/maintenance/issues/162. The MySQL being slow the lot of API requests send tend to occupy a lot of HTTP reverse proxy slot and then the reverse proxy does not answer anymore properly. To be confirmed.

**Comment by macgills** [comment]
I too have noticed download.kiwix.org being unreliable as of late, this lack of feedback while this is happening is a bit poor though. The problem is we download the xml to retrieve the appropriate mirror to download a zim from and we don't express the xml retrieval as a UI state, this could be added
