### ISSUE TITLE
Kiwix fails to restore state of previously opened article on new launches

### ISSUE THREAD

**Issue by daniels234** [kiwix/kiwix-android#2567]
After Kiwix is launched, it opens Library instead of Reader, since this version (3.4.1 F-Droid, LineageOS 17.1)

*Edit: It should open last read article, like in versions before.

**Comment by s-ayush2903** [comment]
@daniels234 The aim of kiwix is to provide users a robust set of library to download and read books, and as per our [release/3.4.1](https://github.com/kiwix/kiwix-android/releases/tag/3.4.1)(and further ones) by the implementation of modern android dev techniques and navigation we're able to achieve it. Being a user it always doesn't seem cool to open the exact same book each time application is launched, as they might be thinking of reading a new book(before opening the application) and as soon as application is launched the user sees previously opened book instead of their own existing library where they can choose books from, so this could be a negative point if implement the request made in this ticket. Also, from perspective of a users like you the request created in this issue would be a good option but if we switch to the previous flow then it won't add much. See these both features have positive and negative points but I'll prefer going with the aim of kiwix. So it can prove to be a regression in the module, not technically but statistically

**Comment by daniels234** [comment]
I was not aware that Kiwix is usually used the way you describe it (like switching through different books constantly), if there's insight that it is used that way mainly, it would indeed make sense to change this established behaviour of Kiwix. 

Rather i understood Kiwix (am a user for years) as a reader for a small but content-rich range of books (which remain open and used over several sessions), and for that it is to my apprehension more user friendly and intiutive to start where you ended last time. When you read a book you won't switch books daily, but i maybe wrong. 

At least having an option in settings like "remember last (paragraph) read" would be convenient or in fact progressive, could imagine a lot of people use Kiwix the way i do.

Changing something (in addition reliable) should not be an end in itself, hope this is not the case here. This way "new" would become "regressive" (maybe in this case not as massive as it sounds, but regressive).

**Comment by mhutti1** [comment]
I definitely understand @daniels234. Perhaps an "Startup with last ZIM" setting might resolve this?

**Comment by kelson42** [comment]
I wanted to react briefly to this ticket as well with a few points. Disclaimer: I don't have checked the feature with previous and current version of Kiwix.

Remarks:
* Feedback from user is legit. Users are interested in the content, the library and Kiwix UI are only means to access it. We should not force users to go through the library only if absolutly necessary.
* Many users use Kiwix with only ine ZIM file.
* I'm disappointed that we have a kind of UX regression here (without me being noticed). I probably just have overseen the discussion, therefore would someone be able to point me the ticket/PR where this has been decided please?
* The problem here is similar to the one a Web browser has... and I believe it should be fixed in a similar manner, ie. with a new settings (a proposal should be made about which kind of seetings exactly we should do).

**Comment by s-ayush2903** [comment]
@kelson42 Is the issue title fine or needs to be changed?

**Comment by s-ayush2903** [comment]
@kelson42 Is the issue title fine or needs to be changed? I believe we can fix the "Start with Reader" problem in a new ticket, the trickier part was to restore the previous position of the article in new launches, with the merge of the linked PR we'll be good to go with it.  And for "Start with Reader" I've planned of creating a new ticket and then writing a fix for it, I think the fix for it should be easy enough to write.
I'm waiting for a response from your end, on the green check I'll create one and will work on it.
