### ISSUE TITLE
Upload screenshots for F-Droid description page

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [kiwix/kiwix-android#2569]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by QMR-Anik** [comment]
can I work on this?

**Comment by mondlicht-und-sterne** [comment]
@QMR-Anik Who are you talking about now?

**Comment by QMR-Anik** [comment]
I am new to Open Source. I want to Contribute.

**Comment by mondlicht-und-sterne** [comment]
well, that was just information that screenshots can be added to the app via fastlane, then the view on fdroid looks nicer.

**Comment by QMR-Anik** [comment]
Opps... Sorry I was looking for "good first issue" as a new comer...

**Comment by AayushSolanki** [comment]
is the issue active?

**Comment by kelson42** [comment]
@gouri-panda I guess this has been fixed by #2869 ?

**Comment by IzzySoft** [comment]
I didn't check. Takes another release to be running through F-Droid's build cycle successfully to see. And there was no new release yet after merging that PR, if I'm not mistaken.

**Comment by kelson42** [comment]
Lets check after the next release then.

**Comment by kelson42** [comment]
@IzzySoft To me it looks the online screenshots are the same which are provided in our fastlane directory. Looks good for you too?

**Comment by IzzySoft** [comment]
I've just manually triggered a fastlane update on my end to pull the latest changes – and yes, looks fine! F-Droid already had the screenshots, mine will have them in a few hours (with the next sync). Also, `full_description.txt` renders fine, looking a bit better in my repo (which supports full Markdown) than with F-Droid even :see_no_evil:

Remaining question: I just wondered why Kiwix was no longer updated in my repo. Turns out you no longer provide APKs at your releases. Do you want me to remove the app from my repo then – or would you attach the APKs again (starting with the currently last release is fine, no need for the other missed ones)?

**Comment by kelson42** [comment]
Thx for the verification.

> I just wondered why Kiwix was no longer updated in my repo.

I think you have been fooled by our chaos (we have released many time the same `3.6.0`). Does it looks better now for you https://github.com/kiwix/kiwix-android/releases ?

**Comment by kelson42** [comment]
Closing the ticket, @IzzySoft Please keep letting me know if you have any additional problem with our publishing process or with Kiwix for Android itself. Thx again for all your help.

**Comment by IzzySoft** [comment]
Thanks @kelson42 – yes, now the APK is pulled from the latest release. So I take it you want me to keep it in my repo, despite of it being present and up-to-date at F-Droid.org again? Current information on that is "it's here because it's disabled at F-Droid", which no longer meets reality. I gladly keep it if you want me to (and update that information accordingly) – or, if you prefer, remove it as it's available at F-Droid.org again. Just let me know which one it should be.

**Comment by kelson42** [comment]
@IzzySoft I really don't have any strong opinion on this honestly. I personaly mostly use F-Droid. But it's true that if your repository is conceived to be complementory to F-Droid, this probably does not makes much sense anymore.

**Comment by IzzySoft** [comment]
I'd agree. As the past has shown, we can easily re-establish it in my repo if needed. Though given it's size it doesn't hurt me keeping it either, so I'll leave the decision to you. For some guidance, the pros and cons [are decribed here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ). Just let me know then whether to keep or to kick :wink:
