### ISSUE TITLE
[Bug]Text input lag-Article search

### ISSUE THREAD

**Issue by Mitia99** [kiwix/kiwix-android#2657]
**Describe the bug**
Text input is very laggy.

**Expected behavior**
Fluid text input
**Steps to reproduce the behavior:**
1.Open library
2. Input any text for search

**Environment**
- Version of Kiwix Android : 3.4.4
- Device : Huawei P30 ELE-L09
- OS version : EMUI 11-Android 10
- Keyboard : Gboard latest version

**Comment by kelson42** [comment]
@Mitia99 you confirm you talk about the library search and not the article search?

**Comment by Mitia99** [comment]
@kelson42 It's about article search in any library

**Comment by kelson42** [comment]
@Mitia99 The library is the place where you can download and list your books. So I guess you mean article search in any book.

**Comment by kelson42** [comment]
Regarding this, I can confirm that a regression has been introduced here. My experience is that is works on recent devices but not at all on my old galaxy tab. Many users have conplained about similar symptoms on latest custom aps wikimed de and wikimed fr... and I had to stop all the updates because of that. @gouri-panda and @s-ayush2903 I strongly suspect that one of the patch you have worked on around this since las december has introduced the problem.

**Comment by Mitia99** [comment]
@kelson42 Yes,You got it.The issue is that some letters are missing when I input.

E.g:I search "hyponatrémie".Only hpontrmie is displayed.

It is occuring when I quickly input

**Comment by gouri-panda** [comment]
@kelson42 I'll dig into that.

**Comment by Mitia99** [comment]
@gouri-panda Thanks for investigating.

Here is a video explaining the issue(you can slow it down to see what I input).

https://drive.google.com/file/d/1JswEG2xLyn4Tje7SkJOGyy9y0ws39rrW/view?usp=drivesdk

I hope that you could fix it asap cause due to this,kiwix is kinda unusable for me.

**Comment by mhutti1** [comment]
Hmm, it looks like my employer remotely disabled usb debugging on my phone... Will need to dig up an older device.

**Comment by danielzgtg** [comment]
This was a regression of #1818 which I filed, and was fixed a year prior. I encountered this bug again too, but in the meantime I just downgraded and used a previous version until now. Today I was thought of cloning the repo and finally looking into this, and was happy that it is fixed.

Since input methods got broken twice, should there be an automated test case for this?
