### ISSUE TITLE
Latest PR's coverage report is failing

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2667]
**Describe the bug**
Latest PR's both coverage reports are failing due to socket time out exception. 
```
> Could not resolve all artifacts for configuration ':app:debugAndroidTestCompileClasspath'.
   > Could not download junit-platform-commons-1.7.0.jar (org.junit.platform:junit-platform-commons:1.7.0)
      > Could not get resource 'https://jcenter.bintray.com/org/junit/platform/junit-platform-commons/1.7.0/junit-platform-commons-1.7.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/junit/platform/junit-platform-commons/1.7.0/junit-platform-commons-1.7.0.jar'.
            > Connection reset

```
See [error](https://github.com/kiwix/kiwix-android/pull/2660/checks?check_run_id=2863393221)
Maybe it's Bintray or timeouts while downloading Maven dependencies due to network timeouts
**Tried Before**
Added `mavenCentral()` in project build.gradle. In that case, it passes one coverage report, So maybe it's a time-out error only.
**Expected behavior**
Should Pass CI.

**Comment by gouri-panda** [comment]
it seems Maven Central bans and holds the request if there are too many requests. Maybe proxy mirroring maven central will solve the problem.

**Comment by kelson42** [comment]
The URLs in your bug report are not at Maven Central. What goes wrong exactly?

**Comment by s-ayush2903** [comment]
Dear @kelson42 : )
As we know that bintray has sunset, and we still have dependency on same i.e., `jcenter()`(see [here](https://github.com/kiwix/kiwix-android/blob/19a70529f481909ff78ab7c879d9c85ceaeed304/build.gradle.kts#L4) & [here](https://github.com/kiwix/kiwix-android/blob/19a70529f481909ff78ab7c879d9c85ceaeed304/build.gradle.kts#L22)), due to which in our CI processes, the runners tend to fetch dependencies from bintray, which no longer is active and therefore are unable to `GET` them. We need to remove our dependency on bintray and change it solely to `mavenCentral()` in order to get the CI build green again.

Let me know if I could be of any help : )
