### ISSUE TITLE
Images not appearing after using the random article function

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-android#2672]
Kiwix Version: 3.4.4
ZIM: 2021-03 English Wikipedia

After using the random article function, images do not come forth as they should (this is not always the case). In order for them to pop up, you need to touch the screen, as you can see in the video below (note the white circle at the 2-second mark indicating that I touched the screen):

https://user-images.githubusercontent.com/71934042/124366914-86fc2580-dc53-11eb-9c98-10624c5e3c47.mp4

**Comment by kelson42** [comment]
@Inbefortus Not sure what to say here because we can not reproduce it. Behaviour is not appropriate but there is nothing we can do IMO. Best explanation is that your behaviour is related to lazy image loading, see https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading. Probably here there is something wrong around that, but this is not the responsability of Kiwix. Maybe a bug in the rendering library or with the device.
