### ISSUE TITLE
500 Error happens in Browser

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2683]
**Describe the bug**
Sometimes if I Open Kiwix's hotspot server through kiwix's android app to see my zim files in my browser.Sometimes I got 500 & 404 (internal server error and page not found)

**Expected behavior**
Not to see that error.

**Steps to reproduce the behavior:**
It happens 6 out of 10 times.

1. Open kiwix android app
2. Go to wifi-hotspot
3. Start the server
4. Look into the browser
5. Open some zim files 
6. Go backward and forward
7. Repeat a couple of times

**Environment**
- Version of Kiwix Android: 3.4.4
- Device: Realme 
- OS version: 11
- Browser: Brave & Chrome

**Comment by kelson42** [comment]
If something goes wrong here, this is highly probably something wrong in the libkiwix.I would recommend to keep that ticket open until we have finish to introduce new JNI based on libkiwix10. Then if the bug is still there, look at it.

**Comment by s-ayush2903** [comment]
Hi, I am aware of it. If you closely inspect the entire behavior of the application, then it turns out, the server shows `Internal Server Error`, _only_ after the application has been terminated(or better to say killed) by the android OS. We might consider optimizing resources usage in order to prevent the application from being killed by the OS(when we move back and forth between browser and application real quick and many times)

**Comment by kelson42** [comment]
Then this is a pure Android problem where we need to handle different,y the hibernation strategy in case the server mode is activated, right?

**Comment by s-ayush2903** [comment]
Yep exactly! These days I'm busy with wrapping my summer of code project and college too has reopened, leaving a very less amount of time in my hands. I do not know when I'll get around this issue, but hopefully it should not be _that_ tricky to fix.

**Comment by MohitMaliFtechiz** [comment]
This issue is automatically fixed by #3217.
