### ISSUE TITLE
PDF files accessed from Kiwix fail to open in external PDF reader apps

### ISSUE THREAD

**Issue by cjohnsto-nz** [kiwix/kiwix-android#2709]
**Describe the bug**

Opening a PDF from a ZIM in Kiwix opens the dialog to select an application. No matter what application is selected, the application will fail to open the PDF.
**Expected behavior**

PDF files included in ZIMs should be able to be either saved to the device and have a URI provided through a Content Provider, or streamed to the application to prevent duplicate use of storage. At the very least, PDFs accessed through Kiwix should be accessible to the selected external application.
**Steps to reproduce the behavior:**
1. 

1. Access a ZIM that links to an included PDF file.
2. Tap the link to the PDF. Select any PDF application from the dialog.
3. PDF application will open, and fail to load the selected PDF.
**Screenshots**

**Environment**
- Version of Kiwix Android : 
- Device : 
- OS version : 

**Logs**

**Comment by cjohnsto-nz** [comment]
Kelson, can I ask, do you have an idea of what the issue is here, and what a solution might be? I have some time on my hands that I could spend looking into this. Thought I'd check with you first to see if there is prior knowledge.

**Comment by kelson42** [comment]
Not really. I guess we call the wrong Qt widget, or with the wrong option. Maybe @juuz0 has a clue?

**Comment by juuz0** [comment]
@kelson42 Wrong repo, I guess :D

**Comment by kelson42** [comment]
@juuz0 oh yes sorry... there is a similar ticket on kiwix-desktop... and i got confused.

**Comment by uellenberg** [comment]
I am unable to view any of the books under WikiBooks. Instead of opening, I receive the message "Could not find an installed application for this type of file." Is this maybe related? It also seems similar to #2684.

**Comment by 4shutosh** [comment]
Is the bug still valid?
I would like to work on this issue. 
@gouri-panda any idea where the problem lies, I'll start looking in that direction then?

One of the zim files mentioned is "books under WikiBooks". @cjohnsto-nz Can you please help me with a specific zim file name for testing?

**Comment by cjohnsto-nz** [comment]
The bug is still valid.

I'll prepare a Zim today.

Basically, any PDF referenced with the file tag brings up the app selection dialog, opens the app, but fails to load in the app
________________________________

**Comment by kelson42** [comment]
Kind of suspect this os somehow linked to https://github.com/kiwix/kiwix-android/issues/1447... but this need a technical analysis.

**Comment by gouri-panda** [comment]
@4shutosh Sorry!, I can't say right now unless I test it. My guess would be either we are providing the wrong content path(URI) or the way the pdf is formated within zim are not valid with other apps. I really can't say unless I debug it.

**Comment by cdhiraj40** [comment]
@cjohnsto-nz can you provide the zim file name so that I can download it and try to reproduce this?
It would be really helpful, thanks :)

**Comment by Archenoth** [comment]
@cdhiraj40, @4shutosh An example of this behavior can be seen in the [Zimgit post-disaster library](https://download.kiwix.org/zim/other/zimgit-post-disaster_en_2022-01.zim). This zim file in particular is just one article filled with PDF links, all which appear to fail to open on Android in general.

**Comment by samuk** [comment]
What would really work for me is a bundled .[PDF viewer](https://f-droid.org/en/packages/com.gsnathan.pdfviewer/) which just opened .pdf's. Would that be a lot  of work?

**Comment by cjohnsto-nz** [comment]
PDF readers are incredibly feature rich. The functionality to pass through to another app is already there. It just doesn't seem to actually pass the file.
________________________________

**Comment by samuk** [comment]
Yes, it does assume that the user has a .pdf reader though. My use case would be offline, where the user may not have a .pdf reader. The intention is to install kiwix.apk from a SD card. I just need to add another step  to get the user to install pdfreader.apk first.

**Comment by Archenoth** [comment]
So, I decided to take a look at this to maybe get more information about what's happening here to hopefully help a little, and it looks like all of the content URLs in pages [are prefixed with `https://kiwix.app/`](https://github.com/kiwix/kiwix-android/blob/develop/core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt#L248), and later handled by the internal reader

But when the URL you select can't be opened by the internal reader, it just [tells an external app to do it](https://github.com/kiwix/kiwix-android/blob/develop/core/src/main/java/org/kiwix/kiwixmobile/core/utils/ExternalLinkOpener.kt#L35). This works for external URLs just fine, but external readers don't know what things like "`https://kiwix.app/I/files/Emergency%20Preparedness%20(1).pdf`" mean, since those URLs look like external URLs, even though they are intended to reference local files

This is also why you get a warning about opening external links when trying to open something that is included in the zim--because that's what it looks like to everything involved..!

**Comment by samuk** [comment]
So it just needs to be re-written to something like; file:///I/files/Emergency%20Preparedness%20(1).pdf

Or is it more complicated than that, for some reason I'm missing?

**Comment by Archenoth** [comment]
> So it just needs to be re-written to something like; file:///I/files/Emergency%20Preparedness%20(1).pdf
> 
> Or is it more complicated than that, for some reason I'm missing?

Since I don't think the files are ever extracted from the zim, I think that means that the links need to be replaced with `content://` URLs and that there needs to be a [ContentProvider](https://developer.android.com/guide/topics/providers/content-provider-creating) to serve it from. I could be wrong though!

I'm not really an Android dev (or know Kotlin), so I'm not sure how difficult that would be, though it looks like there might have been a ContentProvider for zim content in the past, since a commented out line in one of the tests references something that looks like one:

https://github.com/kiwix/kiwix-android/blob/bb9331d4f52a535de9e8eb5c309726f60b4c716a/app/src/androidTest/java/org/kiwix/kiwixmobile/ZimTest.java#L41
