### ISSUE TITLE
Same pictures are saved multiple times

### ISSUE THREAD

**Issue by cdhiraj40** [kiwix/kiwix-android#2755]
**Is your feature request related to a problem? Please describe.**
If I do  "Save a media" for same file, it saves multiple times

**Describe the solution you'd like**
Check if the picture exists before saving it
OR
ask the user if they wanna download the file again
(I have tried the code and it works perfectly in android 11&10)

To Reproduce:
1. Open any zim with pictures, hold the picture and click on save media
2. try this multiple times then
3.  go to storage->android->media->org.kiwix.kiwixmobile
you will see copies of the same files

**Additional context**

![Screenshot_2021-12-05-21-12-07-16_55bef12f624c2b805189a6aa783c400d.jpg](https://user-images.githubusercontent.com/75211982/144753628-e6764d2a-b0a6-4b36-89ed-7583d0444eba.jpg)

**Comment by kelson42** [comment]
Quite an appropriate behaviour IMO. Does Firefox or Chrome behave differently?

**Comment by cdhiraj40** [comment]
> Quite an appropriate behavior IMO. Does Firefox or Chrome behave differently?

@kelson42 chrome lets user decide by showing a small dialog that the file exist we could probably do the same if we also want to let the user decide if the picture already exists.

![Screenshot_2021-12-05-23-17-33-56_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/75211982/144757456-a40797b7-4217-42ae-bf02-679da5d6de9a.jpg)

**Comment by kelson42** [comment]
Ok, but then what happens in term of filename?

**Comment by cdhiraj40** [comment]
> Ok, but then what happens in term of filename?

the file name gets incremented in end by (1)

**Comment by cdhiraj40** [comment]
> Ok, but then what happens in term of filename?

@kelson42 file name gets incremented in end by (1)

kiwix does similar by adding _1 in end

**Comment by gouri-panda** [comment]
I believe sean and I discussed about this feature with sean while refactoring those files unfortunately  I can't find that ticket. I think Google Chrome and Firefox are concerned about this because they download the media files from the internet(it can be costly)  and duplicate files that occupy more memory. If memory is what we are concerned about then we can implement this feature, otherwise, we don't need to worry about it because we don't download the media(image) from the internet.
