### ISSUE TITLE
Filesystem Support

### ISSUE THREAD

**Issue by ChronosNoob** [kiwix/kiwix-android#2784]
I have a Nokia 2.4 and they have decided that their phones cannot support any filesystem other than fat32. I bought an SD card for use with this app. Then I find out that you can't download files over 4GB, due to restrictions in the filesystem. Is there any way you could make it so the app splits downloads into parts or something so I can download what I need to? 

Thanks in advance for any advice or help.

**Comment by cyberpunxrded** [comment]
This is not an issue with the App itself. Doing some digging, it is an issue in Android itself (some say licensing for ext systems, some say problem with certain Apps). 

For some reason when Android is interacting with an SD and certain Apps it will default the filesystem as FAT. The only solution I have seen proposed online is:

"If you want to use ext4 on your sd-card and your phone is rooted then try to change the /fstab.qcom (in root of filesystem). There is - easy to find - a line (one line!)

/devices/msm_sdcc.2/mmc_host /storage/sdcard1 vfat nosuid,nodev wait, voldmanaged=sdcard1:auto,noemulatedsd

Try changing vfat to ext4 …"

I'm guessing is this very simple fix to test it, but alas I know literally 0 about coding/debugging....

I'm guessing there is no possible way for the App to change this code in the OS on a standard Android install due to the level of permission needed....?

 If the next update could somehow fix this, it would be a gamechanger...or at least make an alternate build strictly for Rooted android devices if that is what is needed to access this fix.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

Its not possible to split zim file and download it until unless to being done on backend level.

**Comment by kelson42** [comment]
@ChronosNoob There is indeed no solution in view if your system does not support files larger than 4GB. Sorry.
