### ISSUE TITLE
Get app validated by the Play store moderation team

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#2791]

**Comment by kelson42** [comment]
@MohitMaliFtechiz What is the status on this ticket? Which PR fixes it?

**Comment by MohitMaliFtechiz** [comment]
hi Kelson,

I follow up the document [(https://developer.android.com/training/data-storage/manage-all-files)] tried both alternative with [MediaStore](https://developer.android.com/reference/android/provider/MediaStore) and [Storage Access Framework](https://developer.android.com/training/data-storage/shared/documents-files) but unfortunately on andorid 11 and above scan for zim file is not working without ```MANAGE_EXTERNAL-STORAGE```. So we need to  justify the usage of this permission to playstore.  We don't have any alternative now so. I am preparing the use cases which i will post to playstore so they approved our app.

**Comment by MohitMaliFtechiz** [comment]
Hi @kelson42 ,


### Why we required MANAGE_EXTERNAL_STORAGE permission

* To scan all external memory to load zim files.

* To select a public directory on sd card in which we save our zim files in android R and above ,
if the user delete our app then all the zim files automatically deleted which he downloaded with app.

* if users download the zim file from his desktop and put into the sd card outside the app specific       folder without MANAGE_EXTERNAL_STORAGE permission we can’t read that file on android 10   and above.

* We also use Media Store Api for this but in internal storage media store work fine and load the zim files but in external sd card Media Store Api won’t work on android 10 and above.
so that’s why we do it manualy and for that we need this permission for our app.

**Comment by kelson42** [comment]
@MohitMaliFtechiz What is left to do here?

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

We just to justify the google play store why we need this permission , i already mentioned you the reason why its being needed just need to pass this information to google while submitting to playstore.

**Comment by wbillan** [comment]
Why is ACTION_OPEN_DOCUMENT_TREE not an an option?  I have Poweramp and it has access to files and automatically updates its list of files solely based on granting access to a directory (i.e. using ACTION_OPEN_DOCUMENT_TREE) the first time I ran the app after I installed it.  With ACTION_OPEN_DOCUMENT_TREE, it has access to files in the directory and any subdirectories.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can we have a status updaze here please?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Can we have a status updaze here please?

@kelson42 , For this we have created a play store variant in which we are not using ```MANAGE_EXTERNAL_STORAGE``` permission which is the main reason play store rejected our last apk. Once we upload this variant on play store this issue will resolved as we are not using ```MANAGE_EXTERNAL_STORAGE``` permission in this variant.

**Comment by kelson42** [comment]
It shoukd work now, otherwise we will open a dedicated ticket
