### ISSUE TITLE
Stop relying on Jfrog for libkiwix JNI & other deps

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#2816]
We should reupload our current JNI content to Maeven.

Regarding rebuilding libkiwix JNI, see https://github.com/kiwix/java-libkiwix/issues/1

**Comment by MohitMaliFtechiz** [comment]
https://github.com/kiwix/kiwix-android/issues/2826

**Comment by gouri-panda** [comment]
@kelson42 Now We only depend on Jcenter for these two libraries.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 @gouri-panda ,

I have hosted the libkiwix 9.4.1 on jitpack https://jitpack.io/#kiwix/java-libkiwix/v9.4.1

**Comment by gouri-panda** [comment]
After updating the dependency we'll close this ticket.

**Comment by kelson42** [comment]
Why jitpack, we had decided to use maeven?

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 , Jitpack is best with github project because its auto build the release so we don't need any CI job for publish , as soon any release perform it will automatically within 2 minutes it will available on jitpack.

on the other side , I have spent a lot of time fixing issue with maven they have lots of signing mechanism ,  So to just upload the aar its required to sign in via PGP key and every time its failed on validation.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Ok, but the ticket ask specificaly to use Maven. You can not decide like this to change what to do withour refering. Your move raise many questions:
*

**Comment by kelson42** [comment]
@MohitMaliFtechiz I finally had a look in detail to jrtpack and even if jetpack might work, i'm not happy with it because the same problem like with bintray can happen. Jetpack has a freemium business model like bintray had. Please try to fix the key signing problem with Maven. First thing to do is to explain it in detail here.

**Comment by kelson42** [comment]
This has been made at https://search.maven.org/artifact/org.kiwix.kiwixlib/kiwixlib.
