### ISSUE TITLE
Show message if we don't have internet permission

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2841]
**Is your feature request related to a problem? Please describe.**
Currently, if the user hasn't been given network permission to download the data. The download screen is completely dark. It may confuse users about what's going on.
<img src ="https://user-images.githubusercontent.com/43576162/169288096-18e3b798-87a5-487c-83b4-b3a20256da7d.jpg" width=50% height=50%>

**Describe the solution you'd like**
Add a message text inside the screen and show users if they haven't given the network permission to download the content. And also a button would be nice to add the internet permission as we are doing now if the user refreshes the screen.

**Comment by Dark-Knight11** [comment]
Hi, I would like to work on this issue

**Comment by gouri-panda** [comment]
@Dark-Knight11 Thank you! Please go ahead!

**Comment by Dark-Knight11** [comment]
Hi, I looked into the issue a little bit and I'm confused about a few things.
- Unless the user specifically disables mobile data and wifi for the app, it won't lose its internet permission.
- If I disable these permissions, then on the download screen it simply shows `No Items Available`. So the enable internet settings message is expected here? because I'm not getting any blank screen here. If possible please provide steps to reproduce the issue.
- I tested these things on play store version. The build I got through the master branch of this repo was different from that of play store version. So please help me with the repo setup.

**Comment by gouri-panda** [comment]
@Dark-Knight11 Yes! If the app has internet permission but the user turned of network connection then it shows No items available (Maybe we should show network connection unavailable, it's a different issue). The objective of this issue show the app has no network connection permission. There are many way we can create this scenario.
**Steps to reproduce**

1. Fresh install the app
2. Go to download section
3. Don't allow network permission
4. See the blank screen 

Let us know if you need any help :)
