### ISSUE TITLE
codecov/patch almost systematicaly fails in CI

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#2883]
With #2874, we have now the ability to have a fine grained Codecov configuration at https://github.com/kiwix/kiwix-android/blob/develop/.codecov.yml.

It is as well configured in a way that this is not too sensitive. But still, codecov/patch almost systematicaly fails in CI to the contrary to 
codecov/project.

This means that the code added in the PR is not tested enough (at leas from a perspective of Codecov). I'm not happy with a CI result being systematically ignored (and PR merged). We should have a CI configured in a way this is helpful.

**Comment by kelson42** [comment]
@MohitMaliFtechiz @gouri-panda What do you propose to do? What would be the best approach to on one side garanty a good code quality, on the other side to have green CI... but without having to do sillly test code.

**Comment by gouri-panda** [comment]
@kelson42 I don't think it's possible with out test code. In code coverage we are measuring codes in project and patches by test codes. My solution would be add test cases in necessary PR's in order to get green CI. This will be a burden in short run but in a long run it will add great value to our project. @MohitMaliFtechiz What do you think?

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda and @kelson42 ,

For me its still uncleared how code coverage working on this project because i have seen sometime its just failed by reformatting without changing any test code and sometimes its increasing without making any addition to the file in which its indicate as increase. So for me i have to learned the parameter on which code coverage report is generated , its very unclear behaviour so far .

**Comment by gouri-panda** [comment]
According to Wikipedia
>Test coverage is a percentage measure of the degree to which the [source code](https://en.wikipedia.org/wiki/Source_code) of a [program](https://en.wikipedia.org/wiki/Computer_program) is executed when a particular [test suite](https://en.wikipedia.org/wiki/Test_suite) is run. A program with high test coverage has more of its source code executed during testing, which suggests it has a lower chance of containing undetected [software bugs](https://en.wikipedia.org/wiki/Software_bug) compared to a program with low test coverage.

>on the other side to have green CI... but without having to do silly test code.

So, without test code, it's not possible to increase our code coverage report.
> i have seen sometime its just failed by reformatting without changing any test code and sometimes its increasing without making any addition to the file in which its indicate as increase.

Maybe it failed before the formatting too ...

> @MohitMaliFtechiz @gouri-panda What do you propose to do?

My solution would be simple to write tests for those we're not covered yet.In this way we can increase the code coverage quality.

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda ,

Yes we need to add more test to improve the code coverage quality.

**Comment by kelson42** [comment]
@gouri-panda Please make a proposal of codecov configuration for qhich everybody is happy. To me, the only thing which is really important is that the global code coverage never goes down significantly. Basically all new code should have its automated testing code with it.
