### ISSUE TITLE
F-droid entry uses deprecated logo

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2895]
See here https://f-droid.org/en/packages/org.kiwix.kiwixmobile/

Correct logo to use is https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3.svg

**Comment by kelson42** [comment]
@IzzySoft This is something we should be able to configure/change via the Fastlane directory?

**Comment by IzzySoft** [comment]
@kelson42 yes: `images/icon.png` in the corresponding locale directories. And make sure you use the correct image inside the app itself (`res/drawable*` etc). Though the `icon.png` should override what#s used by the app itself, it would be a bit confusing if it looked different :wink:)

**Comment by kelson42** [comment]
@MohitMaliFtechiz P,ease handle this ticket.

**Comment by MohitMaliFtechiz** [comment]
hi @licaon-kter ,

Can you please let me know how we can update logo on F-Droid page , last release contain the right logo.

**Comment by licaon-kter** [comment]
I fail to see the issue

Al these look the same to me :shrug: 
* https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3.svg
* https://github.com/kiwix/kiwix-android/blob/develop/fastlane/metadata/android/en-US/images/icon.png
* https://f-droid.org/en/packages/org.kiwix.kiwixmobile/

**Comment by MohitMaliFtechiz** [comment]
hi @licaon-kter ,

On this logo https://f-droid.org/en/packages/org.kiwix.kiwixmobile/  look at feet and ball distance and compare with https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3.svg.

**Comment by licaon-kter** [comment]
:) ah, so it is different

Current version 3.5.0 is based on the in-APK icon (I guess), since, at that time, the fastlane icon was not setup, right https://github.com/kiwix/kiwix-android/blob/3.5.0/fastlane/metadata/android/en-US/images/icon.png ?

I'm not sure which icon got extracted, maybe https://github.com/kiwix/kiwix-android/blob/3.5.0/app/src/main/kiwix_icon-web.png ?

Anyway, for 3.6.0 fastlane icon.png should be used so this will be fixed then. Ping back if it's not

**Comment by MohitMaliFtechiz** [comment]
logo is now updated on F-Droid https://f-droid.org/packages/org.kiwix.kiwixmobile/ , I am closing this ticket.
