### ISSUE TITLE
Convert BookmarksDao.java to kotlin

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#2997]
Parent Issue: #1826

**Comment by kelson42** [comment]
Superseeded by #3105

**Comment by kelson42** [comment]
@gouri-panda Reopening this ticket as I suspect that we will need thsi class (in Kotlin) to allow a smooth Migration of the data to Room. What is exactly the purpose of this class?

**Comment by gouri-panda** [comment]
@kelson42 In a nutshell `BookmarksDao` class allows us to access bookmarks object such as bookmark url, bookmark zim id, and bookmark title from the database.

**Comment by kelson42** [comment]
OK, so we will need to use this class to read them and transfer them to the llibkiwix. So corresponding PR should be reviewed and merge now (otherwise we will still live with java corde for the next 2-3 releases).

**Comment by gouri-panda** [comment]
@kelson42 This class is totally replaceable with 1 PR. Our codebase follows android's [clean architecture](https://developer.android.com/topic/architecture) which means we have separate layers for separate things. It is independent of each other. so that we can replace/refactor one layer without refactoring another layer.

**Comment by kelson42** [comment]
@gouri-panda Again, we went through the whole argumentation already. We have to have one implementation to access ObjectBox and one to access the libkiwix at the same time in the codebase. This is necessary to be able to migrate the data from ObjectBox to libkiwix. How to do propose to proceed without keeping this class?
