### ISSUE TITLE
Display Navigation History

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3042]
Kiwix has a "back" menu option which is a type of history, but when you're researching a subject, jumping between several articles, it can be difficult
to refer back to article#3 and then article#7 and then article#4 just by the
"back" and "forward" menu options.

It would be great to have some kind of simple history viewer by implementing contextual menus on back and forward buttons. By long clicking on them you would get a list of the last/further 4-5 visited pages. This list should be scrollable to allow to store the whole visit history if necessary.

In the preference panel, an option should allow to clear the history.

From https://sourceforge.net/p/kiwix/feature-requests/679/

**Comment by kelson42** [comment]
@rishujam Yes, seems reasonable.

**Comment by rishujam** [comment]
> @rishujam We can not just rely on the webview history.

I guess webView history will not be enough we cannot determine which URLs will come in the back and which in the forward. If it is possible please help me a little

**Comment by MohitMaliFtechiz** [comment]
@kelson42 , I want to clear some points.
* Should we use ```BottomSheet``` (showing below in image) for showing list of history of book, when we long click on forward/backward images.
* Will we save the book history into database(because you request a option in preference screen to clear the history) or we should save in a list for runtime (if we switch to new book or close the application the history will cleared automatically).
* We will display forward and backward history separately? (if user click on forward, then we will show only forward history if any, otherwise it will show a no history found text).

![bottom-sheets-storage](https://user-images.githubusercontent.com/34593983/220106193-d6fe385d-e807-47bf-8730-ab4bb518c747.png)

**Comment by kelson42** [comment]
> @kelson42 , I want to clear some points.
> 
>     * Should we use `BottomSheet` (showing below in image) for showing history of book, when we long click on forward/backward images.

I don't understand what you mean. IMO it should popup when long clicking on history back/forward buttons

>     * Will we save the book history into database? (because you request a option in preference screen to clear the history) or we should save in a list for runtime (if we switch to new book or close the application the history will cleared automatically).

For the moment I would like that we only deal with the html rendering history. There should be a function already available to clean it. We should not store the history ourself.

>     * We will display forward and backward history separately? (if user click on forward, then we will show only forward history if any, otherwise it will show a no history found text).

yes

> ![bottom-sheets-storage](https://user-images.githubusercontent.com/34593983/220106193-d6fe385d-e807-47bf-8730-ab4bb518c747.png)
