### ISSUE TITLE
Custom created uptodate zim search not working on android (Works in Windows and kiwix-serve)

### ISSUE THREAD

**Issue by laggykiller** [kiwix/kiwix-android#3098]
**Describe the bug**
I have created a zim of uptodate by zimwriterfs. The content of uptodate is downloaded from archive.org: https://archive.org/details/UTDAll2018

Opening the zim in kiwix-android and searching does not work, with infinite loading. It behaved normally on Windows and kiwix-serve -> Firefox are normal.

**Expected behavior**
Uptodate zim displays result after searching on Android

**Steps to reproduce the behavior:**
1. Create the zim using the following commands on Linux (Sharing the zim publicly here has questionable legality?)
```
cd ~/Downloads

# Source of file: https://archive.org/details/UTDAll2018
# Alternative: Download by torrent (faster) from https://archive.org/download/UTDAll2018/UTDAll2018_archive.torrent
aria2c -x 16 https://archive.org/download/UTDAll2018/UTD%20all%202018.zip

# Unzip
unzip "UTD all 2018.zip"

# Download uptodate logo from google playstore
aria2c -x 16 -o ./UTDall/uptodate.png https://play-lh.googleusercontent.com/3wd1KjbgZpmS6ya09i62jvkRzRXPoEGWSMldomWiUbiNfEecTtBi-ZO2tbv_cdo9Rdg

# Need to increase file limit temporarily or else "Too many open files"
su
ulimit -n 1048576

# Build
zimwriterfs -w UpToDate.htm -l eng -I uptodate.png -t uptodate2018 -d "UpToDate 2018" -c UpToDate -p myself ./UTDall ./uptodate2018.zim

# Clean up (Optional)
rm -rf ./UTDall
rm "./UTD all 2018.zip"
```
3. Copy uptodate2018.zim to the android device
4. Open the zim from kiwix android app
5. Search for 'eczema' (or other terms)

**Screenshots (GIF)**
Android app: Search not working
![android](https://user-images.githubusercontent.com/61652821/193458406-d153e1af-b14d-4b4a-9619-24efeaa22a8b.gif)
Windows: Working
![windows](https://user-images.githubusercontent.com/61652821/193458429-ab5cd83a-8eee-4a3e-92de-4f80a917a3f3.gif)
kiwix-serve viewed on firefox: Working
![kiwix-serve](https://user-images.githubusercontent.com/61652821/193458410-b46f8d8b-5bdd-4405-b6c9-4b038041b933.gif)

**Environment**
- Version of Kiwix Android : 3.6.0 Build 7230600
- Device : Samsung Galaxy S20 FE 5G
- OS version : Android 12

**Logs**
Will be provided if required

**Comment by MohitMaliFtechiz** [comment]
hi @laggykiller ,

I tried to build the custom zim , I am following yours step please confirm the step
``` zimwriterfs -w UpToDate.htm -l eng -I uptodate.png -t uptodate2018 -d "UpToDate 2018" -c UpToDate -p myself ./UTDall ./uptodate2018.zim```.

here ```-I``` needs to be in lower case also ```-i``` stands for ```-i, --withFullTextIndex	index the content and add it to the ZIM.``` so i am not sure ```uptodate.png``` is the correct value for this also ```-f, --favicon		path of ZIM file favicon.``` is a mandatory options which is missing. 

I am following the following -- help
```
Mandatory arguments:
	-w, --welcome		path of default/main HTML page. The path must be relative to HTML_DIRECTORY.
	-f, --favicon		path of ZIM file favicon. The path must be relative to HTML_DIRECTORY and the image a 48x48 PNG.
	-l, --language		language code of the content in ISO639-3
	-t, --title		title of the ZIM file
	-d, --description	short description of the content
	-c, --creator		creator(s) of the content
	-p, --publisher		creator of the ZIM file itself

	HTML_DIRECTORY		is the path of the directory containing the HTML pages you want to put in the ZIM file,
	ZIM_FILE		is the path of the ZIM file you want to obtain.

Optional arguments:
	-v, --verbose		print processing details on STDOUT
	-h, --help		print this help
	-m, --minChunkSize	number of bytes per ZIM cluster (defaul: 2048)
	-x, --inflateHtml	try to inflate HTML files before packing (*.html, *.htm, ...)
	-u, --uniqueNamespace	put everything in the same namespace 'A'. Might be necessary to avoid problems with dynamic/javascript data loading.
	-r, --redirects		path to the TSV file with the list of redirects (namespace, url, title, target_url tab separated).
	-i, --withFullTextIndex	index the content and add it to the ZIM.
	-a, --tags		tags - semicolon separated
	-n, --name		custom (version independent) identifier for the content
```

**Comment by MohitMaliFtechiz** [comment]
hi @laggykiller ,

I tried build the zim you mentioned above , it was succeed by replacing ```-I```  to ```-f``` but when i am searching anything it's just bring me unloaded image. I am attaching the screenshot may be this is due to  different version of ```zimwriterfs``` . 

<img src=https://user-images.githubusercontent.com/34593983/193825526-f70042b2-fc35-4f23-8e56-2cd226c4687b.jpg width=200px height=400px/>

**Comment by laggykiller** [comment]
That unloaded image might be the spinning icon...
Does your zim work on desktop / kiwix-serve?

**Comment by laggykiller** [comment]
Sent via email. Please check if you received it

**Comment by MohitMaliFtechiz** [comment]
hi @laggykiller ,

I have check the issue and finally found out issue is with wrong redirect url  . URL is returning as ```https://kiwix.app/C/d/search.htm``` and return must be as ```https://kiwix.app/C/d/search.htm?s=eczema```. Issue is with the presence of ```?``` we are actually fetching url before ```?```. 
This might be auto fixed by merging the following https://github.com/kiwix/kiwix-android/pull/2968

**Comment by laggykiller** [comment]
@MohitMaliFtechiz thanks! Will check and close this once it is released

**Comment by laggykiller** [comment]
@MohitMaliFtechiz I tried to build branch [Issue#2671](https://github.com/kiwix/kiwix-android/tree/Issue%232671)
I searched for eczema with the built apk, and the result is a white page
![Screenshot_20221007-123613_Kiwix](https://user-images.githubusercontent.com/61652821/194469280-46f055eb-a2d7-48bb-b398-6c716738cd45.jpg)

**Comment by MohitMaliFtechiz** [comment]
hi @laggykiller @mgautierfr ,

yes i have found the issue with libkiwix when we are sending url containing ```?``` for example ```https://kiwix.app/C/d/search.htm?s=eczema``` to checkUrl function of libkiwix its just revert with empty string. 

@kelson42 please move this issue to libkiwix.

**Comment by mgautierfr** [comment]
There is no `checkUrl` function in libkiwix.

I'm not sure it is related to zim search. @laggykiller please confirm, but you seems to use a search feature internal to the zim you've created. At least when you search for `eczma` on the screen cast you've provided, you don't use the search bar of kiwix-desktop or kiwix-server but a search bar **in** the content of the zim file.
So you don't use the search engine of libzim/libkiwix.


On libkiwix side (not the server part) we don't put any special meaning on `?` it is just a char like the other.
On the server part however, `?` has a special meaning, it is used to mark the begining of the querystring. This is not specific a kiwix, it is a http/url standard. So if you want to pass a `?` to libkiwix through a web server, you must url encode the `?`. But only in this case.
kiwix-android do not use the server part of libkiwix (and can start a server, but it doesn't use it) so you should not have to url encode `?`

**Comment by MohitMaliFtechiz** [comment]
hi @mgautierfr ,

```checkUrl``` function in https://github.com/kiwix/java-libkiwix/blob/215237d3a61e2f50b269bc9b9c4fcc0599bd3b96/src/wrapper/java/org/kiwix/kiwixlib/JNIKiwixReader.java#L50. I a not sure whether its being removed on latest libkiwix or not but i am using 10.1.1.

**Comment by mgautierfr** [comment]
As you have pointed it, it is now in `java-libkiwix` not in `libkiwix` :)

You can see in the implementation of `checkUrl` (https://github.com/kiwix/java-libkiwix/blob/215237d3a61e2f50b269bc9b9c4fcc0599bd3b96/src/wrapper/java/kiwixreader.cpp#L292) that it is using `getEntryFromEncodedPath`. So you probably have to url encode the string you pass to `checkUrl`

**Comment by MohitMaliFtechiz** [comment]
hi @mgautierfr ,

So this will automatically fixed when we will start using latest libkiwix and libzim with updated JNI wrapper.

**Comment by laggykiller** [comment]
@mgautierfr can confirm that the zim only has ~10 static html pages, and to view the articles, searching with internal search bar is required to load the dynamically generated pages

**Comment by MohitMaliFtechiz** [comment]
@mgautierfr, @kelson42 I have tried this with `java-libkiwix` 11.0.0 but it is not able to read the article after searching `eczema` inside the zim file.

**For the eczema URL, it is not working.**
Actual URL: https://kiwix.app/d/search.htm?s=eczema
URL passed to libkiwix: d/search.htm
URL obtained from the library: d/search.htm
Has entry in libkiwix: true

Here, we are extracting the URL before the '?' symbol, which is displayed with a loading icon.


Actual URL: https://kiwix.app/d/search.htm?s=eczema
URL passed to libkiwix: d/search.htm?s=eczema
Has entry in libkiwix: false

If we are passing the URL with `?` libkiwix returns there are no entry found for this url.

**For other URLs:** They are working fine with the same type of URL, even if they contain a '?' symbol.
Actual URL: https://kiwix.app/d/toc.htm?path=whats-new
URL passed to libkiwix: d/toc.htm
URL obtained from the library: d/toc.htm
Has entry in libkiwix: true

We extract the link before the '?' symbol, and it works correctly. However, if we try to load the full URL (https://kiwix.app/d/search.htm?s=eczema) without extracting the part before the '?' symbol (since all the articles load correctly on the 'kiwix-extension'), libkiwix does not return the entry for that path. This behavior is also observed for the URL https://kiwix.app/d/toc.htm?path=whats-new. In my opinion, the URL appears to be correct with extracting before `?`, but the content is not loaded properly as it is when using the 'kiwix-extension'.

This behavior is same with all URL's who are `https://kiwix.app/d/search.htm?s=eczema` this type (Means, which have the query in URL, most of the pages of this zim file have this type url).

![Screenshot from 2023-07-18 18-16-55](https://github.com/kiwix/kiwix-android/assets/34593983/20ba3c66-f294-470a-b550-e52cebbb77c3)

**Comment by kelson42** [comment]
@MohitMaliFtechiz so... what is wrong with libkiwix?

**Comment by MohitMaliFtechiz** [comment]
@mgautierfr Thanks for your clear explanation, now it is able to load the content of `eczema` as well as for other articles which contain query params.


https://github.com/kiwix/kiwix-android/assets/34593983/cb1ddcb1-56b1-43cf-9fc9-af0f0c877299

**Comment by laggykiller** [comment]
Can confirm that it works using apk in artifact from https://github.com/kiwix/kiwix-android/actions/runs/6225784317

Thanks for hardwork!
