### ISSUE TITLE
Use libkiwix to store bookmarks

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3109]
This is a subtask for #3102 . Write migration test and new database test for Bookmarks.

 * BookmarkEntity (Responsible for stroing and updating Bookmarks) https://github.com/kiwix/kiwix-android/blob/e2c901bf22034ea891c29ce12bc5793df7eccf52/core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/BookmarkEntity.kt

**Comment by kelson42** [comment]
After discussion with @mgautierfr, it seems clear to me we should not use Room for the bookmarks. Read https://github.com/kiwix/libkiwix/issues/840. The libkiwix provides already all the primitives.

**Comment by gouri-panda** [comment]
@kelson42 Sounds good to me!

**Comment by MohitMaliFtechiz** [comment]
@kelson42, Now we have the latest libkiwix which has the functionality to store the bookmarks in `Library`, Library has inbuilt functions to [write bookmarks in a file](https://github.com/kiwix/java-libkiwix/blob/f9dc43e17700568143ef24edd7ca30fc8ea711be/lib/src/main/java/org/kiwix/libkiwix/Library.java#L45) (this is for write the bookmark in a file which we will use later for retrieving the saved bookmark), [write a library to file](https://github.com/kiwix/java-libkiwix/blob/f9dc43e17700568143ef24edd7ca30fc8ea711be/lib/src/main/java/org/kiwix/libkiwix/Library.java#L44) (this holds the books in it which has the zimFilePath, favicon, etc).
We had to save the bookmarks and library to their respective files(`bookmark.txt`, `library.txt`) since we read bookmarks and their filePath, and favicon from these files.

In #3474 we have implemented this functionality.

we have successfully implemented the functionality of bookmarks with libkiwix (Save, retrieve, delete) while saving or deleting the bookmarks we are updating the corresponding files with the updated data to avoid any data loss.
We have implemented the migration functionality from ObjectBox to libkiwix to keep the previous bookmarks, to properly test the migration functionality we have written the test cases for it.
Now the only thing left to do is write test cases for saving, deleting, and retrieving functionality, As for testing these functionalities we need to use the libkiwix classes and we need to create wrapper classes as we created in `java-libkiwix` https://github.com/kiwix/java-libkiwix/tree/main/lib/src/test/org/kiwix/test/libkiwix here is the tricky part ,  to summarise functionality to save bookmark using libkiwix is done while creating test cases we required the wrapper which is taking time. So I am working on it.

Please let me know your thought on this.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Testing reading/writting bookmarks should be tests in java-libkiwix. It does not make sense to test here because there is no additional logic.

Here, you need to test the bookmark related UI and migration.

**Comment by MohitMaliFtechiz** [comment]
> Please confirm you don't write anything to fs or create custom bookmark related structures/objects.

@kelson42 We are saving bookmarks and library in the file system because libkiwix stores bookmark and books in `library` in the current session(e.g. when the user is using the application) if a user close the application then the libkiwix session is expired and it has not anything in memory. so we need to save bookmarks, and books in the filesystem to access them later as @mgautierfr mentioned there are some methods to store the bookmarks and library in a file which is our current approach to save the bookmarks and book in a file and retrieve those later via `Manager` to read saved bookmarks and their filePath, favicon.

So we are using [write bookmarks in a file](https://github.com/kiwix/java-libkiwix/blob/f9dc43e17700568143ef24edd7ca30fc8ea711be/lib/src/main/java/org/kiwix/libkiwix/Library.java#L45) and [write a library to file](https://github.com/kiwix/java-libkiwix/blob/f9dc43e17700568143ef24edd7ca30fc8ea711be/lib/src/main/java/org/kiwix/libkiwix/Library.java#L44) to deal with filesystem , we are not using any native android filesystem methods.

> Here, you need to test the bookmark related UI and migration.

If this is the approach then we just need to create an instrumentation test case for testing the bookmarks-related UI. The migration test case is already written.

**Comment by kelson42** [comment]
@MohitMaliFtechiz I meant, you don't write to rhe fs *outside the libkiwix*

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz I meant, you don't write to rhe fs _outside the libkiwix_

Yes nothing outside the libkiwix.

**Comment by kelson42** [comment]
Last comment seems to me to clarify the situation appropriatly https://github.com/kiwix/kiwix-android/issues/3109#issuecomment-1723270358. PR shozld be completed, tested and reviewed.
