### ISSUE TITLE
Room migration of Languages

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3112]
This is a subtask for #3102 . Write migration test and new database test for LanguageEntity.

Should be done:
* A kind of generic and abstract accessor to access Room data
* Secure the Room DB is created properly at start (if it is not easy to create on the fly) if necessary (first installation or migration context)
* The data structure and accessor to the languages (based on what exists in ObjectBox)
* Link with the existing code around the languages(disconnect this from ObjectBox)
* Write the automated tests (Unit tests and maybe one UI test) for that new Room code (adapt what exists for ObjectBox)
* Write the migration function (for the data) from the ObjectBox language DB to the Room DB
* Write automated tests for that migration function
* LanguageEntity (Responsible for storing all language lists that user can search) https://github.com/kiwix/kiwix-android/blob/e2c901bf22034ea891c29ce12bc5793df7eccf52/core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/LanguageEntity.kt

**Comment by kelson42** [comment]
I think the problem is slightly more complex. I believe the language list might better be retrieve from the local and [online library](https://kiwix-tools.readthedocs.io/en/latest/kiwix-serve.html#catalog-v2-languages). But this is still unclear to me how exactly we should do it:
* Directly via API?
* Via libkiwix? But does that merge local and remote API?
* Do we need to cache the result? in Room?

**Comment by kelson42** [comment]
To be superseeded with #2689

**Comment by kelson42** [comment]
Clsing
