### ISSUE TITLE
An Italian translation string

### ISSUE THREAD

**Issue by opk12** [kiwix/kiwix-android#3134]
`Download book to internal storage?` is not translated in Italian. It should read as `Scaricare il libro nella memoria interna?`

**Comment by kelson42** [comment]
@gouri-panda @MohitMaliFtechiz It's a problem in An old version of Kiwix? In Translatewiki? In our code?

**Comment by gouri-panda** [comment]
@kelson42 It is from Translatewiki side but we can fix it here.

**Comment by kelson42** [comment]
@gouri-panda Thx, but no added value to fix it here if erased by next PR from TW. But I don't see the string "cancel" in the list of strings left to be translated in Italian?! https://translatewiki.net/w/i.php?title=Special:Translate&group=kiwix&language=it

**Comment by gouri-panda** [comment]
@kelson42 Yes! The translation has already been done. @opk12 You're using an old version of APK. The issue has been fixed. It happens when they are no translations for local languages. It picks a default language. 

<img src="https://user-images.githubusercontent.com/43576162/204100456-cc8550a2-46b1-4fe7-8da6-cbbaad7ef19d.jpg" width=50% height=50%>
