### ISSUE TITLE
Remove red effect while changing tab from reader to library and to other

### ISSUE THREAD

**Issue by utkarsh006** [kiwix/kiwix-android#3250]
**Describe the bug**
Remove red effect which appears while changing tabs from reader to library and to other tabs. This doesn't look adequate while user interacts with UI

https://user-images.githubusercontent.com/94545831/221420164-f0505235-c2b6-4a2d-be3e-95058d824f36.mp4

**Expected behavior**

Remove this effect and ensure that no such red lines appear while changing tabs

**Steps to reproduce the behavior:**
1. 

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.6.0
- Device : Samsung SM-A127F
- OS version : 12

**Logs**

**Comment by utkarsh006** [comment]
@kelson42 Kindly assign the issue to me.

**Comment by kelson42** [comment]
@utkarsh006 AFAIK this is only in the debug version andmight be linked to canaryleak. I guess there is nothing to do. @MohitMaliFtechiz Can you please enlight us about the reason behind this artefact in the debug APK?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 , We have implemented ```StrictMode.setThreadPolicy``` in debug mode. The red line effect is due to disk violation caused by accessing files from our system to show in the LocalLibrary and deleting the cache directory.
https://github.com/kiwix/kiwix-android/blob/192d276103aa7bd7d410fb8810505e88ee0f2da4/core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt#L56

**Comment by kelson42** [comment]
@MohitMaliFtechiz Few complementary questions:
* Do this "disk violoation" are the consequence of a bad software design?
* What are the concrete consequences for the user?
* Should we fix the problem, if "yes" what are the possible approaches?
* What would you personnaly recommend to do?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 ,

> Do this "disk violoation" are the consequence of a bad software design?

Yes, disk violation is not a sign of good software design. A disk violation occurs when an attempt is made to read from or write to a file on disk and the operation fails due to one or more reasons. One common cause of a disk violation is when a program attempts to delete a file that is currently being used by another program. Another cause is when a program does not have the proper permissions to read or write a file on disk.

> Should we fix the problem

Actually, this issue is related to changes made in newer versions of Android that restrict apps from directly accessing files using their absolute path. In earlier versions of Android, creating a file object to delete a cache directory using its absolute path would work fine. However, in newer versions of Android, this approach may cause a disk violation error due to increased security restrictions. our code is working fine here so it's not impacting any application functionality, here it's just a warning.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thank you for the explanation.
@utkarsh006 So, "yes" there is something to fix. Would you still be interested to identify and then fix the bug(s)? If "yes" please explain here as a comment what you clearly have identified and how you plan to fix it (so before coding things and making a PR).
