### ISSUE TITLE
Make an F-Droid repository?

### ISSUE THREAD

**Issue by equwal** [kiwix/kiwix-android#3319]
The "official" F-Droid version is 4 years behind thanks to bureaucracy on their end.

Why not make a cool custom repository to track the latest release, rather than manual APK download? It can even have a QR code. That's how microG does it. They have a nice download page:

https://microg.org/download.html

https://f-droid.org/repomaker/

**Comment by kelson42** [comment]
We are going to fix the FDroid problem by removing ObjectBox fron our codebase. Currently all of this is in the 3.8.0 milestone.

**Comment by ZLima12** [comment]
To clarify here, the reason that the F-Droid build is so outdated is not because of bureaucracy on their end. The version that is on F-Droid currently is the newest version that does not use ObjectBox, which is considered non-free. Once a new release is created without this code, F-Droid will update to it.
