### ISSUE TITLE
More "compact" language selection dialog

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#342]
The current language selection dialog looks currently like this:

![screenshot](https://user-images.githubusercontent.com/1029718/35043987-ee3866a4-fb8e-11e7-94a1-32988fd74874.png)

Not so many languages are displayed at the same time which forces quite a bit of scrolling. I think we should but the language name in the language itself into parenthesis juste behind the language name in UI language. So everything on one line. This would allow to display more languages at the same time and need less scrolling.

**Comment by Ryan10145** [comment]
How do you get to this menu? I can't seem to find it. I recall seeing a screen similar to it a while ago, but I can't figure out how to get to it.

**Comment by kelson42** [comment]
@Ryan10145 In the library, online, top right corner icon.

**Comment by divadsn** [comment]
Maybe also add the user's system language on top of the list? :)

**Comment by kelson42** [comment]
@divadsn will have a look in the next day :)

**Comment by Ryan10145** [comment]
@kelson42 Thanks for the help, I managed to find it :)

**Comment by Ryan10145** [comment]
![list](https://user-images.githubusercontent.com/8119928/35134066-f748c3ba-fca1-11e7-926c-7e934163d5e4.PNG)
Is this spacing ok? Sorry if this isn't the best picture, I can send more from different screen resolutions if wanted.

**Comment by Ryan10145** [comment]
Additionally, I was going through the languages, and I noticed that some of the parentheses appeared to be filled with random whitespace. I looked at some of these in the console, and it turns out that some of the strings from `language.languageLocalized` contain values such as ᏣᎳᎩ (for Cherokee), and they won't display in the app. 
![list 2](https://user-images.githubusercontent.com/8119928/35134999-35e311ba-fca8-11e7-8ec8-99cd7301ae36.PNG)
How can I detect these faulty strings and how should I deal with them? Should I just have the parentheses be empty, e.g. "Cherokee ()", or should I just not include them, e.g. "Cherokee"?

**Comment by kelson42** [comment]
@Ryan10145 Thank you very much. Any chance to reduce a bit the lines height? Regarding the font, I think there is already a system to display characters which are not in the "default" font. The way to do that is to load a font which can display the characters (like "dejavu" for example). @mhutti1 You confirm?

**Comment by divadsn** [comment]
@Ryan10145 regarding the font problem, have a look here: https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml.html :)

**Comment by Ryan10145** [comment]
Thanks @mhutti1 and @divadsn for the help; I managed to get the font system working. However, I need to get more fonts so that I can display the characters for Cherokee, Dzongkha, Gujarati, Oriya, Punjabi, Sinhala, and Tibetan. Is there a preferred place to obtain these fonts and credit them?

Another issue I'm having is that I can't make the line height smaller for each item. I tried setting `android:layout_height` to a smaller value in language_check_item.xml, but the list keeps displaying it at the same size. I've also tried setting `android:min_height`, but nothing has any effect. Does anyone know a solution for this?

**Comment by mhutti1** [comment]
So for the fonts I am not sure. If you need to credit them then there is an item in the settings menu for that.    For the sizes I sometimes find you can use https://developer.android.com/studio/debug/layout-inspector.html to help you with that.

**Comment by kelson42** [comment]
@Ryan10145 For each language, you need to find the best free font we can embed in the app. I do not know a prefered place for that.

**Comment by Ryan10145** [comment]
I found the problem with the height, the margins for language entries count TextView were making the row extremely large. 

Is this size suitable? 

![list 3](https://user-images.githubusercontent.com/8119928/35198069-21b3ad88-feb7-11e7-98a7-f4e08684a5b2.PNG)

**Comment by mhutti1** [comment]
I personally might prefer a bit more padding but this should be perfectly fine.

**Comment by kelson42** [comment]
@Ryan10145 Good, yes, maybe add a few pixels more of padding please :)
