### ISSUE TITLE
content not found on wifi hotspot

### ISSUE THREAD

**Issue by mascherm** [kiwix/kiwix-android#3466]
**Describe the bug**
when i make a hotspot and try to check the content, the server adress show the overview with the search and for example 10 books. but i cant enter a book. it gives me " The requested URL "/wikipedia_de_all_maxi_2023-02" was not found on this server. ".
i can search for topics in the top search bar and the shared books get searched and i get the right results.

**Steps to reproduce the behavior:**
1.  start server on android device
2. open the server adress on the same or other device
3. try to click a book
5. Try the Searchbar on the Error Page

**Environment**
- Version of Kiwix Android :  3.7.1
- Device :  xiaomi 12 pro
- OS version : android 13 

- Version of Kiwix Android :  3.7.1
- Device :  samsung a52s
- OS version : lineage os 20

**Comment by MohitMaliFtechiz** [comment]
@mascherm I confirm this issue exists with libkiwix `10.0.0`, but this is fixed in the new `java-libkiwix`. If you know a little bit about `Android Studio` and coding please try https://github.com/kiwix/kiwix-android/pull/3217, otherwise can you please try with this apk https://drive.google.com/file/d/1razhu6pbH3hdiFdJUCwxaR_tpVVjxM7I/view?usp=sharing. Is this issue still exist on your end?

**Comment by mascherm** [comment]
it works fine in the test version you provided. thanks
