### ISSUE TITLE
Add support of Android 14

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3478]
With proper test in CI

**Comment by kelson42** [comment]
@gouri-panda Maybe this is something you would be interested to do?

**Comment by kelson42** [comment]
No sure if @gouri-panda still work on this, but this ticket would be the first to complete IMO in the `3.9.0` milestone.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Beside bug fixing, this is the priority to implement.

**Comment by kelson42** [comment]
We need to move quickly on this now!
![image](https://github.com/kiwix/kiwix-android/assets/1029718/53f7748b-1735-4528-a57d-757d108ecc0b)

**Comment by MohitMaliFtechiz** [comment]
Depends on https://github.com/kiwix/kiwix-android/issues/3141.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Once https://github.com/kiwix/kiwix-android/issues/3141 fixed, how much work would be left to fix this?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 For this we have an old PR https://github.com/kiwix/kiwix-android/pull/3481, and we have refactored the mostly code according to Android 14 at that time. So after fixing  #3141, there are only a few changes left to implement this ticket.

**Comment by kelson42** [comment]
@MohitMaliFtechiz What is this ticket fixing exactl as an issue? I have an Android 14 and it already seems to work fine?!

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Yes, for now, it will work on your Android 14 device like it is working on my Google Pixel 7a(Android 14), because our current target SDK version is 33(Android 13) and the current grade and SDK do not have the latest files according to Android 14. But when we upgrade our target SDK and gradle which properly supports Android 14(and we need to upgrade it to publish the application on playStore). Then the errors will come due to the fetch library's broadcast receiver since compatible files are in the new version of SDK and Gradle. So this ticket is for upgrading the target SDK, and Gradle, and refactoring our code according to the new changes that come in the new Gradle and SDK e.g. `namespace`, upgrading the dependencies, etc.
