### ISSUE TITLE
User report being unable to install from playstore (Android 13)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#3494]
I cannot reproduce so do what you want with it but here it is:

> Samsung A03s 
> android version 13 A037USQU4DWG1  
> security patch June 1, 2023 
> When I go to the 'Kiwix for Android, get it on Google Play link I get this message; 
> `This app isn't available for your device because it was made for an older version of Android.`
> The Google Play store will not allow me to install it.

**Comment by kelson42** [comment]
Seems to be new playstore politic... but shoukd work IMO. Anyway fixed in 3.8.0. @MohitMaliFtechiz you confirm?

**Comment by MohitMaliFtechiz** [comment]
>This app isn't available for your device because it was made for an older version of Android.

@kelson42, @Popolechien This error means which version is user tries to install the application that is not compatible with Android 13. It might be user is trying to install the application from the Play Store and that user is not the beta tester of our application, because on Play Store currently showing for the last update in 2021.

| Android 13  | On Desktop |
| ------------- | ------------- |
| ![1696398335045](https://github.com/kiwix/kiwix-android/assets/34593983/e87181aa-aa52-42b9-8946-959829b10d5b)  | ![Screenshot from 2023-10-04 11-14-21](https://github.com/kiwix/kiwix-android/assets/34593983/9df7b95b-58cd-4cc8-ba50-802919605879) |


> I cannot reproduce so do what you want with it but here it is:

Probably you are the tester for the application.


Once we have published the APK for all users it will automatically fixed.

**Comment by Popolechien** [comment]
@MohitMaliFtechiz Thanks a lot, makes sense.
