### ISSUE TITLE
Nautilus-generated zim files open to blank screen.

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#3495]
Tested on 3.7.1 (android 13) with the following zim files:
- A library of knots
- Food for preppers
- Medical library

All of them open to a blank screen, but all of them work on Kiwix-server ([1](https://library.kiwix.org/viewer#zimgit-knots_en_2023-06/home), [2](https://library.kiwix.org/viewer#zimgit-food-preparation_en_2023-08/home), [3](https://library.kiwix.org/viewer#zimgit-medicine_en_2023-08/home))

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Haven't we solved this problem? Is the issue still relevant?

**Comment by kelson42** [comment]
Pretty sure, @Popolechien please test with nightly and reopen if necessary.

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda, @Popolechien version `3.7.1` of kiwix is using an old wrapper, we already adapted the new wrapper in `3.8.0` and this bug was fixed in `3.8.0` can you please try with these zim files with the develop branch or try it with the [latest nightly](https://download.kiwix.org/nightly/2023-10-04/kiwix-universal-2023-10-04.apk).
