### ISSUE TITLE
Hitting back on the DWDS app exits it

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#3507]
I'm on a Nothing Phone (1) running Android 13. The usual manner to come back to the previous page is to slide the screen right-to-left. With the current test DWDS (as well as Wikimed; 2023-06 build 6231840) apps, this closes the app and returns the user to the phone's home screen.

I cannot reproduce this bug on the Kiwix app (3.7.1 build 7230701) - going back works fine there.

**Comment by Popolechien** [comment]
Looks like this was addressed in #2886 - is this a regression then?

**Comment by MohitMaliFtechiz** [comment]
@kelson42, @Popolechien It not only exits the app when clicking on the back button, but if you read the Zim file and clicked on an article it takes you to the second page then if you click the back button also it exit from the application instead of going to the previous page.


https://github.com/kiwix/kiwix-android/assets/34593983/c356697c-6632-4a79-acb5-56273cd06b4e


This is because on the `CustomReaderFragment` when the back-pressed event triggers we are finishing the activity https://github.com/kiwix/kiwix-android/blob/981b4e67c71e3018a46e99da712c4c5bcf1b12d1/custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt#L96 

this was introduced in https://github.com/kiwix/kiwix-android/pull/2371 I am currently checking why we have finished the activity when back-pressed is triggers.

**Comment by MohitMaliFtechiz** [comment]
@Popolechien, @kelson42 I have placed a fix for it in #3512.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please secure that for the whole class only the strict necessary is reimplemented (I have seen many methods which are reimplemented without reason). If not, then a clear warning (as code comment) inviting to look the the child class version of the method should he put at parent method head.

It does not make sense to me to override a method and just calling "super". Just remove overriding and it should take parent version.

**Comment by kelson42** [comment]
@MohitMaliFtechiz You don't have follow my request, please do.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz You don't have to follow my request, please do.

@kelson42 I have removed the unnecessary overridden from `CustomReaderFragment`, Sorry i have not removed it from the full code I was thinking it was not related to this PR. I am removing those unnecessary overridden methods from the code.
