### ISSUE TITLE
Custom apps should be able to customize the sidebar log

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3524]
Right now, the prominent placement of the Kiwix logo in the sidebar menu confuses the user. Could we replace the Kiwix logo in the sidebar title with a custom logo (to be specify in the custom app directory always at the same place). This would be helpful for the DWDS app.

**Comment by kelson42** [comment]
@MohitMaliFtechiz LGTM

**Comment by MohitMaliFtechiz** [comment]
For dwds app, we only need this image and we will create a drawable directory here and put that file there. https://github.com/kiwix/kiwix-android-custom/tree/main/dwds/res

**Comment by gremid** [comment]
@MohitMaliFtechiz  Would https://www.dwds.de/static/images/dwds-og.png work?

**Comment by MohitMaliFtechiz** [comment]
@gremid Since this image is png it looks weird in the sidebar logo. As you can see the space between the image and the Bookmarks option.

![Screenshot_20231109-143943_Test Custom App](https://github.com/kiwix/kiwix-android/assets/34593983/7183099e-821f-438f-94e1-2af34fd81126)

It would be better if we made this image JPG with the same background color(or any better color) as it is showing in my Chrome (might be different for you according to your Chrome profile theme).

![Screenshot from 2023-11-09 15-07-04](https://github.com/kiwix/kiwix-android/assets/34593983/534bfdf2-21c4-494a-a76b-b83d734d0011)

**Comment by gremid** [comment]
@MohitMaliFtechiz 

> Since this image is png it looks weird in the sidebar logo. As you can see the space between the image and the Bookmarks option.

I assume the additional padding on the top and bottom results from the image contents, not its format. Could you try

 https://www.dwds.de/static/images/dwds_286_67.png
 
 instead? This is a version without vertical padding, though a bit smaller in size. Alternatively, could you crop the first version so it fits the UI?
 
 > It would be better if we made this image JPG with the same background color …
 
IMHO the advantage of PNG is precisely the transparent background, which let's the logo background adjust to whatever background you pick for the sidebar menu, whether it is a shaded white, grey etc. Also the compression is lossless which normally is preferred for images like logos. Would PNG work as well?

**Comment by MohitMaliFtechiz** [comment]
> https://www.dwds.de/static/images/dwds_286_67.png

This one does not look good.

![Screenshot_20231110-143046_Test Custom App](https://github.com/kiwix/kiwix-android/assets/34593983/5b9d246f-3b88-42eb-950c-a7561f7d7404)

> Could you crop the first version so it fits the UI?

Yes, I have tried, and it looks better in comparison to the original image.

![Screenshot_20231110-142731_Test Custom App](https://github.com/kiwix/kiwix-android/assets/34593983/14603a72-411a-405c-866e-8cad36aa3db3)
