### ISSUE TITLE
Remove Redundant Top Navbar Title in Custom Apps; Use Saved Space for Immediate Access to Search

### ISSUE THREAD

**Issue by gremid** [kiwix/kiwix-android#3528]
**Is your feature request related to a problem? Please describe.**

In custom apps (i. e. DWDS) the title in the top navbar is often redundant. It does not change (as the used ZIM does not change), and the title is often repeated in one way or the other in the embedded ZIM content.

**Describe the solution you'd like**
Instead of switching between the ZIM title and the search query input via the search toggle button (magnifying glass icon), display the search query input permanently, allowing the user to immediately issue search queries without first toggling the view.

**Additional context**

Search queries ("lookups") are the primary mode of navigation in dictionaries, probably in encyclopedic content as well. Therefore search functionality should be placed prominently and be most easily accessible.

**Comment by kelson42** [comment]
@gremid Seems to make sense to me as well, but would like to think twice about that one.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Here my feedback on this:
* I think the request here (for DWDS) is really legit and should be implemented
* One problem I see is that - and this is already a problem - the zone which is touchable is only the zone behind the title whereas this should be the whole zone until the first logo. This has for consequence that if the title is small the touchable zone will be too small. We should make the touchable zone as big as possible if we implement this ticket
* I'm not sure if this is a really good idea for all apps, for all custom apps, only for certain custom apps. Actually if we remove the ZIM/App title, there is no easy way to identify the app and/or the content. Maybe this feature request should come with replacing the "hamburger" with the logo of the app/zim

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Here is my feedback on this:
I think the request here (for DWDS) is legit and should be implemented
One problem I see is that - and this is already a problem - the zone which is touchable is only the zone behind the title whereas this should be the whole zone until the first logo. This has for consequence that if the title is small the touchable zone will be too small. We should make the touchable zone as big as possible if we implement this ticket https://github.com/kiwix/kiwix-android/issues/3547

@kelson42 For the first point I have placed a fix for it in https://github.com/kiwix/kiwix-android/pull/3566.

> I'm not sure if this is a really good idea for all apps, for all custom apps, only for certain custom apps. If we remove the ZIM/App title, there is no easy way to identify the app and/or the content. Maybe this feature request should come with replacing the "hamburger" with the logo of the app/zim

It is not as simple as it looks because this title/toolbar is used in both Kiwix and custom apps so directly removing this from custom apps is not possible. Instead of directly removing this we can add one more property to `info.json` e.g. `disable_title` if this property is set to true then we hide the title from custom apps. By doing this way we have more control over apps which apps should show the title and which apps not.

**Comment by kelson42** [comment]
@gremid OK, moving forward on this.
@MohitMaliFtechiz Thank you, I believe the work done so far is useful, but we need a bit more IMO, Here my proposal:
* replacing the emoty space created by a placeholder “Search…”
* put a small border on the whole input zone so the user clearly undestand this is an input zone
* Magnify glass should be put on the right - inside - the input box
* All of this should work fine if UI is rtl language

**Comment by MohitMaliFtechiz** [comment]
> replacing the empty space created by a placeholder “Search…”
put a small border on the whole input zone so the user clearly understands this is an input zone
Magnify glass should be put on the right - inside - the input box
All of this should work fine if UI is rtl language

@kelson42, sounds good to me, it will be helpful for user.

**Comment by MohitMaliFtechiz** [comment]
> @gremid OK, moving forward on this. @MohitMaliFtechiz Thank you, I believe the work done so far is useful, but we need a bit more IMO, Here my proposal (for custom apps):
> 
> * replacing the empty space created by a placeholder “Search…”
> * put a small border on the whole input zone so the user clearly understands this is an input zone
> * Magnify glass should be put on the right - inside - the input box
> * All of this should work fine if UI is rtl language

@kelson42 I have added the placeholder in https://github.com/kiwix/kiwix-android/pull/3566 as you requested.
