### ISSUE TITLE
Using TTS on Wikivoyage 2023-06 (Android 13) reads code aloud

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#3530]
From a user:
> The read aloud functionality seems to read the code rather than just the text. "The Galapagos" is a good example, it starts off reading the page title and then delves into what I assume is the behind the scenes code. 
> I'm currently using Version 2023-06 on an Android 13 device. Let me know if you need any other info. 

I'm putting this here as we don't recall seeing this kind of bug report for the regular android version. I also see some possibly related issues have been closed for release 3.8.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Domyou confirm the regression.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Yes I confirm it is a new bug, the zim file has the `<style>` attribute inside the `<p>` tag that's why it is reading that coding part.

![Screenshot from 2023-11-17 14-50-57](https://github.com/kiwix/kiwix-android/assets/34593983/451937a0-df0e-475a-bbfe-9cc718b9865a)


However, we can handle this on the `Android Side`, but the `<style>` attribute should not be placed on the content location, I am currently testing this on my device.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Where is the bug exactly? In the Html code? In the TTS player? In Kiwix?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 The bug is in `HTML code` as `<style.` tag is generally placed in the `<head>` tag but here it is placed inside the `<body>` tag as shown in the above image. Might be it is placed for a good reason.

But yes it is the android bug as well since we have options in `javascript` to remove such keywords as we are doing here. https://github.com/kiwix/kiwix-android/blob/252d846b64fc669670b3028f5d59a3ffc211f51e/core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt#L154

We should fix this in the android code to not take `style` while reading the article to avoid this kind of issues.
