### ISSUE TITLE
Start-up message to inform about the restrictions on the Google Store app to open sideloaded ZIM files

### ISSUE THREAD

**Issue by vivadavid** [kiwix/kiwix-android#3576]
Hi,

Following the recent restriction applied on the Google Store app that prevents Kiwix from opening sideloaded ZIM files, I suggest adding a start-up message, which should say something like:

>  Due to Google Play policies on Android 11 and above, this Google Store app can't open sideloaded ZIM files. You can either download them through the app or, instead, uninstall the app and install the APK from https://download.kiwix.org/release/kiwix-android/ [or the page you developers find more suitable].

It would be nice if the message could only be displayed if the app detects that the device is running an Android version affected by this restriction.

This start-up message is inspired by the message displayed by LibreTorrent (though, in this case, the app can access files from the storage, but only from the _Downloads_ folder):

![message_libretorrent](https://github.com/kiwix/kiwix-android/assets/9334287/0a53a3b3-bb28-42d4-809c-cb4c44529ab1)

**Comment by shalenMathew** [comment]
can i work on this issue ?as a beginner would this be a good first issue ?

**Comment by kelson42** [comment]
IMO, we should put this in the app help first.

**Comment by MohitMaliFtechiz** [comment]
@vivadavid Thanks for your proposal it seems very helpful for the Play Store users because they are not aware of this Play Store restriction. 

@kelson42 Along with adding this in the help section, we should show the startup message to the user, for the very first time they install/update the application after implementing this. Since most of the users do not read the help section so for that user it would be helpful to show a startup message so they can be aware of this restriction.
