### ISSUE TITLE
version 3.8.1 from Google Play cannot find zim on SD card

### ISSUE THREAD

**Issue by tedaz** [kiwix/kiwix-android#3579]
**Describe the bug**

version 3.8.1 from Google Play cannot find zim on SD card - zim files download via this app stored on SD and can be find corrctly, zim files in folder "\SD card\Android\data\org.kiwix.kiwixmobile\files\Kiwix", whereas zim files downloaded by computer and copied to the same folder cannot be found. Tried same zim file, but only the file downloaded by the app can be found.
Same zim file works great on old version 3.6.0, and the old verson support zim files in any folder on SD card, whereas the new version 3.8.1 seems only support specific folder and only support app downloaded zim files.
**Expected behavior**

**Steps to reproduce the behavior:**
1. download zim file via a computer
2. copy the zim file to phone SD card
3. open the app on phone and go to tab "Library"
4. no zim file can be found by the app

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.8.1
- Device : Samsung Note 20 Ultra, Samsung Galaxy S10+, both use SD cards for zim storage
- OS version : Android 13 (One UI 5.1, Note 20 Ultra); Android 12 (One UI 4.1, Galaxy S10+)

**Logs**

**Comment by Jaifroid** [comment]
@tedaz Is this actually different from the previous PlayStore version? I've only ever been able to open a ZIM archive that the phone has downloaded, whether I set the storage to the SD card or to the main phone storage. This is because of the scoped storage that Android 11+ imposes on apps. See also #3577, which is the same issue but about the APK version.

Also, it might be worth testing (if you can) whether there is any difference for you with regard to the APK version, which has wider file access (though you may have to grant permission explicitly in Settings).

**Comment by MohitMaliFtechiz** [comment]
@tedaz Thanks for opening the issue.

@Jaifroid It is not related to #3577.  #3577 is related to our website apk, and this issue is related to the Play Store version.

I confirm this bug exists when we copy the externally downloaded zim file inside the app-specific directory in the SD card it is not able to read that file, but if you put the same ZIM file inside the app-specific directory in the `Internal storage` the app can read that file. So it is probably the file ownership issue with the SD card, I am debugging this and will place the fix ASAP.

**Comment by MohitMaliFtechiz** [comment]
@tedaz, @Jaifroid This issue will be fixed by https://github.com/kiwix/kiwix-android/pull/3582.
