### ISSUE TITLE
3.9.0 Welcome screen does not run and kiwix does not prompt for permissions.

### ISSUE THREAD

**Issue by s-i-m-s** [kiwix/kiwix-android#3611]
I can't see that anything has changed from 3.8.1 so this is a continuation of https://github.com/kiwix/kiwix-android/issues/3577 with a more accurate title.

Screen recording of install from 3.9.0 APK
https://i.imgur.com/jxmNqPs.mp4

3.9.0 was not available via the playstore at time of testing.

**Comment by MohitMaliFtechiz** [comment]
@s-i-m-s Thanks for opening the issue. Somehow shared preferences and databases are kept in the device of the previous version even after you installed the new application version. As you can see, the welcome screen is not launched even on new installation applications, it shows unable to open the ZIM file which means there is already an opened file that is present in the shared preference. Also, the list of ZIM files is already loaded in the library screen so it means the database is kept by the application.

Have you tried to refresh the ZIM file list, it will ask you for permission. 

Apart from this, the main issue device is keeping the share preference and databases of the previous version. However, this is not possible in Android since all the share preferences and databases are deleted from the device if you uninstall the application. 

So I suspect that your device is not deleting the corresponding while deleting the application. Have you enabled any settings in your device to keep the data? Has this behavior existed with other apps too?

**Comment by MohitMaliFtechiz** [comment]
@s-i-m-s I have placed a fix for it in #3618 even if the sharedpreference and database are kept by the device. When you try to open the ZIM file it will ask you for the permission.

**Comment by s-i-m-s** [comment]
@MohitMaliFtechiz

> Have you tried to refresh the ZIM file list, it will ask you for permission.

I had not but after doing so it prompted and after giving it permission everything worked normally.

>So I suspect that your device is not deleting the corresponding data while deleting the application. Have you enabled any settings in your device to keep the data? Has this behavior existed with other apps too?

Not that i'm aware of, I don't know that such a setting exists. I haven't noticed this with any other apps.

However now that you mention it if I go in and clear the data via the app info > storage menu and start the app it gives the normal welcome screen and permission prompts but if I clear the data and then uninstall and reinstall the app the same errors return.

I have no idea how this is happening , it doesn't appear to be keeping it from the previous install since that data was manually cleared but it definitely seems to be picking up extra data from somewhere that it should not be.

The app with the data cleared _should_ behave the same as a fresh install yet it doesn't.
