### ISSUE TITLE
Execution failed for task ':custom:shrinkBundleWikimedReleaseResources' - Java heap space error

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3634]
Description:
While attempting to build a bundle for publishing, I encountered the following error:

```
Execution failed for task ':custom:shrinkBundleWikimedReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.transforms.ShrinkAppBundleResourcesAction
   > Java heap space

```

I believe this is happening due to the large amount of the bundle size. We should add a reasonable amount of the heap size for the compiler in the build time NOT runtime as long as that satisfies for all our large custom apps.

Additional context:
https://github.com/kiwix/kiwix-android-custom/actions/runs/7337740623/job/19979122016#step:7:259

**Comment by gouri-panda** [comment]
This needs to be higer if the zim size is high. So i propose to allocate a reasonable amount in our virtual environment.

Additional context:
https://github.com/kiwix/kiwix-android-custom/actions/runs/7340642991/job/19986979759#step:7:260

**Comment by kelson42** [comment]
@MohitMaliDeveloper Its not normal we need so many memory on the heap. Please analyse and fix!

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have done the analysis for this, we need at least 6GB of java heap memory to build the bundle with a `2.13GB` ZIM file (I am taking [wikispecies](https://mirror.download.kiwix.org/zim/.hidden/custom_apps/wikispecies_en_all-app_maxi_2023-12.zim) ZIM file for this analysis which is the largest ZIM file for now). We need at least 6GB `java heap memory` to process the all resources that are inside the bundle. 

From the APK point of view, we don't need to increase the Java heap memory since we are uploading the ZIM file as an expansion file to the play store so the ZIM file is not inside the APK, and Gradle can easily create the APK with the given java heap memory. That's why APK uploading is working without upgrading it.
