### ISSUE TITLE
PlayStore test failing for custom app (Tunisie)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3638]
![image](https://github.com/kiwix/kiwix-android/assets/1029718/03e6dd14-4965-4906-8bc2-1694c2f998ed)

**Logs provided by google**
```kotlin
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_goog3_x86/generic_x86:9/PSR1.180720.092/5326075:userdebug/test-keys'
Revision: '0'
ABI: 'x86'
pid: 7630, tid: 7938, name: RxCachedThreadS  >>> org.kiwix.kiwixcustomtunisie <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    eax 00000000  ebx d3bb4cb8  ecx cc63eeaa  edx c0c77d10
    edi d00b6900  esi c0c77d0c
    ebp c0c77cd8  esp c0c77c70  eip d3b95847
```

**Video of crash provided by Google**

https://github.com/kiwix/kiwix-android/assets/34593983/a9086b86-5d81-4faf-93b1-e31b506ab913

**Second crash logs**
```kotlin
backtrace:
  #00  pc 0x000000000000d847  /data/app/org.kiwix.kiwixcustomtunisie-zpYpvD5NN5TIY8saQ90pwA==/split_config.x86.apk (Java_org_kiwix_libzim_Archive_getEntryByPath__Ljava_lang_String_2+119)
  #01  pc 0x00000000005f6b97  /system/lib/libart.so (art_quick_generic_jni_trampoline+71)
  #02  pc 0x00000000005f0b82  /system/lib/libart.so (art_quick_invoke_stub+338)
  #03  pc 0x00000000000a30ce  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+222)
  #04  pc 0x000000000029bca2  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+338)
  #05  pc 0x0000000000293e48  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1048)
  #06  pc 0x00000000005bc493  /system/lib/libart.so (MterpInvokeVirtual+691)
  #07  pc 0x00000000005e2d21  /system/lib/libart.so (ExecuteMterpImpl+14241)
  #08  pc 0x0000000000205188  /data/app/org.kiwix.kiwixcustomtunisie-zpYpvD5NN5TIY8saQ90pwA==/base.apk (org.kiwix.kiwixmobile.core.reader.ZimFileReader.getItem+84)
  #09  pc 0x0000000000266216  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2093054539)+598)
  #10  pc 0x000000000026c79c  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+220)
  #11  pc 0x0000000000293e2b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1019)
  #12  pc 0x00000000005bc493  /system/lib/libart.so (MterpInvokeVirtual+691)
  #13  pc 0x00000000005e2d21  /system/lib/libart.so (ExecuteMterpImpl+14241)
  #14  pc 0x0000000000204afc  /data/app/org.kiwix.kiwixcustomtunisie-zpYpvD5NN5TIY8saQ90pwA==/base.apk (org.kiwix.kiwixmobile.core.reader.ZimFileReader$$ExternalSyntheticLambda0.run+96)
  #15  pc 0x0000000000266216  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2093054539)+598)
  #16  pc 0x000000000026c79c  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+220)
  #17  pc 0x0000000000293e2b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1019)
  #18  pc 0x00000000005bd574  /system/lib/libart.so (MterpInvokeInterface+1444)
  #19  pc 0x00000000005e2f21  /system/lib/libart.so (ExecuteMterpImpl+14753)
  #20  pc 0x000000000019afd8  /data/app/org.kiwix.kiwixcustomtunisie-zpYpvD5NN5TIY8saQ90pwA==/base.apk (io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual+24)
  #21  pc 0x0000000000266216  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2093054539)+598)
  #22  pc 0x000000000026c79c  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+220)
```

Device specifications
* Model name = Pixel 2 (virtual)
* Manufacturer = Google
* Android version = Android 9 (SDK 28)
* Locale = ar_EG
* Screen size = 1080 x 1920
* Screen density (DPI) = 420
* RAM (total memory) -
* OpenGL ES version -
* ABI = x86
* CPU -

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda, @kelson42  I have tried to reproduce the error with many scenarios in the same configuration of the emulator which is provided by the pre-launched report. Unfortunately, I am not able to reproduce this error on my local machine. The logs provided by the pre-launched report are related to the getEntryByPath and getItem methods, these methods are already in the try-catch block so the crash is occurring inside the lib, and we can not handle this in Android since these methods are already inside the try-catch block.

I saw this report is generated by the Firebase Test lab. so I have tested our APK with the Firebase test lab. However, I have not seen this crash in the Firebase test lab report, so it probably hardly occurs. Might be @mgautierfr can better understand the error by the provided logs.

Apart from this, the Firebase test lab report provides a bug report in our application. This is a genuine error, our application is crashing below Api level 29, when we switch to external storage and it has less storage in it.

Error reported by the Firebase Test Lab report
![Screenshot from 2023-12-29 15-10-21](https://github.com/kiwix/kiwix-android/assets/34593983/d481fdaf-a116-400f-bf7a-d9c177c2da2f)


I confirm this bug exists.
![Screenshot from 2023-12-29 15-08-37](https://github.com/kiwix/kiwix-android/assets/34593983/d4fab70e-1ef1-4dc9-8ea6-ef9c3ae4abe2)

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thank you for the analysis. I guess without the devug symbols of libkiwix it will be difficult to do more.
@mgautierfr Please complete https://github.com/kiwix/java-libkiwix/pull/79 so we avoid in the future to end-up in such situations.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 For the second issue i have placed a fix in https://github.com/kiwix/kiwix-android/pull/3642

**Comment by kelson42** [comment]
I guess here there is nothing much more we can do. Closing.
