### ISSUE TITLE
Tabs Icon Ripple and Title

### ISSUE THREAD

**Issue by Sagar0-0** [kiwix/kiwix-android#3668]
**Describe the bug**

The tab icon in the Reader is not having a ripple effect and a title which is bad for accessibility.

**Expected behavior**

Add Ripple and title/desciption

**Steps to reproduce the behavior:**
1. Open the reader
2. See in the topbar
-->

**Screenshots**

![photo_6131796836109891986_y](https://github.com/kiwix/kiwix-android/assets/85388413/f32ad1d3-fe0b-4a5a-88a0-7d14344be2ee)

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : REALME GT NEO 3T
- OS version : 13

**Logs**

**Comment by satvik2131** [comment]
do anyone working on this project ?
 @Sagar0-0

**Comment by satvik2131** [comment]
oh okay , got it .

**Comment by kelson42** [comment]
@MohitMaliFtechiz @gouri-panda What is the strategy regarding this ripple effect? Do we have it in other cases? If "no" why?

**Comment by gouri-panda** [comment]
@kelson42 The Ripple affect contributes to a more engaging and user-friendly experience.The  visual feedback animation that occurs when a user taps a touchable UI element. It enhances UX by providing immediate feedback .
>Do we have it in other cases? If "no" why?

No, we haven't used it for another cases except when we click/long click the zim files We always aim for simple UX. Having this adds a little bit of complexity to our code that's why we didn't focus on this area.

**Comment by Sagar0-0** [comment]
@gouri-panda can you explain what kind of complexity? I have added the ripple and ready with a PR.

**Comment by kelson42** [comment]
The fix seems indeed trivial, but is that really an improvment? What are the criterias to put such an effect (or not)?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Yes this is an improvement. It improves the user experience and gives clarity of Interaction where the user clicks because it gives immediate feedback from the UI so the user can know if the click happened or not. Also, it is advisable to use a ripple effect to follow the Material design guidelines.
