### ISSUE TITLE
Search IME Action won't trigger Find

### ISSUE THREAD

**Issue by Sagar0-0** [kiwix/kiwix-android#3669]
**Describe the bug**

While searching in a zim, we have the search IME from keyboard which should be default trigger the find action on clicking, which is not happening.

**Expected behavior**

It should trigger find in page actiom

**Steps to reproduce the behavior:**
1. In the reader more, click on top search icon and open keyboard

**Screenshots**

![photo_6134236222915197824_y](https://github.com/kiwix/kiwix-android/assets/85388413/ad68873f-cecb-4252-b86c-cb6aed087493)

**Environment**
- Version of Kiwix Android :  3.9.1
- Device : REALME GT NEO 3T
- OS version : 13

**Logs**

**Comment by kelson42** [comment]
Indon't understand this ticket. Can we have a step by step description? What is "IME"?

**Comment by Sagar0-0** [comment]
The search icon, we have at the bottom right end of the keyboard is an IME action. and it should trigger the FIND IN PAGE event when clicked.

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 Here we have two functionalities on this screen.
1. Search entries from the ZIM file.
2. FIND IN Page functionality.

this keyboard is mainly used for searching the entries from the ZIM files and when this search button is pressed it should search for the entries like it is doing now. Since we are performing the search entries by using this keyboard,  It should not trigger the `FIND IN PAGE` event it is not relevant and it would confuse the user. For triggering the `FIND IN PAGE` event we have provided a specific button which is clearly mentioned if a user presses that button what functionality will perform. 

@kelson42, @gouri-panda What do you think?

**Comment by Sagar0-0** [comment]
With the keyboard IME action, it is not triggering anything for now. Also, I strongly believe the keyboard IME search action should only trigger(if any) the action "Find in page" as it is the only action possible from that particular search field and is also user-expected. It should not be the case where we are triggering different search from IME and different from FIND IN PAGE button.

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 We have implemented a feature in our app at https://github.com/kiwix/kiwix-android/issues/2896 that is more relevant for this search IME option so I am closing this ticket as this feature is not valid anymore.
