### ISSUE TITLE
Release versions are lower in the custom apps

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3677]
**Describe the bug**
In the custom apps release versions are lower. Due to that we can't release further.

**Expected behavior**
It should be higer than their predecessors.

![Screenshot 2024-01-19 at 10 43 19](https://github.com/kiwix/kiwix-android/assets/43576162/19ed8107-a8c8-44c9-ac55-dbbd325186b3)

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda The version code of custom apps is based on the current date.
https://github.com/kiwix/kiwix-android/blob/3f19f55b99c83152d9f6be2d910894c9409c8637/buildSrc/src/main/kotlin/custom/CustomApp.kt#L58

can you please tell me what app is this on which we are facing this issue?

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda Thanks for confirming, I am checking what's going on here.

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda I have checked the code and the code looks correct. There is no error in the code. It is based on the current year and day of the year with an added 0 at last.


https://github.com/kiwix/kiwix-android/blob/3f19f55b99c83152d9f6be2d910894c9409c8637/buildSrc/src/main/kotlin/custom/CustomApp.kt#L58

For E.g. it is printing the `7240220` version for today's date(`Mon Jan 22 15:53:57 IST 2024`) which is correct. However, I am wondering why it was published the `wikivoyage DE` app with `24` suffix as the previous year is `2023` so the version code should be `7233650`. Can you please confirm how the previous version is published of this app?

I also checked for other custom apps and there the prefix is `23` as shown in the below images.

![Screenshot from 2024-01-22 15-57-07](https://github.com/kiwix/kiwix-android/assets/34593983/d78554c6-7c4c-4865-820c-3da32fc03370)
![Screenshot from 2024-01-22 15-56-38](https://github.com/kiwix/kiwix-android/assets/34593983/76ee4ca3-790e-4203-8a9c-12a81994148c)
![Screenshot from 2024-01-22 15-56-02](https://github.com/kiwix/kiwix-android/assets/34593983/51fa38fb-de7d-4ce2-a48b-bebb685fd872)


However, now we can not publish the "wikivoyage DE" app via this code since the version code is lower. We need to change the date pattern from `YYDDD0` to `YYDDD00` so that it will add one more 0 at the last of the version code so that our version code will be bigger than the previous one. @gouri-panda what do you think?

**Comment by kelson42** [comment]
@MohitMaliFtechiz None of the custom apps have been published manually. But maybe our code has changed in the meantime?

**Comment by gouri-panda** [comment]
>However, I am wondering why it was published the wikivoyage DE app with 24 suffix as the previous year is 2023 so the version code should be 7233650. Can you please confirm how the previous version is published of this app?

@MohitMaliFtechiz This app was released this year. It wasn't released manually.
>However, now we can not publish the "wikivoyage DE" app via this code since the version code is lower. We need to change the date pattern from YYDDD0 to YYDDD00 so that it will add one more 0 at the last of the version code so that our version code will be bigger than the previous one. @gouri-panda what do you think?

Yes, it will solve the problem for short period of time. But I think we should find the root cause. I don't know but maybe we'll change next year again for this issue.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz None of the custom apps have been published manually. But maybe our code has changed in the meantime?

@kelson42 No code has been changed related to the version code of custom apps.

> @MohitMaliFtechiz This app was released this year. It wasn't released manually.

@gouri-panda So how the previous version of this app was published if this app is released this year?

>  @MohitMaliFtechiz @gouri-panda Wikivoyage DE has never been published publically. Can we not just remove the test versions  if this is an app specific problem? I'm not eager to modify this very sensitive part of the code for just one app. https://github.com/kiwix/kiwix-android/issues/3681#issuecomment-1913176583_

@kelson42 Yes, this seems like an app-specific problem to me. Since I have checked for other apps too, there is no version code error, we can do this way.

> Yes, it will solve the problem for a short period of time. But I think we should find the root cause. I don't know but maybe we'll change next year again for this issue.

@gouri-panda IMO not I have checked for other apps and there is no error like this. e.g. see these workflows of different years.

2023:- https://github.com/kiwix/kiwix-android-custom/actions/runs/7358085883/job/20030774741#step:9:280

2024:- https://github.com/kiwix/kiwix-android-custom/actions/runs/7559139153/job/20582720564#step:9:308

But yes something is wrong somewhere can you please grant me access to this app so that I can find any clue about this error.

**Comment by MohitMaliFtechiz** [comment]
Okay now I have found everthing here is the last action we used for publishing this application on 31 Dec, and it was uploaded with the wrong version code see https://github.com/kiwix/kiwix-android-custom/actions/runs/7363771582/job/20058787286#step:9:280.

It is because we have used the wrong date pattern. We are using the `YYDDD0` pattern This represents the year in a "week year" format. That's why it is changing the year on the last date of the year. e.g. if we convert the `Sun Dec 31 6:32:26 IST 2023` with this format it will give the `243650` version code instead of `233650`. we should use the `yyDDD0` pattern This represents the year in a "calendar year" format. It will give the correct output for the last day of the year as well. As for the same date as mentioned above it is giving the output `233650` which is correct.

As you can see the difference is in the below images.

With `YYDDD0` format

![Screenshot from 2024-01-29 18-57-43](https://github.com/kiwix/kiwix-android/assets/34593983/4588aa02-aa0c-4e68-a3f5-ff2fa27019c4)

With `yyDDD0` format

![Screenshot from 2024-01-29 18-57-00](https://github.com/kiwix/kiwix-android/assets/34593983/a084d7a7-2303-4c44-974b-95e2278a1509)

**Comment by MohitMaliFtechiz** [comment]
> Yes, it will solve the problem for short period of time. But I think we should find the root cause. I don't know but maybe we'll change next year again for this issue.

@gouri-panda For this issue I have placed a fix in the https://github.com/kiwix/kiwix-android/pull/3681 now it will not happen even if we upload any custom app on the last day of the year.

But what about the `wikivoyage De` app? it is already uploaded with the higher version code. Is there any option to remove the app bundle from the playstore?
