### ISSUE TITLE
[Bug] Read aloud won't stop for closed tabs

### ISSUE THREAD

**Issue by Sagar0-0** [kiwix/kiwix-android#3740]
**Describe the bug**

If the read-aloud feature is running and reading through the page, it will not stop when the specific tab or all tabs is closed.

**Expected behavior**

It should STOP when the tab is closed which it was reading

**Steps to reproduce the behavior:**
1. Open a ZIM and start Read aloud from top right corner.

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : REALME GT
- OS version : 13

**Logs**

**Comment by Sagar0-0** [comment]
Let me work on this please

**Comment by Sagar0-0** [comment]
Please assign this issue to me before I start working on it.

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 Thanks for opening the issue.

> Let me work on this please

Okay, I am assigning this issue to you.

**Comment by Sagar0-0** [comment]
When the tab switcher is clicked, should we pause the reading?
And after that when the tab is closed, then we can stop the read.... what's your take?

**Comment by Sagar0-0** [comment]
Is it possible to check which index tab was playing the tts(real aloud feature)?

**Comment by MohitMaliFtechiz** [comment]
> Is it possible to check which index tab was playing the tts(real aloud feature)?
I have created a function that will stop the tts only if it was playing. I am using that in the closeTab and closeAllTabs methods.

Yes, we can do it, we can achieve it by saving the index of the webview on which tts is running, and if the user closes that tab we should stop the tts as well otherwise tts service should work as before.

**Comment by Sagar0-0** [comment]
Is it already present as currentWebViewIndex in CoreReaderFragment? I think this is the one which we have to use, if no then please tell me what is the use of it?

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 `currentWebViewIndex` is for managing the current webView. We should not rely on this for tts issue. Since there is a scenario where 2 tabs are open, and we run the tts for the 2nd tab and then switch to the first tab, in this case, `currentWebViewIndex` will be for the first tab and if closes that tab it will close the tts service, but the tts service was for the 2nd tab.

**Comment by Sagar0-0** [comment]
@MohitMaliFtechiz from where we can get the tab index of current tts. Please review the PR I made, I think then I just need to change the currentWebViewIndex to a new variable currentTtsIndex

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 When you are starting the tts service at that time save the current position of the webView.
