### ISSUE TITLE
[Bug] Diagnostic Report not doing anything

### ISSUE THREAD

**Issue by Sagar0-0** [kiwix/kiwix-android#3751]
**Describe the bug**

We have a option to share the diagnostic report from the help section from the Drawer. In some combinations of the selected checkboxes, we are not generating a text file(.txt), instead just generating just a string, and then it is not sharable to any source, means sharing is failed.

**Expected behavior**

It should share the string value also, or we can modify the selection combination to always generate the .txt files.

**Steps to reproduce the behavior:**
1. Opent the drawer and go to Help
2. Send diagnostic report
3. Unselect 2nd and 3rd option
4. You'll see we are sharing the string value and not a txt file
5. It will not share the thing and fail.

**Screenshots**

https://github.com/kiwix/kiwix-android/assets/85388413/e8fad77b-140e-4581-95c7-2c7f0e662148

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : REALME GT
- OS version : 13

**Logs**

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 Thanks for opening the issue, it is not sharing on WhatsApp if you unselect the `Application Logs` from the selected list. `Application Logs` generate a file and attach it to the send body. However, On other applications, we are able to share this text (WhatsApp unable to handle this intent's type (vnd.android.cursor.dir/email) without a file). Try to send the details via email, telegram, etc. We are mainly using this functionality for sharing the crash report on Gmail. However, we should improve our code so that Whatsapp also handles this intent type.

https://github.com/kiwix/kiwix-android/blob/f7a34c1b42fbe2a109952c9f9324464a8ea879a6/core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt#L101-L119

**Comment by Sagar0-0** [comment]
IMO, we should always generate a txt file, as the string value is very large and that might not be supported for some sharing options, and also have readability issues.

**Comment by MohitMaliFtechiz** [comment]
Text is supported with all sharing applications our intent type is not supported for most of the applications so we should improve our intent type so that all sharing applications will support it, and in the Txt file, we are copying the same content that we are sending. 

>  and also have readability issues.

What type of readability issue you are pointing out? We are formatting all the strings before sending it. It is for reading the devs not for the end user.

https://github.com/kiwix/kiwix-android/blob/f7a34c1b42fbe2a109952c9f9324464a8ea879a6/core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt#L123-L132.

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 Let me handle this issue, since it needs a very small fix but it is an important functionality in our application.

**Comment by Sagar0-0** [comment]
> Let me handle this issue
That's fine 🥲

> What type of readability issue you are pointing out?
A very large text file on whatsapp or any other sharing app

> Text is supported with all sharing applications
Some apps might have some message size limit, that was my concern

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 I have placed a fix for it in https://github.com/kiwix/kiwix-android/pull/3752, you can test it and give your feedback on it.
