### ISSUE TITLE
New nightly APK signatures prevent easy update

### ISSUE THREAD

**Issue by ThreeDeeJay** [kiwix/kiwix-android#3838]
**Describe the bug**

Each new nightly APK seems to have a different signature, which prevents us from easily updating the app and instead requires uninstalling and reinstalling the app, or disabling signature verification system-wide, which can result in unforeseen consequences.
This also prevents [getting nightly updates via Obtainium](https://github.com/ImranR98/Obtainium/issues/1005#issuecomment-2094737004).

**Expected behavior**

**Steps to reproduce the behavior:**
1. 

- Download and install a non-latest APK like https://download.kiwix.org/nightly/2024-05-11/kiwix-universal-2024-05-11.apk
- Download and install a newer/latest APK like https://download.kiwix.org/nightly/2024-05-12/kiwix-universal-2024-05-12.apk
- The app will refuse to install with some generic error, unless you use [App Manager](https://github.com/MuntashirAkon/AppManager)' only install option, which shows this error:
```
Could not install app because the package name is in use

INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package org.kiwix.kiwixmobile signatures do not match newer version; ignoring!
```

**Screenshots**

![Screenshot_20240512-192224_App Manager_1](https://github.com/kiwix/kiwix-android/assets/71472458/0a160b57-d18a-4bba-b846-71010fce935c)

**Environment**
- Version of Kiwix Android : 3.10.1 (7231001) [2024-05-12]
- OS version : Android 14

**Logs**

**Comment by kelson42** [comment]
@MohitMaliFtechiz Does that impact our released APK?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Does that impact our released APK?
PRIO issue!!!

@kelson42 No, it does not impact our released APK. Our released APK can easily be updated because it is generated with the same keystore(with the same signature) since it uses the playStore keystore to generate the APK. 

https://github.com/kiwix/kiwix-android/blob/2612cf83a8703f66e8ea1dc4c5e6c65312283579/.github/workflows/release.yml#L21-L40

As shown in the below video, in my device `3.10.0` version is installed from our website, and when I downloaded version `3.10.1` and tried to install it shows me to update the existing installed application.

https://github.com/kiwix/kiwix-android/assets/34593983/fee56675-44e9-4063-a685-038b90332368

Apart from this, yes nightly will build with different signatures every time since we are not using any keystore for generating the APK so it takes the default debug signature of the current process for generating the APK which is different every time on CI.

https://github.com/kiwix/kiwix-android/blob/2612cf83a8703f66e8ea1dc4c5e6c65312283579/.github/workflows/nightly.yml#L25-L44

**Comment by kelson42** [comment]
@MohitMaliFtechiz If I get everything right, we could use the same keystore for nightlies like for releases and issue would be soleve? Correct? Any known disadvantages?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz If I get everything right, we could use the same keystore for nightlies like for releases and issue would be soleve? Correct? 

Yes, the problem will resolve if we use the same keystore.

> Any known disadvantages?

Yes, there is a known disadvantage that a user facing in https://github.com/kiwix/kiwix-android/issues/3839. it will show the update notification from playStore.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz If I get everything right, we could use the same keystore for nightlies like for releases and issue would be soleve? Correct? 

Yes, the problem will resolve if we use the same keystore.

> Any known disadvantages?

Yes, there is a known disadvantage that a user facing in https://github.com/kiwix/kiwix-android/issues/3839. it will show the update notification from playStore.

**Comment by ThreeDeeJay** [comment]
Thanks, I can confirm it's working on my end now 👌
