### ISSUE TITLE
User complains that ongoing downloads are lost during app update

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3919]
It should not

**Comment by kelson42** [comment]
Do you have any feedback about that issue?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have tested this and the ongoing download is starting again after the application update. However, if users face this situation due to some condition it is Fetch related issue since the downloading is handled by the Fetch library, and we are already in the process of replacing the fetch library with downloadManager https://github.com/kiwix/kiwix-android/pull/3935, and we replace this library very soon from the project so this error will be automatically fixed.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thank you for the analysis and agree with your conclusion. Closing issue.
