### ISSUE TITLE
Automatically publish to PlayStore for internal testing team

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3942]
Internal testers have to install manually the nightlies to be able to test latest codebase. At least to me, this is already a bit too cumbersome because:
* I have to be on the front of the workstation
* I have to actively do the operation

For macOS/iOS, we have an other model which is pretty good IMHO: Each Monday, during the night, latest dev version is published on Testflight. This allows me effortless to test and play with cutting edge version and test latest bug fixes/ features.

I would like to have the same with Kiwix Android.

Similar to #1777

**Comment by kelson42** [comment]
@MohitMaliFtechiz Is that doable? Do you see any challenge or problem doing so?

**Comment by kelson42** [comment]
@MohitMaliFtechiz Version code is comouted automatically and not part of the git repository, so I don't understand the problem!?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Version code is computed automatically (independently of the version name) and is not part of the git repository, so I don't understand the problem!?

@kelson42 Yes version code is computed independently, but for now, we are generating the version code on behalf of the version name. We have to change this to automatically generate without depending on the version name like we are doing for custom apps.

https://github.com/kiwix/kiwix-android/blob/48efdfa8c88a4463fa731a5ed9c26a6995cbf68d/app/build.gradle.kts#L25-L29

**Comment by kelson42** [comment]
@MohitMaliFtechiz Computing the version code from the version name is not the smartest thing we have done.

I propose to change this by:
* Starting from current version code number as "base" and,
* add/increment with the number of days elapsed between current day and today (17 juli 2024).

Would that work?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Okay so it would be like this,

The current version is 7231101 which we started as a base. and the current date is 17 July 2024 so the number of days would be 199, so the final version code will be  7231101 + 199 = 7231300. Yes, this would work, it will automatically change the version code every day.

**Comment by kelson42** [comment]
Yourcomputation seems wrong, 199 is not correct (no clue where this number comes from). it should 0 as the differrent beetween now and the 17 July 2024 is zero.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 199 is the current day of the year which I am adding in this.

> add/increment with the number of days elapsed between current day and today (17 juli 2024).

From your comment, I thought you meant to add this year's days to the base version name. But it will always add the 0 in the last of the version code, which will be the same for the next APK/bundle which we will upload for this ticket if we do not change the "base" version. Here we are trying to implement the dynamic version code which could automatically increase without manual interaction which is required for this ticket to implement. Or your meaning of "Current day" was the previous set day on the version code? it is not possible at least in gradle because we can not save anything in gradle file. We need to statically type the version code or any method can be placed inside gradle for generating the version code like the date's method. 

Please let me know if I misunderstood anything.
