### ISSUE TITLE
"Night mode" OR "dark mode"?

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3950]
Our feature is called "night mode" but the standarz naming (in browsers) seems to be "dark mode". Wozldn't thst be a good iidea to rename the feature that way?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 The "dark mode" would be a better name for our feature. Apart from the browsers, in smartphones also, this feature name is  "Dark theme/Dark mode". In Whatsapp also, this feature name is "Dark mode". So it is better to use the "Dark mode" for our feature since it works like "dark mode/Dark theme", and the default naming for this feature in phones is also the same.


![1721728975239](https://github.com/user-attachments/assets/b4ac1232-39c9-4fec-9ca1-83679fc51400)

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thx, then you can go ahead with the fix. Not only labels should be uodated, but variables, functions, etc...
