### ISSUE TITLE
"Pause", not "pause"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3967]
![Screenshot_20240729_210015_Kiwix.jpg](https://github.com/user-attachments/assets/e19d7dd3-341a-47c6-bceb-9b42cf8fbc07)

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Thanks for opening the bug, this issue is part of https://github.com/kiwix/kiwix-android/pull/3935, and we have fixed this issue in https://github.com/kiwix/kiwix-android/pull/3935/commits/d56db8e7cd38a99a0f97dbf333d4a09d0c3bc467.

![Screenshot from 2024-07-30 11-17-27](https://github.com/user-attachments/assets/36ffa993-969a-4124-95a9-82fc34b0fadd)
![Screenshot_20240730-111243](https://github.com/user-attachments/assets/ae20d970-c3ea-496d-8a4c-023768ae3059)

**Comment by kelson42** [comment]
@MohitMaliFtechiz Ok, then just update PR description to indicate ir fixes this issue.
