### ISSUE TITLE
Revamp Settings > Storage

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3970]
Here are the requested changes:
* Stop using an overlay/dialog box, the radio button to choose between the multiple storages should be directly in the settings
* It should be clearer (written?) what is total and empty space
* The exact path used should be written. In can this is the storage chosen, then we know what it is as this is a settings stored in the configuration. But in case of a non-used storage, this is hypothetical as there is no settings, the value should come from the code. This last bullet point is important as we will move from the private to the public app directory... people with everything in the private app directory should keep their private app directory but new user should better use public app directory.

**Comment by kelson42** [comment]
@MohitMaliDeveloper Please propose first a mockup so we can validate the design first.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 For the UI part we will remove the storage Selection dialog from the settings and will show radio buttons for selecting the storage(if the SD card is available then it will show in the radio button, Otherwise a single radio button of internal storage will be show on the setting screen with proper total and empty space available in the storage). The storage path will be show on the settings screen in front of the selected storage, which will come from the code.

| Dialog will remove  | Radio button will show like this |
| ------------- | ------------- |
| ![Screenshot_20240806-104446](https://github.com/user-attachments/assets/32145754-0817-4e0f-a109-e8f1f1d3dd8a) | ![Screenshot_20240806-104549](https://github.com/user-attachments/assets/9b7f899c-a25f-4069-8ebb-914fdbd65050) |
