### ISSUE TITLE
Online library can not be retrieved

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3991]
On Samsung tablet with Android14, newly, the online library can not be retrieved. The spinner keeps running...

![Screenshot_20240911_073854_Kiwix](https://github.com/user-attachments/assets/b3301d6e-9891-44ca-9592-2b6f41a8ab6c)

It should work obviously as I have plenty of bandwidth

**Comment by Popolechien** [comment]
I confirm having the same issue on Nothing Phone (2), also running android 14

**Comment by kelson42** [comment]
@MohitMaliFtechiz This the current TOP priomissue. The PRshould include:
* The fix
* A proper automated test

**Comment by MohitMaliFtechiz** [comment]
@kelson42, @Popolechien I have checked it and the online library showing on the tablet.

![Screenshot from 2024-09-12 11-26-08](https://github.com/user-attachments/assets/8fe3378f-effb-4124-b0d8-f25ab032b946)

It seems the issue is something else on your devices.

Can you please tell me if the spinner is showing infinitely? There is no error message showing on the screen after some time? e.g. "Swipe down for library".

Also, can you please provide the device logs? please try to open the OnlineFragment and wait for some time so that the application collects the errors from the logs, and then please attach the log.txt here. It would be helpful in debugging the problem.

**Comment by Popolechien** [comment]
Spinner is infinitely showing, yes, and there was no error message. Swiped down (to refresh I assume?) and there was no change in behaviour (or to be correct, the screen did not "move", which is the normal Swipe down behaviour). Seems to be happening only on the playstore version however, I had installed the APK to test for #3993 and now have the library ¯\_(ツ)_/¯
I'm adding the diagnostic report in case there's anything different between the playstore version (here) and the APK (in #3993)
[Diagnostic Report.txt](https://github.com/user-attachments/files/16974583/Diagnostic.Report.txt)

**Comment by kelson42** [comment]
> Spinner is infinitely showing, yes, and there was no error message. Swiped down (to refresh I assume?) and there was no change in behaviour (or to be correct, the screen did not "move", which is the normal Swipe down behaviour). Seems to be happening only on the playstore version however, I had installed the APK to test for #3993 and now have the library ¯_(ツ)_/¯ I'm adding the diagnostic report in case there's anything different between the playstore version (here) and the APK (in #3993) [Diagnostic Report.txt](https://github.com/user-attachments/files/16974583/Diagnostic.Report.txt)

Same here for me. It is the very first time I experienced this bug myself but I have heard many time from users suffering from this. Here the preliminary things I would like to see implemented:
* Please show the spinner in the middle of the of the screen (not at the top)
* Below the spinner we should have something allowing ideally the user (and in case of problem the dev) to see the progress of the download AND/OR the current status. Therefore it can be a progress bar, but maybe better is a (small font) message like: reaching remote library, starting download of the online library, X% downloading library, remote library downloaded, parsing remote library.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Which versions of Kiwix are impacted by this bug?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 The versions after we introduced Android 14 have been impacted. Mainly the internal testing APK are impacted by this bug since we have not released the application in production after introducing the Android 14.

**Comment by kelson42** [comment]
The colorset is not OK in darkmode
![Screenshot_20240919_195658_Kiwix](https://github.com/user-attachments/assets/c9e164ed-fd80-4153-8e2d-d66324c0caaf)

Before coding place explain why this does not work out of the box with default dark mode colorset of Android.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Here we have used the `mine_shaft_gray900` for text which is not in the `night-color.xml` that's why it is showing a black color on the text in this dialog. At the runtime, it picks the color from night-color.xml` or `color.xml` based on the theme, and if the matched configuration property is not found then it shows the default file's color. Just like the string file(when there is a translation available in the current language then it shows the translated language other it shows the default text which is present in the English version).

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please make a PR and ensure we use everywhere Android standard colors so we never run again in this kind of problem.
