### ISSUE TITLE
"Send diagnostic report" function should open the user's email client

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#4005]
In the Help tab, the Send diagnostic report only generates a diagnostic report, without an indication of the next steps. 

On my phone (Nothing Phone, Android 14), clicking on Send details opens the Sharing tab, but this by default lists my friends on Whatsapp/Signal. Meanwhile, the `Send feedback` option does open the user's email client directly so this clearly is something that can be directly actioned by Kiwix.

**Comment by kelson42** [comment]
I will assess this issue bwfore implementation.

**Comment by MohitMaliFtechiz** [comment]
@Popolechien, @kelson42 This is not directly doable to implement this. Since we are attaching a file in email with device logs, and currently we are using the `ACTION_SEND` which supports the attaching files in email(But it shows the other apps in the suggestion list, like it is showing currently). For opening directly user's email client we have to use the `ACTION_SENDTO` with `data = "mailto:` which is only handled by the email apps so it will open the email client of the user's device(But in this action, we can not attach the files see https://developer.android.com/guide/components/intents-common#ComposeEmail for more details). 

As shown in the below video it is directly showing the email client, but there is no log file attached in the body.

https://github.com/user-attachments/assets/f1918473-5b55-4fa2-ac78-6a6c6d658175


An approach is to implement this, we can remove the file from the diagnostic report, and add the device logs in the email body.
