### ISSUE TITLE
Widgets in dark mode

### ISSUE THREAD

**Issue by fitzz2894** [kiwix/kiwix-android#4009]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kelson42** [comment]
@MohitMaliDeveloper Do the widgets don't respect the dark/light mode?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper Do the widgets don't respect the dark/light mode?

@kelson42 In the widgets we are using (icons, and images) because of this, the widget looks the same in both dark and day modes.


Day mode:

![1727780497162](https://github.com/user-attachments/assets/d0e9e4ff-7400-42e5-b608-88446805c28c)

Night mode:

![1727780496975](https://github.com/user-attachments/assets/66481a67-9d5f-4798-9534-665807c14606)

**Comment by fitzz2894** [comment]
I was talking about the "medical Wikipedia" app by kiwix team widget wasn't
made in dark mode

**Comment by fitzz2894** [comment]
I didn't know you got kiwix as an app, where you got all medical Wikipedia.
No need to make dark mode, I am shifting to kiwix ap from medical Wikipedia
app
