### ISSUE TITLE
Many problems at first side loading of a ZiM file

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#4067]
![Image](https://github.com/user-attachments/assets/199078a4-af9f-4c65-bec5-039b84e6528d)

Here the points:
* It seems the message in the screenshot is displayed only once at first. I wonder if it would not be best to just show the usual one "do you want to move or copy..." and write an explanation in the help.
* Ater closing copy, it goes straight to copy... but actually it should propose the chooser of storage (I have a SD card)

**Comment by MohitMaliFtechiz** [comment]
> It seems the message in the screenshot is displayed only once at first. I wonder if it would not be best to just show the usual one "do you want to move or copy..." and write an explanation in the help.

@kelson42 good idea, because now, we have improved the copy/move dialog message(https://github.com/kiwix/kiwix-android/pull/4069) so users can better understand this. Also, we will add a cancel button.

> Ater closing copy, it goes straight to copy... but actually it should propose the chooser of storage (I have a SD card)

The copied ZIM file will go into the current selected storage https://github.com/kiwix/kiwix-android/issues/3941#issuecomment-2284446727 (I remember I had a conversation about this with you). For example:- if the user has selected "internal storage" in the settings screen the file will go into the "internal storage", the same for the SD card. If there is not enough storage available it will ask to configure the storage(for example if there is not enough storage in internal storage it asks to configure the storage to an SD card). 

But thinking about your opinion, it is better to provide the option for selecting the storage before copy/move since it will let users directly copy/move the files in their wanted storage without configuring the storage from settings.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thx, you get things right. The storage chooser should only be displayed once at start (and only if there is a chiice to make).

**Comment by kelson42** [comment]
@MohitMaliFtechiz Once CI green, please rebase and merge and release for testing in PS

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Once CI green, please rebase and merge and release for testing in PS

@kelson42 I can not directly merge the PR, it needs your approval. The PR is now ready for review with all the videos and screenshots.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 The application has been released in testing on PS. https://github.com/kiwix/kiwix-android/actions/runs/11837938150/job/32985980177.
