### ISSUE TITLE
All versions of the app on Google Pixel Tablet do not install except for the Google Play version.

### ISSUE THREAD

**Issue by AEleven-GitHub** [kiwix/kiwix-android#4098]
All versions of the app on Google Pixel Tablet do not install except for the Google Play version.

**Comment by MohitMaliFtechiz** [comment]
@AEleven-GitHub Thanks for opening the issue. The previous versions of the application can not be installed along with the Google Play app due to the same `package name`. Are you trying to install the application version when a Google Play app is already installed?

We have resolved this issue in https://github.com/kiwix/kiwix-android/issues/3933, can you please try to install [kiwix-universal-2024-11-21.apk](https://download.kiwix.org/nightly/2024-11-21/kiwix-universal-2024-11-21.apk) and let us know it is installing or not in your device? if not installing what error it is showing?

**Comment by MohitMaliFtechiz** [comment]
@AEleven-GitHub Any feedback about the last APK? Is it installing on your device?
