### ISSUE TITLE
Make package structure robust

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#469]
**Is it a ?**

- [ ] Bug Report

- [ ] Feature Request

- [x] Refactor

#### Description

Right now the package structure isn't very good. Infact it isn't followed very well. It should be made robust and code should be packaged into different sections on the basis of features. It is crucial before trying to make the application testable.

@mhutti1 @brijeshshah13  views ?

**Comment by brijeshshah13** [comment]
@srv-twry I very much agree with you. Even I felt the same need because whenever I try to introduce something new by replacing the old, I end up dealing with multiple conflicts with several packages. May I ask how do you plan to solve this?

**Comment by srv-twry** [comment]
@brijeshshah13 Please check the PR :)

**Comment by abdulwd** [comment]
@siddharth2010 Since you are refactoring the package structure we should discuss the new package structure in this issue. Can you propose a new package structure here as is done in #471. Also, you are using underscore in some package names like `content_provider` which I think should be changed to `contentprovider` according to the Java docs [here](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html).
I think we should change the name of **KiwixMobileAcitvity** to **MainActivity**. What is your opinion?

**Comment by siddharth2010** [comment]
@abdulwd , I think the package structure suggested in [#471](https://github.com/kiwix/kiwix-android/pull/471) is really good. So I would suggest the same basic structure, with a few minor changes here and there. (like the renaming of the package `main` (containing `SplashActivity.java`) to `splash`). 
Also, I yes, you are absolutely right. According to the [google java style guide](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names) , all the names like `library_view`, `fileselect_view`, `zim_manager`, `content_provider`, need to be changed.
So here is the structure proposed by me:

.
├── common
│   ├── base
│   │   ├── BaseActivity.java
│   │   ├── BasePresenter.java
│   │   ├── BaseFragment.java
│   │   └── contract
│   │       ├── Presenter.java
│   │       └── ViewCallback.java
│   ├── data
│   │   ├── contentprovider
│   │   │   └── ZimContentProvider.java
│   │   ├── database
│   │   │   ├── entity
│   │   │   │   ├── BookDataSource.java
│   │   │   │   ├── BookmarksSpec.java
│   │   │   │   ├── LibraryDataSource.java
│   │   │   │   ├── NetworkLanguageSpec.java
│   │   │   │   └── RecentSearchSpec.java
│   │   │   ├── BookDao.java
│   │   │   ├── BookmarksDao.java
│   │   │   ├── KiwixDatabase.java
│   │   │   ├── NetworkLanguageDao.java
│   │   │   └── RecentSearchDao.java
│   │   └── network
│   │       ├── KiwixService.java
│   │       └── UserAgentInterceptor.java
│   ├── di
│   │   ├── components
│   │   │   └── ApplicationComponent.java
│   │   ├── modules
│   │   │   ├── ApplicationBindingModule.java
│   │   │   ├── ApplicationModule.java
│   │   │   ├── JNIModule.java
│   │   │   └── NetworkModule.java
│   │   └── PerActivity.java
│   ├── settings
│   │   ├── CustomSwitchPreference.java
│   │   └── KiwixSettingsActivity.java
│   ├── utils
│   │   ├── files
│   │   │   ├── FileReader.java
│   │   │   ├── FileSearch.java
│   │   │   └── FileUtils.java
│   │   ├── BookUtils.java
│   │   ├── Constants.java
│   │   ├── DimenUtils.java
│   │   ├── DocumentParser.java
│   │   ├── LanguageUtils.java
│   │   ├── NetworkUtils.java
│   │   ├── RateAppCounter.java
│   │   ├── StorageUtils.java
│   │   ├── StyleUtils.java
│   │   └── TestingUtils.java
│   └── views
│   │   ├── bottom_tab
│   │   │   ├── PageBottomTab.java
│   │   │   ├── PageBottomTabLayout.java
│   │   │   └── TabDrawerAdapter.java
│   │   ├── table
│   │   │   └── TableDrawerAdapter.java
│   │   └── web
│   │   │   ├── KiwixWebView.java
│   │   │   ├── ToolbarScrollingKiwixWebView.java
│   │   │   ├── ToolbarStaticKiwixWebView.java
│   │   │   └── WebViewCallback.java
│   │   ├── AnimatedProgressBar.java
│   │   ├── AutoCompleteAdapter.java
│   │   ├── CompatFindActionModeCallback.java
│   │   ├── KiwixActionBarDrawerToggle.java
│   │   ├── LanguageSelectDialog.java
│   │   ├── SliderPreference.java
└── modules
│   ├── bookmarks_view
│   │   ├── BookmarksActivity.java
│   │   ├── BookmarksPresenter.java
│   │   └── contract
│   │       └── BookmarksViewCallback.java
│   ├── clients
│   │   ├── KiwixWebChromeClient.java
│   │   └── KiwixWebViewClient.java
│   ├── downloader
│   │   ├── Chunk.java
│   │   ├── ChunkUtils.java
│   │   ├── DownloadFragment.java
│   │   ├── DownloadIntent.java
│   │   └── DownloadService.java
│   ├── library
│   │   ├── entity
│   │   │   ├── LibraryNetworkEntity.java
│   │   │   └── MetaLinkNetworkEntity.java
│   │   └── LibraryAdapter.java
│   ├── main
│   │   └── SplashActivity.java
│   ├── search
│   │   ├── contract
│   │   │   └── SearchViewCallback.java
│   │   ├── KiwixSearchWidget.java
│   │   ├── SearchActivity.java
│   │   └── SearchPresenter.java
│   ├── text_to_speech
│   │   └── KiwixTextToSpeech.java
│   └── zimmanager
│       ├── contract
│       │   └── ZimManageViewCallback.java
│       ├── fileselectview
│       │   ├── contract
│       │   │   └── ZimFileSelectViewCallback.java
│       │   ├── ZimFileSelectFragment.java
│       │   └── ZimFileSelectPresenter.java
│       ├── libraryview
│       │   ├── contract
│       │   │   └── LibraryViewCallback.java
│       │   ├── LibraryFragment.java
│       │   ├── LibraryPresenter.java
│       │   └── LibraryUtils.java
│       ├── SectionsPagerAdapter.java
│       ├── ZimManageActivity.java
│       └── ZimManagePresenter.java
├── KiwixApplication.java
├── KiwixMobileActivity.java
├── KiwixMobileErrorActivity.java

The structure is in the  branch: `siddharth2010/Package_Refactor`, in the main kiwix repo.

**Comment by abdulwd** [comment]
@siddharth2010 I think we should have separate packages for **KiwixMobileActivity** and **KiwixErrorActivity**. We can rename **KiwixMobileActivity** to **MainActivity** and move it to a package called `main`.
Please have a look at this [sample app](https://github.com/googlesamples/android-architecture/tree/todo-mvp/) so that it may give us a greater insight into architecture. You can find more sample apps at this [link](https://github.com/googlesamples/android-architecture).

**Comment by abdulwd** [comment]
@siddharth2010 I think we should have separate packages for **KiwixMobileActivity** and **KiwixErrorActivity**. We can rename **KiwixMobileActivity** to **MainActivity** and move it to a package called `main`.
Please have a look at this [sample app](https://github.com/googlesamples/android-architecture/tree/todo-mvp/) so that it may give us a greater insight into architecture. You can find more sample apps at this [link](https://github.com/googlesamples/android-architecture).

**Comment by siddharth2010** [comment]
@abdulwd Sure. I will look into it right now and get back to you as soon as possible.

**Comment by siddharth2010** [comment]
@abdulwd , I guess I now understand the idea behind having separate packages for `KiwixMobileActivity` and `KiwixErrorActivity`, and I think it's the right way to go. I will do this.

**Comment by abdulwd** [comment]
Closed via #748
