### ISSUE TITLE
Make Views dumber in MVP

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#488]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request

#### Feature Description

Right now, even though we are implementing MVP pattern in the project, there is a lot of logic inside the Views which is against the principles of MVP. The logic inside the Views should be as minimum as possible. This would lead to easier testing experience in the future.

We will need to setup a lot of things and hence needs to be done Activity/Fragment wise. 
I would setup it up and implement it for a smaller view and take the feedback. If agreed, we can move on to applying it on all the views.

Can only be done after 

- [ ] #469 
- [ ] #459

**Comment by Aditya-Sood** [comment]
Hello @srv-twry 
I'm just over the beginner threshold in Android, and want to contribute to the app portion of the project.
I have a decent idea about the separation of data, app logic, & user interaction in the MVP model.

Are there any activities which you haven't covered yet which I can have a go at?

**Comment by srv-twry** [comment]
@Aditya-Sood 
Hi! Actually i haven't started yet. I am having to wait for other issues to be solved before i can go ahead with this. 
Also this issue is a big issue so yes we can split them once it's time to work on it.

**Comment by Aditya-Sood** [comment]
@srv-twry 
Which list of GSoC ideas are you exactly referring to? I couldn't find one anywhere

**Comment by srv-twry** [comment]
[here](http://wiki.kiwix.org/wiki/GSoC#GSoC_2018_Ideas_List)

**Comment by Aditya-Sood** [comment]
Thanks :+1: 
Let me know when we can start working on it

**Comment by kelson42** [comment]
@srv-twry @Aditya-Sood What should we do with this ticket? Is that still actual?

**Comment by Aditya-Sood** [comment]
@kelson I'll have a go at this once I'm through with the remaining deliverables?

**Comment by kelson42** [comment]
@Aditya-Sood thx

**Comment by macgills** [comment]
@Aditya-Sood MVP is not really what we want anymore, MVI is much more our aim

**Comment by Aditya-Sood** [comment]
@macgills thanks, I'll read up on MVI and discuss the changes with you before doing anything

**Comment by kelson42** [comment]
I'm not comfortable with this kind of ticket because It's on meta level, making decision and implementing this needing:
* a good understanding of the whole app (in particular if a new pattern is introduced)
* a good technical know-how (in particular if a new pattern is introduced)
* a lot of time.

I dont' want this happening like this. If we need a new architecture of the software which will need dozens an probably hundreds of hours to be invested to be successful. I want to have:
* a formal discussion about this
* the works properly split from the beginning in small tasks.

Last but not least: I want the dev leads to lead that effort if they judge this is necessary. So @macgills, if you think a dedicated effort of software rearchituring needs to be done (beside the usual small day by day revamping decisions), please open a ticket an lets discuss it together. To be honest, I hope we won't have to do that.

Here these conditions are not re-united. The idea is maybe not bad but it does not have tu support of the dev leads and a lot of details would have to be evaluted. I don't think we need to go through all of that now.
