### ISSUE TITLE
Fix "Credits" dialog box colors in night mode

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#618]
### Environment
  * version of the software you use : Version 2.3 build 55
  * device / operating system : Samsung Galaxy S6 (Android 7.0)
  
### The Bug:
I think that the colors inside the "credits" dialog box should also be inverted in night mode.

![screenshot_20180311-165341](https://user-images.githubusercontent.com/32238400/37252748-b7ad2632-254c-11e8-859b-26d51de97001.png)

#### Steps to reproduce:

  1. Go to "settings"
  2. Toggle night mode to "on" (if not done already)
  2. tap on "Credits"

**Comment by GeVic** [comment]
@siddharth2010 can i do this ?

**Comment by MayankChuriwal** [comment]
@GeVic You may proceed with the same. If you want any reference issue #526

**Comment by siddharth2010** [comment]
Sure @GeVic , Go ahead!

**Comment by GeVic** [comment]
@siddharth2010 Thanks. One question though, since the content of the alert box is in webview so i am not able to change the text colour dynamically when the theme is changed. 
Any suggestions ?

**Comment by GeVic** [comment]
@siddharth2010 @mhutti1 Since credit dialog box contained **HTML (with `pre` tag)** so i changed the code as follows:
`if(nightMode(sharedPreferenceUtil)) {`
        `view.setBackgroundColor(0);`
        `view.loadUrl("file:///android_asset/credits_dark.html");`
      `} else {`
        `view.loadUrl("file:///android_asset/credits.html");`
      `}`
You can see here **i created two copies of credits.html** that is to change the text colour on theme change as i **wasn't able to change it dynamically**.

![credit](https://user-images.githubusercontent.com/29516629/37258780-c19e631c-25a2-11e8-9832-d0a4f113c654.gif)

Any suggestions ??

**Comment by mhutti1** [comment]
Javascript is your friend. You can inject it into the page. I think that would likely be the easiest option.

**Comment by siddharth2010** [comment]
Exactly. This is the best idea AFAIK.

**Comment by GeVic** [comment]
@mhutti1 @siddharth2010 oh it totally slipped off my mind. Creating pull request now
