### ISSUE TITLE
Add ability to share ZIM files from within the app

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#779]
#### Feature Description

Long clicking a downloaded file should give the option to either delete or share via a top menu as happens in bookmarks.

![screenshot_20180628-225705_kiwix](https://user-images.githubusercontent.com/2286937/42060313-52fd2b38-7b1e-11e8-867a-16c47b67159d.jpg)

**Comment by mhutti1** [comment]
Also see #770

**Comment by sparrow007** [comment]
can i work on this issue ??

**Comment by Aditya-Sood** [comment]
@mhutti1 when you say share the ZIM file in-app, do you mean to do so over a Wi-Fi connection between the two devices? And/or share a link to download that particular ZIM file?

**Comment by Aditya-Sood** [comment]
Sharing it over a WiFi connection would be a really useful feature for users in regions with poor internet connectivity. And also, users in those regions would probably be the ones that depend most on the app, of all the users.

**Comment by mhutti1** [comment]
For this specific issue I mean share via the standard android sharing interface.

**Comment by Aditya-Sood** [comment]
Could you clarify what you're referring to by that? I'm only aware of Android Beam for sharing files between devices

**Comment by Aditya-Sood** [comment]
Using the Wi-Fi P2P API would be a better option though - It supports connectivity over a greater distance and a much higher file transfer rate (thanks to Wi-Fi Direct), than the NFC pairing + Bluetooth connection used by Android Beam

**Comment by mhutti1** [comment]
![image](https://user-images.githubusercontent.com/2286937/43479563-98273296-94f8-11e8-9c87-33799683c5bf.png)

I mean share like this. If you want to share with wifi IMO the user can just install an app.

**Comment by mhutti1** [comment]
I think in general it would be sharing the file always.

**Comment by Aditya-Sood** [comment]
Majority of the ZIM files available are too large to be uploaded over normal data connections to a social media site or as an attachment in an email - So in situations where Internet access (when available) is not restricted, it would be better to allow the user to share just the link to the ZIM file, instead of forcing them to wait and upload the entire file.

SMS, clipboard and notes won't support sharing the actual file (only the link), so how do you want to go about email & social?

**Comment by abdulwd** [comment]
@Aditya-Sood We intend to share the file(s) between 2 devices without an internet connection. Apps like **ShareIt**, **Mi Drop**, etc can handle the transferring from one device to another. For this issue, we just need to add a share button which will open the bottom sheet as shown by @mhutti1 with **ShareIt/Mi Drop/or any other app for file transfer**. The user can then select the desired app for transferring the file. As @mhutti1 says, you can ask the user to download the app for file transfer if there are none on the device.

**Comment by Aditya-Sood** [comment]
@abdulwd thanks but did you go through the whole thread?
My query essentially is:
- Should the app only share the actual ZIM file (and thus only apps which can do that should show up in the menu),
OR
- Should it also offer to share the link (for the apps which would be inefficient in/don't support sending the entire ZIM file, like Email, Social Media, Notes, etc)?

**Comment by Aditya-Sood** [comment]
@mhutti1 could you clarify?

**Comment by mhutti1** [comment]
Sharing a link is not really possible as it is not part of the ZIM spec. I think only sharing the file would be fine.

**Comment by Aditya-Sood** [comment]
Okay
I'll get started then

**Comment by mhutti1** [comment]
No but if it gets done by then we will add it.

**Comment by Aditya-Sood** [comment]
Apologies for this delay
I'll try and finish it by the end of coming weekend

**Comment by Aditya-Sood** [comment]
Regarding the location of the option to share:
I'm planning on adding it within the WebView, so that the users would be able to share the ZIM file they are currently reading

I could alternatively/additionally add the Share option in the Downloads Library, wherein you could select multiple ZIM files for sharing. This would also require shifting the 'Delete' functionality to the new action bar that appears upon selecting the file(s).

@mhutti1 pl clarify which design flow to proceed with

**Comment by Aditya-Sood** [comment]
Also, what's the procedure to add string translations to the string resources?
Do I simply use Google Translate for converting 'Share' to other languages and manually make the addition to the resource?

**Comment by Aditya-Sood** [comment]
UPDATE: I'm facing difficulty in identifying/obtaining URI for the currently open ZIM file.

Despite spending 3 days on the same trying to get the file uri using getIntent() on the main activity (KiwixMobileActivity), & subsequently tinkering with methods from the ZimContentProvider, but I still couldn't obtain the direct uri to the currently open file.

Examining the logs of errors and crashes, I gather that the content provider parses and returns the HTML/CSS from the actual ZIM file. Other methods like getFilePath() didn't help either.

I can't confirm this due to lack of experience with the project on my behalf and absence of documentation, but I have a hunch that the content provider can't help me obtain the uri of the currently open file.

**Comment by Aditya-Sood** [comment]
So I've decided to instead focus on adding the ability to share from the Downloads Library page

**Comment by abdulwd** [comment]
> Regarding the location of the option to share:
> I'm planning on adding it within the WebView, so that the users would be able to share the ZIM file they are currently reading
> 
> I could alternatively/additionally add the Share option in the Downloads Library, wherein you could select multiple ZIM files for sharing. This would also require shifting the 'Delete' functionality to the new action bar that appears upon selecting the file(s).

@Aditya-Sood You should not add the share button within the **WebView** but in the downloaded books tab i.e. **Device** tab. You can shift the delete functionality to the contextual action bar.

> UPDATE: I'm facing difficulty in identifying/obtaining URI for the currently open ZIM file.

You can try using:
`Uri.fromFile(new File(ZimContentProvider.getZimFile()));`

Also, you should rebase your branch on [3.0](https://github.com/kiwix/kiwix-android/tree/3.0).

**Comment by Aditya-Sood** [comment]
@mhutti1 
Could you please review and give a feedback? Thanks

**Comment by mhutti1** [comment]
Could you please follow abduls advice and then I will gladly give you a review :)

**Comment by Aditya-Sood** [comment]
On it
