### ISSUE TITLE
Some articles are not found by the search function

### ISSUE THREAD

**Issue by IrgendwerA8** [kiwix/kiwix-android#871]
Kiwix 2.4 Build 182160
Android 4.1.2
Wikipedia 2018-06-30 German, no video, 32.2 GB in 2 GB chunks

Tapping the magnifier icon for "find" and entering "DCF77" (case doesn't matter) will not show any matching article.

But if you look up "Funkuhr" (which can be found) and tap the link "DCF77" in the text, the "DCF77"
article is shown - so it is available.

(Had this issue for other articles too, but cannot remember the name anymore yet.)

**Comment by MennovdHurk** [comment]
https://github.com/kiwix/kiwix-android/issues/84

**Comment by IrgendwerA8** [comment]
Isn't #84 a different issue? There is no article "FFT", but in my case the article "DCF77" is no ambiguous abbreviation, but existing "natively"...

**Comment by cipo7741** [comment]
Sadly it's the same problem, because its forcing each search with the first letter upper case, rest lower case.
FFT = Fft
USA = Usa
DCF77 = Dcf77
DDR = Ddr (results into Ddrescue)

As you work with recent kiwix and recent wiki, it's strange it still persists.
https://github.com/kiwix/kiwix-android/issues/84#issuecomment-347545915

**Comment by kelson42** [comment]
This is fixed in Kiwix Android 3.0
