### ISSUE TITLE
German & English Wikipedia no pictures on some Articles with kiwix 2.4

### ISSUE THREAD

**Issue by dazed-horizon** [kiwix/kiwix-android#899]
There are no pictures on some articles on Kiwix for Android Version 2.4 (latest version).
I am using the "wikipedia_de_all_novid_2018-11.zim" , downloaded it twice, checksum ok. I tried different Android phones with Android 7.0 and Android 4.1, still no pictures. For example on these articles:
"Deutschland" (no pictures at all!) and "Binomial-Verteilung" (scroll down, no pictures) as well as "Deutsche Nationalhymne". Sadly since Kiwix Version 2.3 too many errors... Not good. P.S.: my wikipedia is not chuncked in parts, it is in one big file.

**Comment by mhutti1** [comment]
I can see pictures on that article so this is likely device specific.

**Comment by okkebal** [comment]
I cannot see pictures in Kiwix 2.4 on Wikipedia EN 2018-10 on these articles:

- Adam Curry
- Germany
- IBM

There must be many more articles without pictures. I do see pictures in most articles. It also only just EN Wikipedia that has problems for me.

I guess this is caused by the crawler being blocked from downloading pictures. You can't keep requesting pictures indefinitely from some hosts. They will block you, thinking its a DDOS or something

**Comment by okkebal** [comment]
I am using Kiwix 2.4 on android Pie. Using 2018-10-24 EN Wikipedia (78.1 GB in one file)

**Comment by dazed-horizon** [comment]
@ mhutti1   It is not device specific. I have tried it on 8 different devices, checked the checksum and still no luck. And as  "okkebal" said, there are many articles without pictures! I really hope that there will be finally a version which works...

**Comment by kelson42** [comment]
@okkebal @dazed-horizon I have checked, the problem is with the ZIM file itself. Not with Kiwix for Android. An effort is currently ongoing on MWoffliner to identify why time to time images are not scraped properly. Here is one of these tickets https://github.com/openzim/mwoffliner/issues/462.
