### ISSUE TITLE
Correctly handle icudt*.dat in android.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-android#9]
For now the icudt*.dat is loaded by the java code on android.

However, the kiwixlib has code to load the same data. 
It is only used if we are on a apple platform (with the define \_\_APPLE__).

We should simplify this. Only one code should handle this. Either the kiwixlib itself or the caller code, but not both.

**Comment by kelson42** [comment]
@mgautierfr You confirm you have fixed that bug?

**Comment by kelson42** [comment]
@MohitMaliDeveloper Anything stops us to fix this ticket right now?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 ,

Actually It's not loading ```icudt*.dat``` data on android side. It is only coping the ```.dat``` file from asset folder to **filesDir/icu** ```(/data/data/org.kiwix.kiwixmobile/files/icu)``` folder and returning the directory path to ```kiwixlib```. Because we can not directly access file from assets folder in android (this returns a ```InputStream```).

**Here is code which we are using to copy file from asset folder**

https://github.com/kiwix/kiwix-android/blob/30773dad42bd90b8d108bd292e47ab474a9df032/core/src/main/java/org/kiwix/kiwixmobile/core/JNIInitialiser.kt#L33

**and setting the folder to setICUDataDirectory**

https://github.com/kiwix/kiwix-android/blob/30773dad42bd90b8d108bd292e47ab474a9df032/core/src/main/java/org/kiwix/kiwixmobile/core/JNIInitialiser.kt#L30

We are only setting the directory to ```kiwixlib``` which contains the ```icudt*.dat``` file. kiwixlib loading ```.dat``` file itself for it's use cases.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Sounds good and appropraite to me.
@mgautierfr Do you still believe we should do differently?

**Comment by kelson42** [comment]
@mgautierfr Any feedback?

**Comment by kelson42** [comment]
I will close the ticket because there is nothing more we can reasonably do. Usinf libicu or libicu dat from Android seems to me pretty risky, with a very low added value. We rely here on the libzim and the libkiwix. If libkiwix allows to load a dat file like the libzim then we will be glad to use such a feature.
