### ISSUE TITLE
convert build.gradle to build.gradle.kts

### ISSUE THREAD

**Issue by soloturn** [kiwix/kiwix-android#947]
gradle switched over from groovy to kotlin. please convert build.gradle, and settings.gradle to kotlin:
https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/
as documented there this does not need to be done at once.

**Comment by iadeelzafar** [comment]
@soloturn  I'd like to work on this issue.

**Comment by soloturn** [comment]
@iadeelzafar much appreciated, i made a spike in branch st-build-gradle-kotlin. feel free to pull it in ...

**Comment by soloturn** [comment]
@iadeelzafar any news here?

**Comment by iadeelzafar** [comment]
@soloturn no. I'm focusing on some other things rn.

**Comment by kelson42** [comment]
@macgills Please comment on this idea

**Comment by macgills** [comment]
I am in two minds about it because kotlin is great and hardly anyone knows Groovy that well.
On the other hand most examples are all in groovy and the kotlin constructs are often clunkier, my gut says it would be better to postpone to a later date to see how well kotlin takes off as replacement even though the advantages are very cool

**Comment by kelson42** [comment]
@macgills Do I have understood properly? We should wait a new version of Google Studio that we can carry on with this? Should we postpone it?

**Comment by macgills** [comment]
We can do it now, Android Studio 4.0 shouldn't be far off and post modularisation most of our buildscript code is already in kotlin

**Comment by kelson42** [comment]
@macgills OK, so lets do it.
