### ISSUE TITLE
fix button names in download notification

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#967]
Instead of "Play", we should Probably have the string "Resume"

**Steps to reproduce the behavior:**
1. Download a zim file
2. Pause the download
3. Open notifications

**Screenshots**

![screenshot_20190210-190737](https://user-images.githubusercontent.com/32238400/52534540-d383f500-2d68-11e9-8601-770a016ac103.png)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Samsung S6
- OS version : Android 7.0

**Comment by iadeelzafar** [comment]
I can work on this

**Comment by siddharth2010** [comment]
Sure. go ahead

**Comment by iadeelzafar** [comment]
@siddharth2010 this is the Kiwix Home Page that I see.

![screenshot_24](https://user-images.githubusercontent.com/36811908/52538832-21b0ec80-2d99-11e9-84de-69b7d656df15.png)

I've noticed that this is the updated one. How can I get this one so that I could download zim files?

![screenshot_25](https://user-images.githubusercontent.com/36811908/52538862-7f453900-2d99-11e9-822d-2ea5a95c1e5e.png)

**Comment by iadeelzafar** [comment]
Hi @siddharth2010 , Previously I was on Kiwix VERSION 2017-07 Build 1. Now after seeing your post, I went to Project>Module Settings>app>flavors and updated Version code>55>version name>2.4
This is what I see in my app settings now.
![screenshot_27](https://user-images.githubusercontent.com/36811908/52539310-71de7d80-2d9e-11e9-9122-f0d5b3340a55.png)
But I don't think it's version 2.4 because the app still looks the same as before on my emulator. There's something I'm doing wrong. Kindly enlighten me on this.

**Comment by siddharth2010** [comment]
oh no all that was not actually required.

The version I am using is the one in the latest master branch. In the settings activity, it says version 2.4 Build 55. Just like you have in your screenshot.

**Comment by iadeelzafar** [comment]
@siddharth2010  I'm also using the latest master branch but my Home Page looks like this.
![screenshot_24](https://user-images.githubusercontent.com/36811908/52539668-d1d72300-2da2-11e9-8db5-ee3fc3023d27.png)
I've noticed that this is the latest one which I'm not seeing because of which I also can't figure out where to download zim files.
![screenshot_25](https://user-images.githubusercontent.com/36811908/52539670-d3085000-2da2-11e9-925d-e4ce0180bf41.png)

**Comment by iadeelzafar** [comment]
My version was VERSION 2017-07 Build 1 and it still is the same. I tried to edit it to the latest one but I failed.

**Comment by abdulwd** [comment]
@iadeelzafar The below one is the older home screen, it was changed because it looked more like help screen. You can open a new tab to go to the download button or go to **menu -> Get Content** to download a ZIM file.

**Comment by iadeelzafar** [comment]
@abdulwd  Oh okay. The above screen which I'm seeing is that the latest one? I'm curious about it because in the settings I see VERSION 2017-07 Build 1.

**Comment by abdulwd** [comment]
Yes, that is the latest one.

**Comment by iadeelzafar** [comment]
@abdulwd Look, this is the menu I see. There's no Get Content here.

![screenshot_28](https://user-images.githubusercontent.com/36811908/52561988-d93c1200-2e1e-11e9-9dd7-6abd536cb49b.png)

**Comment by mhutti1** [comment]
@iadeelzafar You are running the wrong flavour of the app. You need to change your build variant in Android Studio Settings.

**Comment by iadeelzafar** [comment]
@mhutti1 Thanks a lot for helping out. kiwixDebug is the build variant I should use.?

**Comment by iadeelzafar** [comment]
@siddharth2010 I've completed this task. One thing I'm unsure about is that should I add Resume translations as well in all other string files or some specific languages only?

**Comment by siddharth2010** [comment]
I think we should do it in all the files.

**Comment by abdulwd** [comment]
We should have translations in as many languages as possible but if you use google translate or any other automated translators the translations will be mostly inaccurate. @mhutti1 How do we handle string translations? I think one should only translate to languages which are known to him/her so it is as accurate as possible.

**Comment by mhutti1** [comment]
Only edit strings.xml all the others are auto generated based on manual translations from translatewiki.net
